package com.sourcetrace.eses.entity;
// Generated 23 Jun, 2020 5:09:17 PM by Hibernate Tools 5.0.6.Final

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.annotations.FilterDef;
import org.hibernate.annotations.Filters;
import org.hibernate.annotations.OrderBy;
import org.hibernate.annotations.ParamDef;
import org.hibernate.annotations.UpdateTimestamp;

/**
 * AgentAccessLog generated by hbm2java
 */
@Entity
 @FilterDef(name = "branchFilter", parameters = @ParamDef(name = "branchIdParam", type = "string"))@Filters(@org.hibernate.annotations.Filter(name="branchFilter", condition="branch_id in ( :branchIdParam )"))
@Table(name = "AGENT_ACCESS_LOG")
public class AgentAccessLog implements java.io.Serializable {

	private Long id;
	private String profileId;
	private Date login;
	private Date lastTxnTime;
	private String serialNo;
	private String mobileVersion;
	private String branchId;
	private String updatedUser;
	private Date updatedDate;

	
	public AgentAccessLog() {
	}

	public AgentAccessLog(String profileId, Date login, Date lastTxnTime, String serialNo, String mobileVersion,
			String branchId) {
		this.profileId = profileId;
		this.login = login;
		this.lastTxnTime = lastTxnTime;
		this.serialNo = serialNo;
		this.mobileVersion = mobileVersion;
		this.branchId = branchId;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "ID", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@Column(name = "PROFILE_ID", length = 45)
	public String getProfileId() {
		return this.profileId;
	}

	public void setProfileId(String profileId) {
		this.profileId = profileId;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "LOGIN", length = 10)
	public Date getLogin() {
		return this.login;
	}

	public void setLogin(Date login) {
		this.login = login;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "LAST_TXN_TIME", length = 19)
	public Date getLastTxnTime() {
		return this.lastTxnTime;
	}

	public void setLastTxnTime(Date lastTxnTime) {
		this.lastTxnTime = lastTxnTime;
	}

	@Column(name = "SERIAL_NO", length = 50)
	public String getSerialNo() {
		return this.serialNo;
	}

	public void setSerialNo(String serialNo) {
		this.serialNo = serialNo;
	}

	@Column(name = "MOBILE_VERSION", length = 50)
	public String getMobileVersion() {
		return this.mobileVersion;
	}

	public void setMobileVersion(String mobileVersion) {
		this.mobileVersion = mobileVersion;
	}

	@Column(name = "BRANCH_ID", length = 50)
	public String getBranchId() {
		return this.branchId;
	}

	public void setBranchId(String branchId) {
		this.branchId = branchId;
	}
	@OneToMany(mappedBy = "accessLog", fetch = FetchType.LAZY)
	@OrderBy(clause = "ID ASC")
	private Set<AgentAccessLogDetail> agentAccessLogDetails;
	
	@Column(name = "UPDATED_USER", length = 50, columnDefinition = "VARCHAR(255)")
	public String getUpdatedUser() {
		return updatedUser;
	}

	public void setUpdatedUser(String updatedUser) {
		this.updatedUser = updatedUser;
	}
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "UPDATED_DATE",  length = 19)
	@UpdateTimestamp
	public Date getUpdatedDate() {
		return updatedDate;
	}

	public void setUpdatedDate(Date updatedDate) {
		this.updatedDate = updatedDate;
	}
}
