package com.sourcetrace.eses.entity;
// Generated 23 Jun, 2020 5:09:17 PM by Hibernate Tools 5.0.6.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * BankInfo generated by hbm2java
 */
@Entity
@Table(name = "BANK_INFO")
public class BankInfo implements java.io.Serializable {

	private Long id;
	//private Farmer farmer;
	private Long farmerId;
	private String accountNo;
	private String bankName;
	private String branchName;
	private String sortCode;
	private String swiftCode;
	private String accType;
	
	private String accName;

	public BankInfo() {
	}

	public BankInfo( String accountNo, String bankName, String branchName, String sortCode,
			String swiftCode, String accType, String accName) {
		//this.farmer = farmer;
		this.accountNo = accountNo;
		this.bankName = bankName;
		this.branchName = branchName;
		this.sortCode = sortCode;
		this.swiftCode = swiftCode;
		this.accType = accType;
	
		this.accName = accName;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "ID", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	/*
	 * @ManyToOne(fetch = FetchType.LAZY)
	 * 
	 * @JoinColumn(name = "FARMER_ID") public Farmer getFarmer() { return
	 * this.farmer; }
	 * 
	 * public void setFarmer(Farmer farmer) { this.farmer = farmer; }
	 */
	@Column(name = "ACCOUNT_NO", length = 35)
	public String getAccountNo() {
		return this.accountNo;
	}

	public void setAccountNo(String accountNo) {
		this.accountNo = accountNo;
	}

	@Column(name = "BANK_NAME", length = 250)
	public String getBankName() {
		return this.bankName;
	}

	public void setBankName(String bankName) {
		this.bankName = bankName;
	}

	@Column(name = "BRANCH_NAME", length = 35)
	public String getBranchName() {
		return this.branchName;
	}

	public void setBranchName(String branchName) {
		this.branchName = branchName;
	}

	@Column(name = "SORT_CODE", length = 35)
	public String getSortCode() {
		return this.sortCode;
	}

	public void setSortCode(String sortCode) {
		this.sortCode = sortCode;
	}

	@Column(name = "SWIFT_CODE", length = 35)
	public String getSwiftCode() {
		return this.swiftCode;
	}

	public void setSwiftCode(String swiftCode) {
		this.swiftCode = swiftCode;
	}

	@Column(name = "ACC_TYPE", length = 100)
	public String getAccType() {
		return this.accType;
	}

	public void setAccType(String accType) {
		this.accType = accType;
	}

	

	@Column(name = "ACC_NAME")
	public String getAccName() {
		return this.accName;
	}

	public void setAccName(String accName) {
		this.accName = accName;
	}

	@Column(name = "FARMER_ID")
	public Long getFarmerId() {
		return farmerId;
	}

	public void setFarmerId(Long farmerId) {
		this.farmerId = farmerId;
	}

}
