package com.sourcetrace.eses.entity;
// Generated 23 Jun, 2020 5:09:17 PM by Hibernate Tools 5.0.6.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * CityWarehouseDetail generated by hbm2java
 */
@Entity

@Table(name = "CITY_WAREHOUSE_DETAIL")
public class CityWarehouseDetail implements java.io.Serializable {
	 public enum TYPE {
	        PROCUREMENT, PROCUREMENT_MTNT, PROCUREMENT_MTNR, SUPPLIER_PROCUREMENT,PROCUREMENT_TRACEABILITY,COLD_STORAGE,COLD_STORAGE_STOCK_TRANSFER,BUY
	    }

	private Long id;
	private CityWarehouse cityWarehouse;
	private Date date;
	private int type;
	private Long referenceId;
	private Long previousNumberOfBags;
	private Double previousLoss;
	private Double previousGrossWeight;
	private Double previousSorted;
	private Long txnNoOfBags;
	private Double txnGrossWeight;
	private Double txnLoss;
	private Double txnSorted;
	private Long totalNumberOfBags;
	private Double totalGrossWeight;
	private Double totalLoss;
	private Double totalSorted;
	private String description;
	private String batchNo;
		public CityWarehouseDetail() {
	}

	
	public CityWarehouseDetail(Long id, CityWarehouse cityWarehouse, Date date, int type, Long referenceId,
				Long previousNumberOfBags, Double previousLoss, Double previousGrossWeight, Double previousSorted,
				Long txnNoOfBags, Double txnGrossWeight, Double txnLoss, Double txnSorted, Long totalNumberOfBags,
				Double totalGrossWeight, Double totalLoss, Double totalSorted, String description, String batchNo) {
			this.cityWarehouse = cityWarehouse;
			this.date = date;
			this.type = type;
			this.referenceId = referenceId;
			this.previousNumberOfBags = previousNumberOfBags;
			this.previousLoss = previousLoss;
			this.previousGrossWeight = previousGrossWeight;
			this.previousSorted = previousSorted;
			this.txnNoOfBags = txnNoOfBags;
			this.txnGrossWeight = txnGrossWeight;
			this.txnLoss = txnLoss;
			this.txnSorted = txnSorted;
			this.totalNumberOfBags = totalNumberOfBags;
			this.totalGrossWeight = totalGrossWeight;
			this.totalLoss = totalLoss;
			this.totalSorted = totalSorted;
			this.description = description;
			this.batchNo = batchNo;
		}


	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "ID", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CITY_WAREHOUSE_ID")
	public CityWarehouse getCityWarehouse() {
		return this.cityWarehouse;
	}

	public void setCityWarehouse(CityWarehouse cityWarehouse) {
		this.cityWarehouse = cityWarehouse;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "TXN_DATE", length = 19)
	public Date getDate() {
		return this.date;
	}

	public void setDate(Date date) {
		this.date =date;
	}

	@Column(name = "TYPEE")
	public int getType() {
		return this.type;
	}

	public void setType(int type) {
		this.type = type;
	}

	@Column(name = "TXN_REFERENCE_ID")
	public Long getReferenceId() {
		return this.referenceId;
	}

	public void setReferenceId(Long referenceId) {
		this.referenceId = referenceId;
	}

	
	@Column(name = "PREVIOUS_GROSS_WEIGHT", precision = 20, scale = 3)
	public Double getPreviousGrossWeight() {
		return this.previousGrossWeight;
	}

	public void setPreviousGrossWeight(Double previousGrossWeight) {
		this.previousGrossWeight = previousGrossWeight;
	}

	@Column(name = "TXN_NO_OF_BAGS")
	public Long getTxnNoOfBags() {
		return this.txnNoOfBags;
	}

	public void setTxnNoOfBags(Long txnNoOfBags) {
		this.txnNoOfBags = txnNoOfBags;
	}

	@Column(name = "TXN_GROSS_WEIGHT", precision = 20, scale = 3)
	public Double getTxnGrossWeight() {
		return this.txnGrossWeight;
	}

	public void setTxnGrossWeight(Double txnGrossWeight) {
		this.txnGrossWeight = txnGrossWeight;
	}

	@Column(name = "TOTAL_NO_OF_BAGS")
	public Long getTotalNumberOfBags() {
		return this.totalNumberOfBags;
	}

	public void setTotalNumberOfBags(Long totalNumberOfBags) {
		this.totalNumberOfBags = totalNumberOfBags;
	}

	@Column(name = "TOTAL_GROSS_WEIGHT", precision = 20, scale = 3)
	public Double getTotalGrossWeight() {
		return this.totalGrossWeight;
	}

	public void setTotalGrossWeight(Double totalGrossWeight) {
		this.totalGrossWeight = totalGrossWeight;
	}

	@Column(name = "DESCRIPTION")
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "BATCH_NO", length = 20)
	public String getBatchNo() {
		return this.batchNo;
	}

	public void setBatchNo(String batchNo) {
		this.batchNo = batchNo;
	}


	@Column(name = "PREVIOUS_NO_OF_BAGS")
	public Long getPreviousNumberOfBags() {
		return previousNumberOfBags;
	}

	public void setPreviousNumberOfBags(Long previousNumberOfBags) {
		this.previousNumberOfBags = previousNumberOfBags;
	}
	@Column(name = "PREV_LOSS", precision = 20, scale = 3)
	public Double getPreviousLoss() {
		return previousLoss;
	}

	public void setPreviousLoss(Double previousLoss) {
		this.previousLoss = previousLoss;
	}
	@Column(name = "PREV_SORTED", precision = 20, scale = 3)
	public Double getPreviousSorted() {
		return previousSorted;
	}

	public void setPreviousSorted(Double previousSorted) {
		this.previousSorted = previousSorted;
	}
	@Column(name = "TXN_LOSS", precision = 20, scale = 3)
	public Double getTxnLoss() {
		return txnLoss;
	}

	public void setTxnLoss(Double txnLoss) {
		this.txnLoss = txnLoss;
	}
	@Column(name = "TXN_SORTED", precision = 20, scale = 3)
	public Double getTxnSorted() {
		return txnSorted;
	}

	public void setTxnSorted(Double txnSorted) {
		this.txnSorted = txnSorted;
	}
	@Column(name = "TOTAL_LOSS", precision = 20, scale = 3)
	public Double getTotalLoss() {
		return totalLoss;
	}

	public void setTotalLoss(Double totalLoss) {
		this.totalLoss = totalLoss;
	}
	@Column(name = "TOTAL_SORTED", precision = 20, scale = 3)
	public Double getTotalSorted() {
		return totalSorted;
	}

	public void setTotalSorted(Double totalSorted) {
		this.totalSorted = totalSorted;
	}

}
