package com.sourcetrace.eses.entity;
// Generated 23 Jun, 2020 5:09:17 PM by Hibernate Tools 5.0.6.Final

import static javax.persistence.GenerationType.IDENTITY;

import java.io.File;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Transient;

import org.hibernate.annotations.CreationTimestamp;
import org.hibernate.annotations.UpdateTimestamp;

/**
 * DocumentUpload generated by hbm2java
 */
@Entity
@Table(name = "DOCUMENT_UPLOAD")
public class DocumentUpload implements java.io.Serializable {
	 public static enum docType{
	    	Farmer,DealerInspection,PermitApplication,PremisesInspection,Fumigator,FumigatorProof,FieldInspection,LicenseCopy,PaymentProof,Signature,BorderPointInspection,CROP_IMAGE, IMPORT_APP, BREEDER_SEED,SeedCertificationServices,VARIETY_INCLUSION,farmer,FARM_INSPECTION_PHOTO,FARM_INSPECTION_SIGN
	    	,SPRAY_FIELD_MANAGEMENT
	 }
	    
	    public static enum fileType{
	    	TEXT,IMAGE,AUDIO,VIDEO,PDF
	    }
	private Long id;
	
	private String Name;
	private byte[] content;
	   private Integer type;
	    private Integer fileType;
	    private File docFile;
	    private String docFileFileName;
	    private String docFileContentType;
	    private String refCode;
	    private Long revisionNo;
	    private String createdUser;
		private Date createdDate;
		private String updatedUser;
		private Date updatedDate;
		private String ipAddr;
		private String latitude;
		private String longitude;
		
	public DocumentUpload() {
	}

	public DocumentUpload( String Name, byte[] content) {
		
		this.Name = Name;
		this.content = content;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "ID", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	

	

	@Column(name = "DOC_NAME")
	public String getName() {
		return this.Name;
	}

	public void setName(String Name) {
		this.Name = Name;
	}

	@Column(name = "FILE")
	public byte[] getContent() {
		return this.content;
	}

	public void setContent(byte[] content) {
		this.content = content;
	}
	@Column(name = "TYPE")
	public Integer getType() {
		return type;
	}

	public void setType(Integer type) {
		this.type = type;
	}
	@Column(name = "FILE_TYPE")
	public Integer getFileType() {
		return fileType;
	}

	public void setFileType(Integer fileType) {
		this.fileType = fileType;
	}
	@Transient
	public File getDocFile() {
		return docFile;
	}

	public void setDocFile(File docFile) {
		this.docFile = docFile;
	}
	@Transient
	public String getDocFileFileName() {
		return docFileFileName;
	}

	public void setDocFileFileName(String docFileFileName) {
		this.docFileFileName = docFileFileName;
	}
	@Column(name = "DOC_EXT")
	public String getDocFileContentType() {
		return docFileContentType;
	}

	public void setDocFileContentType(String docFileContentType) {
		this.docFileContentType = docFileContentType;
	}
	@Column(name = "REFERNCE")
	public String getRefCode() {
		return refCode;
	}

	public void setRefCode(String refCode) {
		this.refCode = refCode;
	}
	@Column(name = "REVISION_NO")
	public Long getRevisionNo() {
		return revisionNo;
	}

	public void setRevisionNo(Long revisionNo) {
		this.revisionNo = revisionNo;
	}
	
	@Column(name = "CREATED_USER", length = 50, columnDefinition = "VARCHAR(255)")
	public String getCreatedUser() {
		return createdUser;
	}

	public void setCreatedUser(String createdUser) {
		this.createdUser = createdUser;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CREATED_DATE",  length = 19)
	@CreationTimestamp
	public Date getCreatedDate() {
		return createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	@Column(name = "UPDATED_USER", length = 50, columnDefinition = "VARCHAR(255)")
	public String getUpdatedUser() {
		return updatedUser;
	}

	public void setUpdatedUser(String updatedUser) {
		this.updatedUser = updatedUser;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "UPDATED_DATE",  length = 19)
	@UpdateTimestamp
	public Date getUpdatedDate() {
		return updatedDate;
	}

	public void setUpdatedDate(Date updatedDate) {
		this.updatedDate = updatedDate;
	}

	@Column(name = "IP_ADDR", length = 50, columnDefinition = "VARCHAR(255)")
	public String getIpAddr() {
		return ipAddr;
	}

	public void setIpAddr(String ipAddr) {
		this.ipAddr = ipAddr;
	}

	@Column(name = "LAT", length = 50, columnDefinition = "VARCHAR(255)")
	public String getLatitude() {
		return latitude;
	}

	public void setLatitude(String latitude) {
		this.latitude = latitude;
	}

	@Column(name = "LON", length = 50, columnDefinition = "VARCHAR(255)")
	public String getLongitude() {
		return longitude;
	}

	public void setLongitude(String longitude) {
		this.longitude = longitude;
	}
	
	

	

}
