package com.sourcetrace.eses.entity;
// Generated 23 Jun, 2020 5:09:17 PM by Hibernate Tools 5.0.6.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * DynamicFieldReportConfig generated by hbm2java
 */
@Entity
@Table(name = "DYNAMIC_FIELD_REPORT_CONFIG")
public class DynamicFieldReportConfig implements java.io.Serializable {

	private Long id;
	private String entity;
	private String txnType;
	private String label;
	private String field;
	private String sumpProp;
	private String groupProp;
	private String orderz;
	private String gridAvailable;
	private String exportAvailable;

	public DynamicFieldReportConfig() {
	}

	public DynamicFieldReportConfig(String entity, String txnType, String label, String field, String sumpProp,
			String groupProp, String orderz, String gridAvailable, String exportAvailable) {
		this.entity = entity;
		this.txnType = txnType;
		this.label = label;
		this.field = field;
		this.sumpProp = sumpProp;
		this.groupProp = groupProp;
		this.orderz = orderz;
		this.gridAvailable = gridAvailable;
		this.exportAvailable = exportAvailable;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "ID", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@Column(name = "ENTITY", length = 45)
	public String getEntity() {
		return this.entity;
	}

	public void setEntity(String entity) {
		this.entity = entity;
	}

	@Column(name = "TXN_TYPE", length = 45)
	public String getTxnType() {
		return this.txnType;
	}

	public void setTxnType(String txnType) {
		this.txnType = txnType;
	}

	@Column(name = "LABEL")
	public String getLabel() {
		return this.label;
	}

	public void setLabel(String label) {
		this.label = label;
	}

	@Column(name = "NAME", length = 45)
	public String getField() {
		return this.field;
	}

	public void setField(String field) {
		this.field = field;
	}

	@Column(name = "IS_SUM_PROP", length = 45)
	public String getIsSumpProp() {
		return this.sumpProp;
	}

	public void setIsSumpProp(String sumpProp) {
		this.sumpProp = sumpProp;
	}

	@Column(name = "IS_GROUP_PROP", length = 45)
	public String getIsGroupProp() {
		return this.groupProp;
	}

	public void setIsGroupProp(String groupProp) {
		this.groupProp = groupProp;
	}

	@Column(name = "ORDERZ", length = 45)
	public String getOrderz() {
		return this.orderz;
	}

	public void setOrderz(String orderz) {
		this.orderz = orderz;
	}

	@Column(name = "IS_GRID_AVAILABLE", length = 45)
	public String getGridAvailable() {
		return this.gridAvailable;
	}

	public void setGridAvailable(String gridAvailable) {
		this.gridAvailable = gridAvailable;
	}

	@Column(name = "IS_EXPORT_AVAILABLE", length = 45)
	public String getExportAvailable() {
		return this.exportAvailable;
	}

	public void setExportAvailable(String exportAvailable) {
		this.exportAvailable = exportAvailable;
	}

}
