package com.sourcetrace.eses.entity;
// Generated 23 Jun, 2020 5:09:17 PM by Hibernate Tools 5.0.6.Final

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * DynamicMenuSectionMap generated by hbm2java
 */
@Entity
@Table(name = "DYNAMIC_MENU_SECTION_MAP")
public class DynamicMenuSectionMap implements java.io.Serializable {

	private Long id;
	private DynamicFeildMenuConfig menu;
	private DynamicSectionConfig section;
	private Long order;
	private String branchId;
	private String MBeforeInsert;
	private String MAfterInsert;
	private String beforeInsert;
	private String afterInsert;

	public DynamicMenuSectionMap() {
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "ID", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "MENU_ID",  insertable = false, updatable = false)
	public DynamicFeildMenuConfig getMenu() {
		return this.menu;
	}

	public void setMenu(DynamicFeildMenuConfig dynamicMenuConfig) {
		this.menu = dynamicMenuConfig;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "SECTION_ID",  insertable = false, updatable = false)
	public DynamicSectionConfig getSection() {
		return this.section;
	}

	public void setSection(DynamicSectionConfig dynamicSectionConfig) {
		this.section = dynamicSectionConfig;
	}

	@Column(name = "ORDERZ")
	public Long getOrder() {
		return this.order;
	}

	public void setOrder(Long orderz) {
		this.order = orderz;
	}

	@Column(name = "BRANCH")
	public String getBranchId() {
		return this.branchId;
	}

	public void setBranchId(String branchId) {
		this.branchId = branchId;
	}

	@Column(name = "M_BEFORE_INSERT", length = 100)
	public String getMBeforeInsert() {
		return this.MBeforeInsert;
	}

	public void setMBeforeInsert(String MBeforeInsert) {
		this.MBeforeInsert = MBeforeInsert;
	}

	@Column(name = "M_AFTER_INSERT", length = 100)
	public String getMAfterInsert() {
		return this.MAfterInsert;
	}

	public void setMAfterInsert(String MAfterInsert) {
		this.MAfterInsert = MAfterInsert;
	}

	@Column(name = "BEFORE_INSERT", length = 100)
	public String getBeforeInsert() {
		return this.beforeInsert;
	}

	public void setBeforeInsert(String beforeInsert) {
		this.beforeInsert = beforeInsert;
	}

	@Column(name = "AFTER_INSERT", length = 100)
	public String getAfterInsert() {
		return this.afterInsert;
	}

	public void setAfterInsert(String afterInsert) {
		this.afterInsert = afterInsert;
	}

}
