package com.sourcetrace.eses.entity;
// Generated 23 Jun, 2020 5:09:17 PM by Hibernate Tools 5.0.6.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * DynamicReportFieldsConfig generated by hbm2java
 */
@Entity
@Table(name = "DYNAMIC_REPORT_FIELDS_CONFIG")
public class DynamicReportFieldsConfig implements java.io.Serializable {

	private Integer id;
	private String field;
	private String label;
	private String dataType;
	private String isGroupByField;
	private DynamicReportTableConfig dynamicReportTable;
	private String filterAlias;

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "field", length = 500)
	public String getField() {
		return this.field;
	}

	public void setField(String field) {
		this.field = field;
	}

	@Column(name = "label")
	public String getLabel() {
		return this.label;
	}

	public void setLabel(String label) {
		this.label = label;
	}

	@Column(name = "dataType")
	public String getDataType() {
		return this.dataType;
	}

	public void setDataType(String dataType) {
		this.dataType = dataType;
	}

	@Column(name = "Is_GroupByField")
	public String getIsGroupByField() {
		return this.isGroupByField;
	}

	public void setIsGroupByField(String isGroupByField) {
		this.isGroupByField = isGroupByField;
	}

	@ManyToOne()
	@JoinColumn(name = "entity")
	public DynamicReportTableConfig getDynamicReportTable() {
		return this.dynamicReportTable;
	}

	public void setDynamicReportTable(DynamicReportTableConfig dynamicReportTable) {
		this.dynamicReportTable = dynamicReportTable;
	}

	@Column(name = "filter_alias")
	public String getFilterAlias() {
		return this.filterAlias;
	}

	public void setFilterAlias(String filterAlias) {
		this.filterAlias = filterAlias;
	}

}
