package com.sourcetrace.eses.entity;
// Generated 23 Jun, 2020 5:09:17 PM by Hibernate Tools 5.0.6.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * EseCard generated by hbm2java
 */
@Entity
 @Table(name = "ESE_CARD", uniqueConstraints = @UniqueConstraint(columnNames = "CARD_ID"))
public class ESECard implements java.io.Serializable {

	public static final int INACTIVE = 0;
	public static final int ACTIVE = 1;
	public static final int BLOCKED = 2;

	public static final int AGENT_CARD = 0;
	public static final int CLIENT_CARD = 1;
	public static final int SHOP_DEALER_CARD=1;
	public static final int FARMER_CARD=2;

	public static final String OPERATOR_CARD = "OC";
	public static final String CUSTOMER_CARD = "CC";

	public static final int IS_REWRITABLE_NO = 0;
	public static final int IS_REWRITABLE_YES = 1;
	
	private Long id;
	private String cardId;
	private String cardType;
	private Integer type;
	private Date issueDate;
	private Integer status;
	private Date updateTime;
	private Date createTime;
	private String profileId;
	private Integer cardRewritable;


	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "ID", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@Column(name = "CARD_ID", unique = true, length = 45)
	public String getCardId() {
		return this.cardId;
	}

	public void setCardId(String cardId) {
		this.cardId = cardId;
	}

	@Column(name = "CARD_TYPE", length = 45)
	public String getCardType() {
		return this.cardType;
	}

	public void setCardType(String cardType) {
		this.cardType = cardType;
	}

	@Column(name = "TYPEE")
	public Integer getType() {
		return this.type;
	}

	public void setType(Integer type) {
		this.type = type;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "ISSUE_DATE", length = 10)
	public Date getIssueDate() {
		return this.issueDate;
	}

	public void setIssueDate(Date issueDate) {
		this.issueDate = issueDate;
	}

	@Column(name = "STATUS")
	public Integer getStatus() {
		return this.status;
	}

	public void setStatus(Integer status) {
		this.status = status;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "MOD_TIME",  length = 19)
	public Date getUpdateTime() {
		return this.updateTime;
	}

	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CRE_TIME",  length = 19)
	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	@Column(name = "PROFILE_ID", length = 45)
	public String getProfileId() {
		return this.profileId;
	}

	public void setProfileId(String profileId) {
		this.profileId = profileId;
	}

	@Column(name = "CARD_REWRITABLE")
	public Integer getCardRewritable() {
		return this.cardRewritable;
	}

	public void setCardRewritable(Integer cardRewritable) {
		this.cardRewritable = cardRewritable;
	}

}
