package com.sourcetrace.eses.entity;
// Generated 23 Jun, 2020 5:09:17 PM by Hibernate Tools 5.0.6.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * EseTxnType generated by hbm2java
 */
@Entity
@Table(name = "ese_txn_type")
public class ESETxnType implements java.io.Serializable {

	private Long id;
	private String code;
	private String name;
	private Set<ESETxnHeader> eseTxnHeaders = new HashSet<ESETxnHeader>(0);

	

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "ID", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@Column(name = "CODE",  length = 45)
	public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	@Column(name = "NAME", length = 45)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@OneToMany( mappedBy = "eseTxnType")
	public Set<ESETxnHeader> getEseTxnHeaders() {
		return this.eseTxnHeaders;
	}

	public void setEseTxnHeaders(Set<ESETxnHeader> eseTxnHeaders) {
		this.eseTxnHeaders = eseTxnHeaders;
	}

}
