package com.sourcetrace.eses.entity;
// Generated 23 Jun, 2020 5:09:17 PM by Hibernate Tools 5.0.6.Final

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import java.util.SortedSet;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.annotations.OrderBy;


/**
 * FarmerDynamicFieldValue generated by hbm2java
 */
@Entity
 @Table(name = "farmer_dynamic_field_value")
public class FarmerDynamicFieldsValue implements java.io.Serializable {

	private Long id;
	private String fieldName;
	private String fieldValue;
	private Long farmerId;
	private String componentType;
	private Integer typez;
	private String referenceId;
	private String txnType;
	private Date createdDate;
	private String createdUser;
	private Long txnUniqueId;
	private FarmerDynamicData farmerDynamicData;
	private String validationType;
	private Integer accessType;
	private String catalogueType;
	private Long parentId;
	private String profileField;
	private Long isProfileUpdate;
	private Integer score;
	private Double percentage;
	private FarmerDynamicFieldsValue followUpParent;
	private FarmerDynamicFieldsValue actionPlan;
	private String recom;
	private Long actStatus;
	private Long followUp;
	private String parentActionField;
	private String parentActionKey;
	private String grade;
	private Long orderz;
	private String imageIds;
	private String listMethod;
	private String isMobileAvail;
	private String parentActField;
	private String parentActKey;
	private String isUpdateProfile;
	private FarmerDynamicFieldsValue deadline;
	private Set<DynamicImageData> dymamicImageData;
	
	private SortedSet<FarmerDynamicFieldsValue> followUps;
	
	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "ID", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public String getIsMobileAvail() {
		return isMobileAvail;
	}

	public void setIsMobileAvail(String isMobileAvail) {
		this.isMobileAvail = isMobileAvail;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@Column(name = "FIELD_NAME")
	public String getFieldName() {
		return this.fieldName;
	}

	public void setFieldName(String fieldName) {
		this.fieldName = fieldName;
	}

	@Column(name = "FIELD_VALUE", columnDefinition="LONGTEXT")
	public String getFieldValue() {
		return this.fieldValue;
	}

	public void setFieldValue(String fieldValue) {
		this.fieldValue = fieldValue;
	}

	@Column(name = "FARMER_ID")
	public Long getFarmerId() {
		return this.farmerId;
	}

	public void setFarmerId(Long farmerId) {
		this.farmerId = farmerId;
	}

	@Column(name = "COMPONENT_TYPE", length = 45)
	public String getComponentType() {
		return this.componentType;
	}

	public void setComponentType(String componentType) {
		this.componentType = componentType;
	}

	@Column(name = "TYPEZ", length = 45)
	public Integer getTypez() {
		return this.typez;
	}

	public void setTypez(Integer typez) {
		this.typez = typez;
	}

	@Column(name = "REFERENCE_ID", length = 45)
	public String getReferenceId() {
		return this.referenceId;
	}

	public void setReferenceId(String referenceId) {
		this.referenceId = referenceId;
	}

	@Column(name = "TXN_TYPE", length = 45)
	public String getTxnType() {
		return this.txnType;
	}

	public void setTxnType(String txnType) {
		this.txnType = txnType;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CREATED_DATE", length = 19)
	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	@Column(name = "CREATED_USER", length = 100)
	public String getCreatedUser() {
		return this.createdUser;
	}

	public void setCreatedUser(String createdUser) {
		this.createdUser = createdUser;
	}

	@Column(name = "TXN_UNIQUE_ID")
	public Long getTxnUniqueId() {
		return this.txnUniqueId;
	}

	public void setTxnUniqueId(Long txnUniqueId) {
		this.txnUniqueId = txnUniqueId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "FARMER_DYNAMIC_DATA_ID")
	public FarmerDynamicData getFarmerDynamicData() {
		return this.farmerDynamicData;
	}

	public void setFarmerDynamicData(FarmerDynamicData farmerDynamicDataId) {
		this.farmerDynamicData = farmerDynamicDataId;
	}

	@Column(name = "VALIDATION_TYPE", length = 20)
	public String getValidationType() {
		return this.validationType;
	}

	public void setValidationType(String validationType) {
		this.validationType = validationType;
	}



	@Column(name = "ACCESS_TYPE")
	public Integer getAccessType() {
		return this.accessType;
	}

	public void setAccessType(Integer accessType) {
		this.accessType = accessType;
	}

	@Column(name = "CATALOGUE_TYPE", length = 45)
	public String getCatalogueType() {
		return this.catalogueType;
	}

	public void setCatalogueType(String catalogueType) {
		this.catalogueType = catalogueType;
	}

	@Column(name = "PARENT_ID")
	public Long getParentId() {
		return this.parentId;
	}

	public void setParentId(Long parentId) {
		this.parentId = parentId;
	}

	@Column(name = "PROFILE_FIELD", length = 250)
	public String getProfileField() {
		return this.profileField;
	}

	public void setProfileField(String profileField) {
		this.profileField = profileField;
	}

	@Column(name = "IS_PROFILE_UPDATE")
	public Long getIsProfileUpdate() {
		return this.isProfileUpdate;
	}

	public void setIsProfileUpdate(Long isProfileUpdate) {
		this.isProfileUpdate = isProfileUpdate;
	}

	@Column(name = "SCORE")
	public Integer getScore() {
		return this.score;
	}

	public void setScore(Integer score) {
		this.score = score;
	}

	@Column(name = "PERCENTAGE", precision = 45)
	public Double getPercentage() {
		return this.percentage;
	}

	public void setPercentage(Double percentage) {
		this.percentage = percentage;
	}


	@ManyToOne(cascade=CascadeType.ALL, fetch = FetchType.LAZY)
	@JoinColumn(name = "FDV_ID")	
	public FarmerDynamicFieldsValue getFollowUpParent() {
		return followUpParent;
	}

	public void setFollowUpParent(FarmerDynamicFieldsValue followUpParent) {
		this.followUpParent = followUpParent;
	}

	@ManyToOne(cascade=CascadeType.ALL, fetch = FetchType.LAZY)
	@JoinColumn(name = "ACTION_PLAN")	
	public FarmerDynamicFieldsValue getActionPlan() {
		return this.actionPlan;
	}

	public void setActionPlan(FarmerDynamicFieldsValue actionPlan) {
		this.actionPlan = actionPlan;
	}

	/*@Column(name = "deadline")
	public Long getDeadline() {
		return this.deadline;
	}

	public void setDeadline(Long deadline) {
		this.deadline = deadline;
	}*/

	@Column(name = "RECOM", length = 250)
	public String getRecom() {
		return this.recom;
	}

	public void setRecom(String recom) {
		this.recom = recom;
	}

	@Column(name = "ACT_STATUS")
	public Long getActStatus() {
		return this.actStatus;
	}

	public void setActStatus(Long actStatus) {
		this.actStatus = actStatus;
	}

	@Column(name = "FOLLOW_UP")
	public Long getFollowUp() {
		return this.followUp;
	}

	public void setFollowUp(Long followUp) {
		this.followUp = followUp;
	}

	@Column(name = "PARENT_ACTION_FIELD", length = 50)
	public String getParentActionField() {
		return this.parentActionField;
	}

	public void setParentActionField(String parentActionField) {
		this.parentActionField = parentActionField;
	}

	@Column(name = "PARENT_ACTION_KEY", length = 50)
	public String getParentActionKey() {
		return this.parentActionKey;
	}

	public void setParentActionKey(String parentActionKey) {
		this.parentActionKey = parentActionKey;
	}

	@Column(name = "GRADE", length = 10)
	public String getGrade() {
		return this.grade;
	}

	public void setGrade(String grade) {
		this.grade = grade;
	}

	@Column(name = "orderz")
	public Long getOrderz() {
		return this.orderz;
	}

	public void setOrderz(Long orderz) {
		this.orderz = orderz;
	}

	
	@OneToMany(cascade = CascadeType.ALL)
	@JoinColumn(name = "FDV_ID")
	@OrderBy(clause="ORDERZ")
	public SortedSet<FarmerDynamicFieldsValue> getFollowUps() {
		return followUps;
	}

	public void setFollowUps(SortedSet<FarmerDynamicFieldsValue> followUps) {
		this.followUps = followUps;
	}

	public String getImageIds() {
		return imageIds;
	}

	public void setImageIds(String imageIds) {
		this.imageIds = imageIds;
	}
	public String getListMethod() {
		return listMethod;
	}

	public void setListMethod(String listMethod) {
		this.listMethod = listMethod;
	}
	@OneToMany( mappedBy = "farmerDynamicFieldValue")
	public Set<DynamicImageData> getDymamicImageData() {
		return dymamicImageData;
	}

	public void setDymamicImageData(Set<DynamicImageData> dymamicImageData) {
		this.dymamicImageData = dymamicImageData;
	}

	public String getParentActField() {
		return parentActField;
	}

	public void setParentActField(String parentActField) {
		this.parentActField = parentActField;
	}

	public String getParentActKey() {
		return parentActKey;
	}

	public void setParentActKey(String parentActKey) {
		this.parentActKey = parentActKey;
	}
	public String getIsUpdateProfile() {
		return isUpdateProfile;
	}

	public void setIsUpdateProfile(String isUpdateProfile) {
		this.isUpdateProfile = isUpdateProfile;
	}

	public FarmerDynamicFieldsValue getDeadline() {
		return deadline;
	}

	public void setDeadline(FarmerDynamicFieldsValue deadline) {
		this.deadline = deadline;
	}

		
}
