package com.sourcetrace.eses.entity;
// Generated 23 Jun, 2020 5:09:17 PM by Hibernate Tools 5.0.6.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.CascadeType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * ImageInfo generated by hbm2java
 */
@Entity
@org.hibernate.annotations.Filter(name = "branchFilter", condition = "branch_id in ( :branchIdParam )")
@Table(name = "image_info")
public class ImageInfo implements java.io.Serializable {

	private Long id;
	private Image photo;
	private Image biometric;
	private Long rev;

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "ID", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@Column(name = "REV")
	public Long getRev() {
		return this.rev;
	}

	@ManyToOne(fetch = FetchType.LAZY,cascade = CascadeType.ALL)
	@JoinColumn(name = "PHOTO")
	public Image getPhoto() {
		return photo;
	}

	public void setPhoto(Image photo) {
		this.photo = photo;
	}

	@ManyToOne(fetch = FetchType.LAZY,cascade = CascadeType.ALL)
	@JoinColumn(name = "BIOMETRIC")
	public Image getBiometric() {
		return biometric;
	}

	public void setBiometric(Image biometric) {
		this.biometric = biometric;
	}

	public void setRev(Long rev) {
		this.rev = rev;
	}

}
