package com.sourcetrace.eses.entity;
// Generated 23 Jun, 2020 5:09:17 PM by Hibernate Tools 5.0.6.Final

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.EnumType;
import javax.persistence.Enumerated;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * License generated by hbm2java
 */
@Entity
@Table(name = "license")
public class License implements java.io.Serializable {

	private Long id;
	private String licKey;
	private String owner;
	private String client;
	private LicenseType type;
	private String ver;
	private Date start;
	private Date end;

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "ID", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@Column(name = "LIC_KEY",  columnDefinition="LONGTEXT")
	public String getLicKey() {
		return this.licKey;
	}

	public void setLicKey(String licKey) {
		this.licKey = licKey;
	}

	@Column(name = "OWNER", nullable = false)
	public String getOwner() {
		return this.owner;
	}

	public void setOwner(String owner) {
		this.owner = owner;
	}

	@Column(name = "CLIENT", nullable = false)
	public String getClient() {
		return this.client;
	}

	public void setClient(String client) {
		this.client = client;
	}
	@Column(name = "LIC_TYPE", nullable = false)
	@Enumerated(EnumType.STRING)
	public LicenseType geType() {
		return this.type;
	}

	public void setLicType(LicenseType type) {
		this.type = type;
	}

	@Column(name = "VER",  length = 25)
	public String getVer() {
		return this.ver;
	}

	public void setVer(String ver) {
		this.ver = ver;
	}

	
	 /**
     * Gets the start.
     * @return the start
     */
	@Temporal(TemporalType.DATE)
	@Column(name = "VALID_FROM",  length = 10)
	
    public Date getStart() {

        return start;
    }

    /**
     * Sets the start.
     * @param start the new start
     */
    public void setStart(Date start) {

        this.start = start;
    }

    /**
     * Gets the end.
     * @return the end
     */
    @Temporal(TemporalType.DATE)
	@Column(name = "VALID_TILL",  length = 10)

    public Date getEnd() {

        return end;
    }

    /**
     * Sets the end.
     * @param end the new end
     */
    public void setEnd(Date end) {

        this.end = end;
    }
}
