package com.sourcetrace.eses.entity;
// Generated 23 Jun, 2020 5:09:17 PM by Hibernate Tools 5.0.6.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * LocaleProperty generated by hbm2java
 */
@Entity
@Table(name = "locale_property")
public class LocaleProperty implements java.io.Serializable {

	private Long id;
	private String code;
	private String langCode;
	private String langValue;

	public LocaleProperty() {
	}

	public LocaleProperty(String code, String langCode, String langValue) {
		this.code = code;
		this.langCode = langCode;
		this.langValue = langValue;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@Column(name = "code",  length = 50)
	public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	@Column(name = "lang_code",  length = 20)
	public String getLangCode() {
		return this.langCode;
	}

	public void setLangCode(String langCode) {
		this.langCode = langCode;
	}

	@Column(name = "lang_value",  length = 500)
	public String getLangValue() {
		return this.langValue;
	}

	public void setLangValue(String langValue) {
		this.langValue = langValue;
	}

}
