package com.sourcetrace.eses.entity;
// Generated 23 Jun, 2020 5:09:17 PM by Hibernate Tools 5.0.6.Final

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import lombok.Data;

/**
 * Product generated by hbm2java
 */
@Entity
@Table(name = "product")
@Data
public class Product implements java.io.Serializable {
	
	public static final int LIST_UNIT_BASED_ON_UOM = 10;


	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "ID", unique = true, nullable = false)
	private Long id;

	@ManyToOne(fetch = FetchType.EAGER, cascade = { CascadeType.PERSIST, CascadeType.MERGE })
	@JoinColumn(name = "SUB_CATEGORY_ID")
	private SubCategory subCategory;

	@Column(name = "NAME",  length = 50,columnDefinition="VARCHAR(255)")
	private String name;

	@Column(name = "CODE",  length = 20,columnDefinition="VARCHAR(255)")
	private String code;

	@Column(name = "UNIT", length = 15,columnDefinition="VARCHAR(255)")
	private String unit;

	@Column(name = "PRICE",columnDefinition="VARCHAR(255)")
	private String price;
	
	@Column(name = "REVISION_NO")
	private Long revisionNo;

	@Column(name = "TYPE")
	private Long type;

	@Column(name = "MANUFACTURE",columnDefinition="VARCHAR(255)")
	private String manufacture;

	@Column(name = "INGREDIENT",columnDefinition="VARCHAR(255)")
	private String ingredient;

}
