package com.sourcetrace.eses.entity;
// Generated 23 Jun, 2020 5:09:17 PM by Hibernate Tools 5.0.6.Final

import static javax.persistence.GenerationType.IDENTITY;

import java.util.HashSet;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import org.hibernate.annotations.FilterDef;
import org.hibernate.annotations.Filters;
import org.hibernate.annotations.ParamDef;

import com.fasterxml.jackson.annotation.JsonIgnore;

import lombok.Data;

/**
 * SubCategory generated by hbm2java
 */
@Entity
 @FilterDef(name = "branchFilter", parameters = @ParamDef(name = "branchIdParam", type = "string"))@Filters(@org.hibernate.annotations.Filter(name="branchFilter", condition="branch_id in ( :branchIdParam )"))
@Table(name = "sub_category")
@Data
public class SubCategory implements java.io.Serializable {

	
	
	
	
	public SubCategory() {
	}

	public SubCategory(String code, String name) {
		this.code = code;
		this.name = name;
	}


	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "ID", unique = true, nullable = false,columnDefinition="BIGINT(45)")
	private Long id;

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CATEGORY_ID")
	
	private Category category;
	@Column(name = "CODE",  length = 20,columnDefinition="VARCHAR(255)")
	private String code;

	@Column(name = "NAME",  length = 50,columnDefinition="VARCHAR(255)")
	
	private String name;
	@Column(name = "BRANCH_ID", length = 50,columnDefinition="VARCHAR(255)")
	private String branchId;

	@OneToMany( mappedBy = "subCategory",fetch=FetchType.LAZY, cascade = CascadeType.ALL)
	@JsonIgnore
	private Set<Product> products = new HashSet<Product>(0);
	@Override
	public String toString() {
		return "SubCategory{" +
				"id=" + id +
				", category=" + category +
				", code='" + code + '\'' +
				", name='" + name + '\'' +
				", branchId='" + branchId + '\'' +
				", products=" + products +
				'}';
	}
}
