package com.sourcetrace.eses.entity;
// Generated 24 Jun, 2020 6:21:14 PM by Hibernate Tools 5.0.6.Final

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.annotations.FilterDef;
import org.hibernate.annotations.Filters;
import org.hibernate.annotations.ParamDef;

/**
 * Txn generated by hbm2java
 */
@Entity
 @FilterDef(name = "branchFilter", parameters = @ParamDef(name = "branchIdParam", type = "string"))@Filters(@org.hibernate.annotations.Filter(name="branchFilter", condition="branch_id in ( :branchIdParam )"))
@Table(name = "txn")
public class Transaction implements java.io.Serializable {

	
	public enum Status {
		SUCCESS, FAILED, PENDING
	};

	public static final String OPERATIONTYPE_REGULAR = "01";
	public static final String OPERATIONTYPE_VOID = "02";

	public static final String MODE_ONLINE = "01";
	public static final String MODE_OFFLINE = "02";

	public static final int BOD = 1;
	public static final int EOD = 0;

	public static final String SUCCESS = "00";
	public static final String FAILED = "01";
	public static final String PENDING = "02";

	public static final String SUCCESS_MSG = "SUCCESS";
	public static final String FAILED_MSG = "FAILED";
	public static final String PENDING_MSG = "PENDING";

	
	private Long id;
	private Date txnTime;
	private String txnType;
	private String txnCode;
	private Integer operType;
	private Integer mode;
	private long resentCount;
	private long msgNo;
	private long batchNo;
	private String statusCode;
	private String statusMsg;
	private TransactionHeader header;
	private String branchId;
	private String tenantId;
	

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "ID", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "TXN_TIME", length = 19)
	public Date getTxnTime() {
		return this.txnTime;
	}

	public void setTxnTime(Date txnTime) {
		this.txnTime = txnTime;
	}

	@Column(name = "TXN_TYPE", length = 45)
	public String getTxnType() {
		return this.txnType;
	}

	public void setTxnType(String txnType) {
		this.txnType = txnType;
	}

	@Column(name = "TXN_CODE", length = 45)
	public String getTxnCode() {
		return this.txnCode;
	}

	public void setTxnCode(String txnCode) {
		this.txnCode = txnCode;
	}

	@Column(name = "OPER_TYPE", nullable = false)
	public Integer getOperType() {
		return this.operType;
	}

	public void setOperType(Integer operType) {
		this.operType = operType;
	}

	@Column(name = "MODE", nullable = false)
	public Integer getMode() {
		return this.mode;
	}

	public void setMode(Integer mode) {
		this.mode = mode;
	}

	@Column(name = "RESENT_COUNT", nullable = false)
	public long getResentCount() {
		return this.resentCount;
	}

	public void setResentCount(long resentCount) {
		this.resentCount = resentCount;
	}

	@Column(name = "MSG_NO", nullable = false)
	public long getMsgNo() {
		return this.msgNo;
	}

	public void setMsgNo(long msgNo) {
		this.msgNo = msgNo;
	}

	@Column(name = "BATCH_NO", nullable = false)
	public long getBatchNo() {
		return this.batchNo;
	}

	public void setBatchNo(long batchNo) {
		this.batchNo = batchNo;
	}

	@Column(name = "STATUS_CODE", nullable = false)
	public String getStatusCode() {
		return this.statusCode;
	}

	public void setStatusCode(String statusCode) {
		this.statusCode = statusCode;
	}

	@Column(name = "STATUS_MSG")
	public String getStatusMsg() {
		return this.statusMsg;
	}

	public void setStatusMsg(String statusMsg) {
		this.statusMsg = statusMsg;
	}
	
	@ManyToOne
	@JoinColumn(name = "TXN_HEADER_ID")
	public TransactionHeader getHeader() {
		return header;
	}

	public void setHeader(TransactionHeader header) {
		this.header = header;
	}

	@Column(name = "BRANCH_ID", length = 50)
	public String getBranchId() {
		return this.branchId;
	}

	public void setBranchId(String branchId) {
		this.branchId = branchId;
	}

	@Column(name = "TENANT_ID", length = 20)
	public String getTenantId() {
		return this.tenantId;
	}

	public void setTenantId(String tenantId) {
		this.tenantId = tenantId;
	}

	
}
