package com.sourcetrace.eses.entity;
// Generated 24 Jun, 2020 6:21:14 PM by Hibernate Tools 5.0.6.Final

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;

import org.hibernate.annotations.FilterDef;
import org.hibernate.annotations.Filters;
import org.hibernate.annotations.ParamDef;

/**
 * TxnReqResLog generated by hbm2java
 */
@Entity
@Table(name = "txn_req_res_log")
public class TxnReqResLog implements java.io.Serializable {

	private Long id;
	private byte[] req;
	private byte[] res;
	private String code;
	private String msg;
	private Integer status;
	private String txnCode;

	public TxnReqResLog() {
	}

	public TxnReqResLog(byte[] req, byte[] res, String code, String msg, Integer status, String txnCode) {
		this.req = req;
		this.res = res;
		this.code = code;
		this.msg = msg;
		this.status = status;
		this.txnCode = txnCode;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "ID", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@Column(name = "REQ")
	public byte[] getReq() {
		return this.req;
	}

	public void setReq(byte[] req) {
		this.req = req;
	}

	@Column(name = "RES")
	public byte[] getRes() {
		return this.res;
	}

	public void setRes(byte[] res) {
		this.res = res;
	}

	@Column(name = "CODE", length = 45)
	public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	@Column(name = "MSG")
	public String getMsg() {
		return this.msg;
	}

	public void setMsg(String msg) {
		this.msg = msg;
	}

	@Column(name = "STATUS")
	public Integer getStatus() {
		return this.status;
	}

	public void setStatus(Integer status) {
		this.status = status;
	}

	@Column(name = "TXN_CODE", length = 45)
	public String getTxnCode() {
		return this.txnCode;
	}

	public void setTxnCode(String txnCode) {
		this.txnCode = txnCode;
	}

}
