package com.sourcetrace.eses.entity;
// Generated 24 Jun, 2020 6:21:14 PM by Hibernate Tools 5.0.6.Final

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.annotations.FilterDef;
import org.hibernate.annotations.Filters;
import org.hibernate.annotations.ParamDef;

/**
 * UptimeLog generated by hbm2java
 */
@Entity
@Table(name = "uptime_log")
public class UptimeLog implements java.io.Serializable {

	private Long id;
	private Date startup;
	private Date shutdown;
	private String module;

	public UptimeLog() {
	}
	
	public UptimeLog(String module) {

        this.module = module;
        this.startup = new Date();
    }


	public UptimeLog(Date startup, String module) {
		this.startup = startup;
		this.module = module;
	}

	public UptimeLog(Date startup, Date shutdown, String module) {
		this.startup = startup;
		this.shutdown = shutdown;
		this.module = module;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "ID", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "STARTUP",  length = 19)
	public Date getStartup() {
		return this.startup;
	}

	public void setStartup(Date startup) {
		this.startup = startup;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "SHUTDOWN", length = 19)
	public Date getShutdown() {
		return this.shutdown;
	}

	public void setShutdown(Date shutdown) {
		this.shutdown = shutdown;
	}

	@Column(name = "MODULE",  length = 45)
	public String getModule() {
		return this.module;
	}

	public void setModule(String module) {
		this.module = module;
	}

}
