package com.sourcetrace.eses.entity;
// Generated 24 Jun, 2020 6:21:14 PM by Hibernate Tools 5.0.6.Final

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;

import org.hibernate.annotations.FilterDef;
import org.hibernate.annotations.Filters;
import org.hibernate.annotations.ParamDef;

/**
 * VillageWarehouse generated by hbm2java
 */
@Entity
 @FilterDef(name = "branchFilter", parameters = @ParamDef(name = "branchIdParam", type = "string"))@Filters(@org.hibernate.annotations.Filter(name="branchFilter", condition="branch_id in ( :branchIdParam )"))
@Table(name = "village_warehouse")
public class VillageWarehouse implements java.io.Serializable {

	public static final int DELETED = 1;
    public static final int NOT_DELETED = 0;
	private Long id;
	private Long villageId;
	private Long procurementProductId;
	private Long numberOfBags;
	private Double grossWeight;
	private String agentId;
	private String quality;
	private Integer isDelete;

	public VillageWarehouse() {
	}

	public VillageWarehouse(Long villageId, Long procurementProductId, Long numberOfBags, Double grossWeight,
			String agentId, String quality, Integer isDelete) {
		this.villageId = villageId;
		this.procurementProductId = procurementProductId;
		this.numberOfBags = numberOfBags;
		this.grossWeight = grossWeight;
		this.agentId = agentId;
		this.quality = quality;
		this.isDelete = isDelete;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "ID", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@Column(name = "VILLAGE_ID")
	public Long getVillageId() {
		return this.villageId;
	}

	public void setVillageId(Long villageId) {
		this.villageId = villageId;
	}

	@Column(name = "PROCUREMENT_PRODUCT_ID")
	public Long getProcurementProductId() {
		return this.procurementProductId;
	}

	public void setProcurementProductId(Long procurementProductId) {
		this.procurementProductId = procurementProductId;
	}

	@Column(name = "NUMBER_OF_BAGS")
	public Long getNumberOfBags() {
		return this.numberOfBags;
	}

	public void setNumberOfBags(Long numberOfBags) {
		this.numberOfBags = numberOfBags;
	}

	@Column(name = "GROSS_WEIGHT", precision = 22, scale = 0)
	public Double getGrossWeight() {
		return this.grossWeight;
	}

	public void setGrossWeight(Double grossWeight) {
		this.grossWeight = grossWeight;
	}

	@Column(name = "AGENT_ID", length = 45)
	public String getAgentId() {
		return this.agentId;
	}

	public void setAgentId(String agentId) {
		this.agentId = agentId;
	}

	@Column(name = "QUALITY", length = 45)
	public String getQuality() {
		return this.quality;
	}

	public void setQuality(String quality) {
		this.quality = quality;
	}

	@Column(name = "IS_DELETE")
	public Integer getIsDelete() {
		return this.isDelete;
	}

	public void setIsDelete(Integer isDelete) {
		this.isDelete = isDelete;
	}

}
