package com.sourcetrace.eses.entity;
// Generated 24 Jun, 2020 6:21:14 PM by Hibernate Tools 5.0.6.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.annotations.Type;

/**
 * WarehouseProductDetail generated by hbm2java
 */
@Entity

@Table(name = "warehouse_product_detail")
public class WarehouseProductDetail implements java.io.Serializable {

	private Long id;
	private String receiptNo;
	private Date txnTime;
	private String txnDesc;
	private String vendorId;
	private Double costPrice;
	private Double prevStock;
	private Double txnStock;
	private Double finalStock;
	private String damagedQty;
	private String orderNo;
	private Boolean status;
	private String userName;
	private PackhouseIncoming packhouseIncoming;
	private String parentCode;
	private String packetsInfo;
	private String seedType;
	private String uom;
	private String variety;



	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "ID", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@Column(name = "RECEIPT_NO", length = 45)
	public String getReceiptNo() {
		return this.receiptNo;
	}

	public void setReceiptNo(String receiptNo) {
		this.receiptNo = receiptNo;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "TXN_TIME", length = 19)
	public Date getTxnTime() {
		return this.txnTime;
	}

	public void setTxnTime(Date txnTime) {
		this.txnTime = txnTime;
	}

	@Column(name = "TXN_DESC")
	public String getTxnDesc() {
		return this.txnDesc;
	}

	public void setTxnDesc(String txnDesc) {
		this.txnDesc = txnDesc;
	}

	@Column(name = "VENDOR_ID", length = 8)
	public String getVendorId() {
		return this.vendorId;
	}

	public void setVendorId(String vendorId) {
		this.vendorId = vendorId;
	}

	@Column(name = "COST_PRICE", precision = 20, scale = 3)
	public Double getCostPrice() {
		return this.costPrice;
	}

	public void setCostPrice(Double costPrice) {
		this.costPrice = costPrice;
	}

	@Column(name = "PREV_STOCK", precision = 20, scale = 3)
	public Double getPrevStock() {
		return this.prevStock;
	}

	public void setPrevStock(Double prevStock) {
		this.prevStock = prevStock;
	}

	@Column(name = "TXN_STOCK", precision = 20, scale = 3)
	public Double getTxnStock() {
		return this.txnStock;
	}

	public void setTxnStock(Double txnStock) {
		this.txnStock = txnStock;
	}

	@Column(name = "FINAL_STOCK", precision = 20, scale = 3)
	public Double getFinalStock() {
		return this.finalStock;
	}

	public void setFinalStock(Double finalStock) {
		this.finalStock = finalStock;
	}

	@Column(name = "DAMAGED_QTY", length = 20)
	public String getDamagedQty() {
		return this.damagedQty;
	}

	public void setDamagedQty(String damagedQty) {
		this.damagedQty = damagedQty;
	}

	@Column(name = "ORDER_NO", length = 45)
	public String getOrderNo() {
		return this.orderNo;
	}

	public void setOrderNo(String orderNo) {
		this.orderNo = orderNo;
	}

	@Column(name = "STATUS",columnDefinition= "TINYINT")
	@Type(type = "org.hibernate.type.NumericBooleanType")
	public Boolean getStatus() {
		return this.status;
	}

	public void setStatus(Boolean status) {
		this.status = status;
	}

	@Column(name = "USER_NAME", length = 45)
	public String getUserName() {
		return this.userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "WAREHOUSE_PRODUCT_ID")
	public PackhouseIncoming getWarehouseProduct() {
		return packhouseIncoming;
	}

	public void setWarehouseProduct(PackhouseIncoming packhouseIncoming) {
		this.packhouseIncoming = packhouseIncoming;
	}

	@Column(name = "PARENT_CODE", length = 30)
	public String getParentCode() {
		return this.parentCode;
	}

	public void setParentCode(String parentCode) {
		this.parentCode = parentCode;
	}

	@Column(name = "PACKETS_INFO", length = 45)
	public String getPacketsInfo() {
		return this.packetsInfo;
	}

	public void setPacketsInfo(String packetsInfo) {
		this.packetsInfo = packetsInfo;
	}

	@Column(name = "SEED_TYPE", length = 30)
	public String getSeedType() {
		return this.seedType;
	}

	public void setSeedType(String seedType) {
		this.seedType = seedType;
	}

	@Column(name = "UOM", length = 30)
	public String getUom() {
		return this.uom;
	}

	public void setUom(String uom) {
		this.uom = uom;
	}

	@Column(name = "VARIETY", length = 30)
	public String getVariety() {
		return this.variety;
	}

	public void setVariety(String variety) {
		this.variety = variety;
	}

}
