package com.sourcetrace.eses.entity;
// Generated 24 Jun, 2020 6:21:14 PM by Hibernate Tools 5.0.6.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * WarehouseStockReturn generated by hbm2java
 */
@Entity
@Table(name = "warehouse_stock_return")
public class WarehouseStockReturn implements java.io.Serializable {

	private Long id;
	private Vendor vendor;

	private Date trxnDate;
	private String receiptNo;
	private String stockReturnType;
	private String orderNo;
	private Long totalDamagedStock;
	private Double totalAmount;
	private String paymentMode;
	private Double paymentAmount;
	private String remarks;
	private Long revisionNo;
	private String seasonCode;
	private Set<WarehouseStockReturnDetails> warehouseStockReturnDetailses = new HashSet<WarehouseStockReturnDetails>(
			0);

	public WarehouseStockReturn() {
	}

	public WarehouseStockReturn(Vendor vendor,  Date trxnDate, String receiptNo,
			String stockReturnType, String orderNo, Long totalDamagedStock, Double totalAmount, String paymentMode,
			Double paymentAmount, String remarks, Long revisionNo, String seasonCode,
			Set<WarehouseStockReturnDetails> warehouseStockReturnDetailses) {
		this.vendor = vendor;
		
		this.trxnDate = trxnDate;
		this.receiptNo = receiptNo;
		this.stockReturnType = stockReturnType;
		this.orderNo = orderNo;
		this.totalDamagedStock = totalDamagedStock;
		this.totalAmount = totalAmount;
		this.paymentMode = paymentMode;
		this.paymentAmount = paymentAmount;
		this.remarks = remarks;
		this.revisionNo = revisionNo;
		this.seasonCode = seasonCode;
		this.warehouseStockReturnDetailses = warehouseStockReturnDetailses;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "ID", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "VENDOR_ID")
	public Vendor getVendor() {
		return this.vendor;
	}

	public void setVendor(Vendor vendor) {
		this.vendor = vendor;
	}

	

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "TRXN_DATE", length = 19)
	public Date getTrxnDate() {
		return this.trxnDate;
	}

	public void setTrxnDate(Date trxnDate) {
		this.trxnDate = trxnDate;
	}

	@Column(name = "RECEIPT_NO", length = 20)
	public String getReceiptNo() {
		return this.receiptNo;
	}

	public void setReceiptNo(String receiptNo) {
		this.receiptNo = receiptNo;
	}

	@Column(name = "STOCK_RETURN_TYPE", length = 25)
	public String getStockReturnType() {
		return this.stockReturnType;
	}

	public void setStockReturnType(String stockReturnType) {
		this.stockReturnType = stockReturnType;
	}

	@Column(name = "ORDER_NO", length = 20)
	public String getOrderNo() {
		return this.orderNo;
	}

	public void setOrderNo(String orderNo) {
		this.orderNo = orderNo;
	}

	@Column(name = "TOTAL_DAMAGED_STOCK")
	public Long getTotalDamagedStock() {
		return this.totalDamagedStock;
	}

	public void setTotalDamagedStock(Long totalDamagedStock) {
		this.totalDamagedStock = totalDamagedStock;
	}

	@Column(name = "TOTAL_AMOUNT", precision = 20)
	public Double getTotalAmount() {
		return this.totalAmount;
	}

	public void setTotalAmount(Double totalAmount) {
		this.totalAmount = totalAmount;
	}

	@Column(name = "PAYMENT_MODE", length = 3)
	public String getPaymentMode() {
		return this.paymentMode;
	}

	public void setPaymentMode(String paymentMode) {
		this.paymentMode = paymentMode;
	}

	@Column(name = "PAYMENT_AMOUNT", precision = 20)
	public Double getPaymentAmount() {
		return this.paymentAmount;
	}

	public void setPaymentAmount(Double paymentAmount) {
		this.paymentAmount = paymentAmount;
	}

	@Column(name = "REMARKS", columnDefinition="LONGTEXT")
	public String getRemarks() {
		return this.remarks;
	}

	public void setRemarks(String remarks) {
		this.remarks = remarks;
	}

	@Column(name = "REVISION_NO")
	public Long getRevisionNo() {
		return this.revisionNo;
	}

	public void setRevisionNo(Long revisionNo) {
		this.revisionNo = revisionNo;
	}

	@Column(name = "SEASON_CODE", length = 25)
	public String getSeasonCode() {
		return this.seasonCode;
	}

	public void setSeasonCode(String seasonCode) {
		this.seasonCode = seasonCode;
	}

	@OneToMany( mappedBy = "warehouseStockReturn")
	public Set<WarehouseStockReturnDetails> getWarehouseStockReturnDetailses() {
		return this.warehouseStockReturnDetailses;
	}

	public void setWarehouseStockReturnDetailses(Set<WarehouseStockReturnDetails> warehouseStockReturnDetailses) {
		this.warehouseStockReturnDetailses = warehouseStockReturnDetailses;
	}

}
