<%@ page contentType="text/html; charset=UTF-8"%>
<%@ taglib uri="/struts-tags" prefix="s"%>

<head>
<script src="assets/common/jqGrid/js/jquery.js" type="text/javascript"></script>
<script src="assets/client/demo/js/sts.changeTheme.js" type="text/javascript"></script>
<script>
	init('<s:property value="themeName"/>');
</script>
</head>
<div align="left" style="font-family:Arial;" class="licWrap">
<table ><tr>
<td height="800" valign="top" >
 <table width="100%" border="0" cellpadding="0" cellspacing="0" style="margin:20px auto;">
  <tr>
   <td valign="top" style="font-size:12px;text-align:justify;padding:10px;">
   <h2>License Agreement</h2>
   <p>LICENSEE AGREES TO DEFEND, INDEMNIFY, AND HOLD HARMLESS SOURCETRACE, ITS OFFICERS, MEMBERS, EMPLOYEES, CONTRACTORS, AFFILIATES AND ITS LICENSORS FROM AND AGAINST ANY DAMAGES, COSTS, LIABILITIES, SETTLEMENT AMOUNTS AND/OR EXPENSES (INCLUDING ATTORNEYS FEES) INCURRED IN CONNECTION WITH ANY CLAIM, LAWSUIT OR ACTION BY ANY PARTY OR THIRD PARTY THAT ARISES OR RESULTS FROM (angel) THE USE OR DISTRIBUTION OF THE SOLUTION OR ANY PORTION THEREOF, OR (beer) ANY BREACH OF LICENSEES REPRESENTATIONS, WARRANTIES AND COVENANTS SET FORTH IN THIS AGREEMENT</p>
<p>DISCLAIMER OF WARRANTIES AND LIMITATION OF LIABILITY.</p>
<p>DISCLAIMER OF WARRANTIES. LICENSEE AGREES THAT TO THE MAXIMUM EXTENT PERMITTED BY APPLICABLE LAW, SOURCETRACE AND ITS SUPPLIERS PROVIDE THE SOLUTION AND SUPPORT SERVICES (IF ANY) AS IS AND WITH ALL FAULTS, AND HEREBY DISCLAIM ALL OTHER WARRANTIES AND CONDITIONS, EITHER EXPRESS, IMPLIED OR STATUTORY, INCLUDING, BUT NOT LIMITED TO, ANY (IF ANY) IMPLIED WARRANTIES, DUTIES OR CONDITIONS OF MERCHANTABILITY, OF FITNESS FOR A PARTICULAR PURPOSE, OF ACCURACY OR COMPLETENESS OF RESPONSES, OF RESULTS, OF WORKMANLIKE EFFORT, OF LACK OF VIRUSES, AND OF LACK OF NEGLIGENCE, ALL WITH REGARD TO THE SOLUTION, AND THE PROVISION OF OR FAILURE TO PROVIDE SUPPORT SERVICES. ALSO, THERE IS NO WARRANTY OR CONDITION OF TITLE, QUIET ENJOYMENT, QUIET POSSESSION, CORRESPONDENCE TO DESCRIPTION OR NON-INFRINGEMENT WITH REGARD TO THE SOLUTION. THE ENTIRE RISK AS TO THE QUALITY OR ARISING OUT OF USE OR PERFORMANCE OF THE SOLUTION AND SUPPORT SERVICES, IF ANY, REMAINS WITH LICENSEE.<p>
<p>EXCLUSION OF INCIDENTAL, CONSEQUENTIAL AND CERTAIN OTHER DAMAGES. TO THE MAXIMUM EXTENT PERMITTED BY APPLICABLE LAW, IN NO EVENT SHALL SOURCETRACE OR ITS SUPPLIERS BE LIABLE FOR ANY SPECIAL, INCIDENTAL, INDIRECT, PUNITIVE OR CONSEQUENTIAL DAMAGES WHATSOEVER (INCLUDING, BUT NOT LIMITED TO, DAMAGES FOR LOSS OF PROFITS OR CONFIDENTIAL OR OTHER INFORMATION, FOR BUSINESS INTERRUPTION, FOR PERSONAL INJURY, FOR LOSS OF PRIVACY, FOR FAILURE TO MEET ANY DUTY INCLUDING OF GOOD FAITH OR OF REASONABLE CARE, FOR NEGLIGENCE, AND FOR ANY OTHER PECUNIARY OR OTHER LOSS WHATSOEVER) ARISING OUT OF OR IN ANY WAY RELATED TO THE USE OF OR INABILITY TO USE THE SOLUTION, THE PROVISION OF OR FAILURE TO PROVIDE SUPPORT SERVICES, OR OTHERWISE UNDER OR IN CONNECTION WITH ANY PROVISION OF THIS AGREEMENT, EVEN IN THE EVENT OF THE FAULT, TORT (INCLUDING NEGLIGENCE), STRICT LIABILITY, BREACH OF CONTRACT OR BREACH OF WARRANTY OF SOURCETRACE OR ANY SUPPLIER, AND EVEN IF SOURCETRACE OR ANY SUPPLIER HAS BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES.</p>
<p>LIMITATION OF LIABILITY AND REMEDIES. NOTWITHSTANDING ANY DAMAGES THAT LICENSEE MIGHT INCUR FOR ANY REASON WHATSOEVER (INCLUDING, WITHOUT LIMITATION, ALL DAMAGES REFERENCED ABOVE AND ALL DIRECT OR GENERAL DAMAGES), LICENSEE AGREES THAT THE ENTIRE LIABILITY OF SOURCETRACE AND ALL OF ITS SUPPLIERS UNDER ANY PROVISION OF THIS AGREEMENT AND LICENSEES EXCLUSIVE REMEDY FOR ALL OF THE FOREGOING SHALL BE LIMITED TO THE GREATER OF THE ACTUAL FEE PAID BY LICENSEE TO SOURCETRACE UNDER THIS AGREEMENT OR U.S. $5. THE FOREGOING LIMITATIONS, EXCLUSIONS AND DISCLAIMERS SHALL APPLY TO THE MAXIMUM EXTENT PERMITTED BY APPLICABLE LAW, EVEN IF ANY REMEDY FAILS ITS ESSENTIAL PURPOSE.</p>
<p>LICENSEE WARRANTS THAT IT SHALL HOLD IN THE STRICTEST CONFIDENCE THIS COMPUTER PROGRAM AND ANY RELATED MATERIALS OR INFORMATION INCLUDING, BUT NOT LIMITED TO, ANY TECHNICAL DATA, RESEARCH, PRODUCT PLANS OR KNOW-HOW PROVIDED BY SOURCETRACE TO LICENSEE, EITHER DIRECTLY OR INDIRECTLY IN WRITING, ORALLY OR BY INSPECTION OF MATERIALS, INCLUDING THE SOFTWARE, RELATED LICENSED MATERIALS, AND OTHER APPLICATION SOFTWARE, SYSTEMS, OR MATERIALS, PROVIDED BY SOURCETRACE ('SOURCETRACES CONFIDENTIAL INFORMATION'). LICENSEE WARRANTS THAT IT SHALL NOT DISCLOSE ANY OF SOURCETRACES CONFIDENTIAL INFORMATION TO THIRD PARTIES AND LICENSEE WARRANTS THAT IT SHALL TAKE REASONABLE MEASURES TO PROTECT THE SECRECY OF AND AVOID DISCLOSURE AND UNAUTHORIZED USE OF SOURCETRACES CONFIDENTIAL INFORMATION. LICENSEE SHALL IMMEDIATELY NOTIFY SOURCETRACE IN THE EVENT OF ANY UNAUTHORIZED OR SUSPECTED USE OR DISCLOSURE OF SOURCETRACES CONFIDENTIAL INFORMATION.</p>
<p>SOURCETRACE ESERVICES EVERYWHERE COPYRIGHT ©2020 SOURCETRACE SYSTEMS.</p>
   </td>
  </tr>
 </table>
</tr></table>
</div>