
-- ----------------------------
-- Records of farmer_field
-- ----------------------------
INSERT INTO `farmer_field` (`ID`, `NAME`, `TYPE`, `TYPE_NAME`, `PARENT`, `STATUS`) VALUES ('1', 'Cert Details', '4', 'farmer_info', NULL, '1');
INSERT INTO `farmer_field` (`ID`, `NAME`, `TYPE`, `TYPE_NAME`, `PARENT`, `STATUS`) VALUES ('2', 'Personal Details', '4', 'pers_info', NULL, '1');
INSERT INTO `farmer_field` (`ID`, `NAME`, `TYPE`, `TYPE_NAME`, `PARENT`, `STATUS`) VALUES ('3', 'Contact Details', '4', 'contact_info', NULL, '1');
INSERT INTO `farmer_field` (`ID`, `NAME`, `TYPE`, `TYPE_NAME`, `PARENT`, `STATUS`) VALUES ('4', 'Farmer Family Details', '4', 'family_info', NULL, '1');
INSERT INTO `farmer_field` (`ID`, `NAME`, `TYPE`, `TYPE_NAME`, `PARENT`, `STATUS`) VALUES ('5', 'Assets Detail', '4', 'assets_info', NULL, '1');
INSERT INTO `farmer_field` (`ID`, `NAME`, `TYPE`, `TYPE_NAME`, `PARENT`, `STATUS`) VALUES ('6', 'Loan Detail', '4', 'loan_info', NULL, '1');
INSERT INTO `farmer_field` (`ID`, `NAME`, `TYPE`, `TYPE_NAME`, `PARENT`, `STATUS`) VALUES ('7', 'Dwelling Detail', '4', 'dwelling_info', NULL, '1');
INSERT INTO `farmer_field` (`ID`, `NAME`, `TYPE`, `TYPE_NAME`, `PARENT`, `STATUS`) VALUES ('8', 'Bank Details', '4', 'bank_info', NULL, '1');
INSERT INTO `farmer_field` (`ID`, `NAME`, `TYPE`, `TYPE_NAME`, `PARENT`, `STATUS`) VALUES ('9', 'Insurance Details', '4', 'insurance_info', NULL, '1');
INSERT INTO `farmer_field` (`ID`, `NAME`, `TYPE`, `TYPE_NAME`, `PARENT`, `STATUS`) VALUES ('10', 'House Hold Details', '4', 'houseHold_info', NULL, '0');
INSERT INTO `farmer_field` (`ID`, `NAME`, `TYPE`, `TYPE_NAME`, `PARENT`, `STATUS`) VALUES ('11', 'Ivestigator Deails', '4', 'investigator_info', NULL, '0');
INSERT INTO `farmer_field` (`ID`, `NAME`, `TYPE`, `TYPE_NAME`, `PARENT`, `STATUS`) VALUES ('12', 'Enroll Place', '1', 'farmer.enrollmentPlace', '1', '0');
INSERT INTO `farmer_field` (`ID`, `NAME`, `TYPE`, `TYPE_NAME`, `PARENT`, `STATUS`) VALUES ('13', 'Enroll Date', '1', 'dateOfJoining', '1', '0');
INSERT INTO `farmer_field` (`ID`, `NAME`, `TYPE`, `TYPE_NAME`, `PARENT`, `STATUS`) VALUES ('14', 'Is Certified Farmer', '1', 'farmer.isCertifiedFarmer', '1', '1');
INSERT INTO `farmer_field` (`ID`, `NAME`, `TYPE`, `TYPE_NAME`, `PARENT`, `STATUS`) VALUES ('15', 'ICS Name', '1', 'farmer.icsName', '1', '1');
INSERT INTO `farmer_field` (`ID`, `NAME`, `TYPE`, `TYPE_NAME`, `PARENT`, `STATUS`) VALUES ('16', 'ICS Code', '1', 'farmer.icsCode', '1', '1');
INSERT INTO `farmer_field` (`ID`, `NAME`, `TYPE`, `TYPE_NAME`, `PARENT`, `STATUS`) VALUES ('17', 'Cert Type', '1', 'farmer.certificationType', '1', '0');
INSERT INTO `farmer_field` (`ID`, `NAME`, `TYPE`, `TYPE_NAME`, `PARENT`, `STATUS`) VALUES ('18', 'Ics Unit No', '1', 'farmer.icsUnitNo', '1', '0');
INSERT INTO `farmer_field` (`ID`, `NAME`, `TYPE`, `TYPE_NAME`, `PARENT`, `STATUS`) VALUES ('19', 'Ics Tracenet', '1', 'farmer.icsTracenetRegNo', '1', '0');
INSERT INTO `farmer_field` (`ID`, `NAME`, `TYPE`, `TYPE_NAME`, `PARENT`, `STATUS`) VALUES ('20', 'Farmer Code by Ics', '1', 'farmer.farmerCodeByIcs', '1', '0');
INSERT INTO `farmer_field` (`ID`, `NAME`, `TYPE`, `TYPE_NAME`, `PARENT`, `STATUS`) VALUES ('21', 'Farmer Code Tracenet', '1', 'farmer.farmersCodeTracenet', '1', '0');
INSERT INTO `farmer_field` (`ID`, `NAME`, `TYPE`, `TYPE_NAME`, `PARENT`, `STATUS`) VALUES ('22', 'Beneficiary Scheme', '1', 'farmer.isBeneficiaryInGovScheme', '1', '0');
INSERT INTO `farmer_field` (`ID`, `NAME`, `TYPE`, `TYPE_NAME`, `PARENT`, `STATUS`) VALUES ('23', 'Scheme Name', '1', 'farmer.nameOfTheScheme', '1', '0');
INSERT INTO `farmer_field` (`ID`, `NAME`, `TYPE`, `TYPE_NAME`, `PARENT`, `STATUS`) VALUES ('24', 'Govt Dept', '1', 'farmer.govtDept', '1', '0');
INSERT INTO `farmer_field` (`ID`, `NAME`, `TYPE`, `TYPE_NAME`, `PARENT`, `STATUS`) VALUES ('25', 'First Name', '1', 'farmer.firstName', '2', '1');
INSERT INTO `farmer_field` (`ID`, `NAME`, `TYPE`, `TYPE_NAME`, `PARENT`, `STATUS`) VALUES ('26', 'Father Name', '1', 'farmer.lastName', '2', '1');
INSERT INTO `farmer_field` (`ID`, `NAME`, `TYPE`, `TYPE_NAME`, `PARENT`, `STATUS`) VALUES ('27', 'Sur name', '1', 'farmer.surName', '2', '0');
INSERT INTO `farmer_field` (`ID`, `NAME`, `TYPE`, `TYPE_NAME`, `PARENT`, `STATUS`) VALUES ('28', 'Gender', '1', 'farmer.gender', '2', '1');
INSERT INTO `farmer_field` (`ID`, `NAME`, `TYPE`, `TYPE_NAME`, `PARENT`, `STATUS`) VALUES ('29', 'DOB', '1', 'calendar', '2', '0');
INSERT INTO `farmer_field` (`ID`, `NAME`, `TYPE`, `TYPE_NAME`, `PARENT`, `STATUS`) VALUES ('30', 'Age', '1', 'age', '2', '1');
INSERT INTO `farmer_field` (`ID`, `NAME`, `TYPE`, `TYPE_NAME`, `PARENT`, `STATUS`) VALUES ('31', 'Farmer Photo', '1', 'farmerImage', '2', '1');
INSERT INTO `farmer_field` (`ID`, `NAME`, `TYPE`, `TYPE_NAME`, `PARENT`, `STATUS`) VALUES ('32', 'Education', '1', 'farmer.education', '2', '1');
INSERT INTO `farmer_field` (`ID`, `NAME`, `TYPE`, `TYPE_NAME`, `PARENT`, `STATUS`) VALUES ('33', 'Marital Status', '1', 'farmer.maritalSatus', '2', '0');
INSERT INTO `farmer_field` (`ID`, `NAME`, `TYPE`, `TYPE_NAME`, `PARENT`, `STATUS`) VALUES ('34', 'Acc Balance', '1', 'accBalance', '2', '0');
INSERT INTO `farmer_field` (`ID`, `NAME`, `TYPE`, `TYPE_NAME`, `PARENT`, `STATUS`) VALUES ('35', 'Id Proof', '1', 'farmer.idProof', '2', '0');
INSERT INTO `farmer_field` (`ID`, `NAME`, `TYPE`, `TYPE_NAME`, `PARENT`, `STATUS`) VALUES ('36', 'Farmer Code', '1', 'farmer.farmerCode', '2', '1');
INSERT INTO `farmer_field` (`ID`, `NAME`, `TYPE`, `TYPE_NAME`, `PARENT`, `STATUS`) VALUES ('37', 'Living Status', '1', 'farmer.personalStatus', '2', '0');
INSERT INTO `farmer_field` (`ID`, `NAME`, `TYPE`, `TYPE_NAME`, `PARENT`, `STATUS`) VALUES ('38', 'Farmer Category', '1', 'farmer.category', '2', '0');
INSERT INTO `farmer_field` (`ID`, `NAME`, `TYPE`, `TYPE_NAME`, `PARENT`, `STATUS`) VALUES ('39', 'Caste ', '1', 'farmer.casteName', '2', '0');
INSERT INTO `farmer_field` (`ID`, `NAME`, `TYPE`, `TYPE_NAME`, `PARENT`, `STATUS`) VALUES ('40', 'Social Categiry', '1', 'farmer.socialCategory', '2', '0');
INSERT INTO `farmer_field` (`ID`, `NAME`, `TYPE`, `TYPE_NAME`, `PARENT`, `STATUS`) VALUES ('41', 'Aadhar', '1', 'farmer.adhaarNo', '2', '0');
INSERT INTO `farmer_field` (`ID`, `NAME`, `TYPE`, `TYPE_NAME`, `PARENT`, `STATUS`) VALUES ('42', 'Religion', '1', 'farmer.religion', '2', '0');
INSERT INTO `farmer_field` (`ID`, `NAME`, `TYPE`, `TYPE_NAME`, `PARENT`, `STATUS`) VALUES ('43', 'Family Type', '1', 'farmer.typeOfFamily', '2', '0');
INSERT INTO `farmer_field` (`ID`, `NAME`, `TYPE`, `TYPE_NAME`, `PARENT`, `STATUS`) VALUES ('44', 'Household Wet', '1', 'farmer.houseHoldLandWet', '2', '0');
INSERT INTO `farmer_field` (`ID`, `NAME`, `TYPE`, `TYPE_NAME`, `PARENT`, `STATUS`) VALUES ('45', 'Household Dry', '1', 'farmer.houseHoldLandDry', '2', '0');
INSERT INTO `farmer_field` (`ID`, `NAME`, `TYPE`, `TYPE_NAME`, `PARENT`, `STATUS`) VALUES ('46', 'Farmer Code', '1', 'farmer.farmerCode', '2', '1');
INSERT INTO `farmer_field` (`ID`, `NAME`, `TYPE`, `TYPE_NAME`, `PARENT`, `STATUS`) VALUES ('47', 'Farmer Address', '1', 'farmer.address', '3', '0');
INSERT INTO `farmer_field` (`ID`, `NAME`, `TYPE`, `TYPE_NAME`, `PARENT`, `STATUS`) VALUES ('48', 'Mobile Number', '1', 'farmer.mobileNumber', '3', '0');
INSERT INTO `farmer_field` (`ID`, `NAME`, `TYPE`, `TYPE_NAME`, `PARENT`, `STATUS`) VALUES ('49', 'Email', '1', 'farmer.email', '3', '0');
INSERT INTO `farmer_field` (`ID`, `NAME`, `TYPE`, `TYPE_NAME`, `PARENT`, `STATUS`) VALUES ('50', ' Country', '1', 'selectedCountry', '3', '1');
INSERT INTO `farmer_field` (`ID`, `NAME`, `TYPE`, `TYPE_NAME`, `PARENT`, `STATUS`) VALUES ('51', 'selectedState', '1', 'selectedState', '3', '1');
INSERT INTO `farmer_field` (`ID`, `NAME`, `TYPE`, `TYPE_NAME`, `PARENT`, `STATUS`) VALUES ('52', 'District', '1', 'selectedLocality', '3', '1');
INSERT INTO `farmer_field` (`ID`, `NAME`, `TYPE`, `TYPE_NAME`, `PARENT`, `STATUS`) VALUES ('53', 'City', '1', 'selectedCity', '3', '1');
INSERT INTO `farmer_field` (`ID`, `NAME`, `TYPE`, `TYPE_NAME`, `PARENT`, `STATUS`) VALUES ('54', 'Grampanchayat', '1', 'selectedPanchayat', '3', '1');
INSERT INTO `farmer_field` (`ID`, `NAME`, `TYPE`, `TYPE_NAME`, `PARENT`, `STATUS`) VALUES ('55', 'Village', '1', 'selectedVillage', '3', '1');
INSERT INTO `farmer_field` (`ID`, `NAME`, `TYPE`, `TYPE_NAME`, `PARENT`, `STATUS`) VALUES ('56', 'Samithi', '1', 'selectedSamithi', '3', '1');
INSERT INTO `farmer_field` (`ID`, `NAME`, `TYPE`, `TYPE_NAME`, `PARENT`, `STATUS`) VALUES ('57', 'Sangham', '1', 'selectedSangham', '3', '0');
INSERT INTO `farmer_field` (`ID`, `NAME`, `TYPE`, `TYPE_NAME`, `PARENT`, `STATUS`) VALUES ('58', 'Group Position', '1', 'selectedGroupPosition', '3', '0');
INSERT INTO `farmer_field` (`ID`, `NAME`, `TYPE`, `TYPE_NAME`, `PARENT`, `STATUS`) VALUES ('59', 'FPO', '1', 'farmer.fpo', '3', '0');
INSERT INTO `farmer_field` (`ID`, `NAME`, `TYPE`, `TYPE_NAME`, `PARENT`, `STATUS`) VALUES ('60', 'Phone Number', '1', 'farmer.phoneNumber', '3', '0');
INSERT INTO `farmer_field` (`ID`, `NAME`, `TYPE`, `TYPE_NAME`, `PARENT`, `STATUS`) VALUES ('61', 'Status', '1', 'farmer.status', '3', '1');
INSERT INTO `farmer_field` (`ID`, `NAME`, `TYPE`, `TYPE_NAME`, `PARENT`, `STATUS`) VALUES ('62', 'No of family Members', '1', 'farmer.noOfFamilyMembers', '4', '0');
INSERT INTO `farmer_field` (`ID`, `NAME`, `TYPE`, `TYPE_NAME`, `PARENT`, `STATUS`) VALUES ('63', 'House Hold members', '1', 'farmer.noOfHouseHoldMem', '4', '1');
INSERT INTO `farmer_field` (`ID`, `NAME`, `TYPE`, `TYPE_NAME`, `PARENT`, `STATUS`) VALUES ('64', 'Head of Family', '1', 'farmer.headOfFamily', '4', '0');
INSERT INTO `farmer_field` (`ID`, `NAME`, `TYPE`, `TYPE_NAME`, `PARENT`, `STATUS`) VALUES ('65', 'Adult Cnt', '1', 'farmer.adultCountMale', '4', '1');
INSERT INTO `farmer_field` (`ID`, `NAME`, `TYPE`, `TYPE_NAME`, `PARENT`, `STATUS`) VALUES ('66', 'Child Cnt', '1', 'farmer.childCountMale', '4', '1');
INSERT INTO `farmer_field` (`ID`, `NAME`, `TYPE`, `TYPE_NAME`, `PARENT`, `STATUS`) VALUES ('67', 'School going child', '1', 'farmer.noOfSchoolChildMale', '4', '1');
INSERT INTO `farmer_field` (`ID`, `NAME`, `TYPE`, `TYPE_NAME`, `PARENT`, `STATUS`) VALUES ('68', 'Consumer Electronics', '1', 'farmer.consumerElectronics', '5', '1');
INSERT INTO `farmer_field` (`ID`, `NAME`, `TYPE`, `TYPE_NAME`, `PARENT`, `STATUS`) VALUES ('69', 'Vehicle ', '1', 'farmer.vehicle', '5', '1');
INSERT INTO `farmer_field` (`ID`, `NAME`, `TYPE`, `TYPE_NAME`, `PARENT`, `STATUS`) VALUES ('70', 'Cell', '1', 'farmer.cellPhone', '5', '0');
INSERT INTO `farmer_field` (`ID`, `NAME`, `TYPE`, `TYPE_NAME`, `PARENT`, `STATUS`) VALUES ('71', 'Loan Taken Last Year', '1', 'farmer.loanTakenLastYear', '6', '1');
INSERT INTO `farmer_field` (`ID`, `NAME`, `TYPE`, `TYPE_NAME`, `PARENT`, `STATUS`) VALUES ('72', 'Loan Taken From', '1', 'farmer.loanTakenFrom', '6', '0');
INSERT INTO `farmer_field` (`ID`, `NAME`, `TYPE`, `TYPE_NAME`, `PARENT`, `STATUS`) VALUES ('73', 'Loan Amount', '1', 'farmer.loanAmount', '6', '0');
INSERT INTO `farmer_field` (`ID`, `NAME`, `TYPE`, `TYPE_NAME`, `PARENT`, `STATUS`) VALUES ('74', 'Purpose ', '1', 'farmer.loanPupose', '6', '0');
INSERT INTO `farmer_field` (`ID`, `NAME`, `TYPE`, `TYPE_NAME`, `PARENT`, `STATUS`) VALUES ('75', 'Intrest Rate', '1', 'farmer.loanIntRate', '6', '0');
INSERT INTO `farmer_field` (`ID`, `NAME`, `TYPE`, `TYPE_NAME`, `PARENT`, `STATUS`) VALUES ('76', 'Interest Period', '1', 'farmer.loanIntPeriod', '6', '0');
INSERT INTO `farmer_field` (`ID`, `NAME`, `TYPE`, `TYPE_NAME`, `PARENT`, `STATUS`) VALUES ('77', 'Security', '1', 'farmer.loanSecurity', '6', '0');
INSERT INTO `farmer_field` (`ID`, `NAME`, `TYPE`, `TYPE_NAME`, `PARENT`, `STATUS`) VALUES ('78', 'Loan Replacement Date', '1', 'repaymentDate', '6', '0');
INSERT INTO `farmer_field` (`ID`, `NAME`, `TYPE`, `TYPE_NAME`, `PARENT`, `STATUS`) VALUES ('79', 'Loan Replacement Amount', '1', 'farmer.loanRepaymentAmount', '6', '0');
INSERT INTO `farmer_field` (`ID`, `NAME`, `TYPE`, `TYPE_NAME`, `PARENT`, `STATUS`) VALUES ('80', 'Housing Ownership', '1', 'farmer.farmerEconomy.housingOwnership', '7', '1');
INSERT INTO `farmer_field` (`ID`, `NAME`, `TYPE`, `TYPE_NAME`, `PARENT`, `STATUS`) VALUES ('81', 'Electrified Housse', '1', 'farmer.farmerEconomy.electrifiedHouse', '7', '1');
INSERT INTO `farmer_field` (`ID`, `NAME`, `TYPE`, `TYPE_NAME`, `PARENT`, `STATUS`) VALUES ('82', 'Housing Type', '1', 'farmer.farmerEconomy.housingType', '7', '0');
INSERT INTO `farmer_field` (`ID`, `NAME`, `TYPE`, `TYPE_NAME`, `PARENT`, `STATUS`) VALUES ('83', 'Drinking Water source', '1', 'farmer.farmerEconomy.drinkingWaterSource', '7', '1');
INSERT INTO `farmer_field` (`ID`, `NAME`, `TYPE`, `TYPE_NAME`, `PARENT`, `STATUS`) VALUES ('84', 'Cooking Fuel', '1', 'farmer.farmerEconomy.cookingFuel', '7', '0');
INSERT INTO `farmer_field` (`ID`, `NAME`, `TYPE`, `TYPE_NAME`, `PARENT`, `STATUS`) VALUES ('85', 'Toilet Available', '1', 'farmer.farmerEconomy.toiletAvailable', '7', '0');
INSERT INTO `farmer_field` (`ID`, `NAME`, `TYPE`, `TYPE_NAME`, `PARENT`, `STATUS`) VALUES ('86', 'Life Insurance', '1', 'farmer.lifeInsurance', '9', '1');
INSERT INTO `farmer_field` (`ID`, `NAME`, `TYPE`, `TYPE_NAME`, `PARENT`, `STATUS`) VALUES ('87', 'Life Insurance Amt', '1', 'farmer.lifeInsAmount', '9', '1');
INSERT INTO `farmer_field` (`ID`, `NAME`, `TYPE`, `TYPE_NAME`, `PARENT`, `STATUS`) VALUES ('88', 'Health Ins', '1', 'farmer.healthInsurance', '9', '1');
INSERT INTO `farmer_field` (`ID`, `NAME`, `TYPE`, `TYPE_NAME`, `PARENT`, `STATUS`) VALUES ('89', 'Health Ins Amt', '1', 'farmer.healthInsAmount', '9', '1');
INSERT INTO `farmer_field` (`ID`, `NAME`, `TYPE`, `TYPE_NAME`, `PARENT`, `STATUS`) VALUES ('90', 'Crop Ins', '1', 'farmer.isCropInsured', '9', '1');
INSERT INTO `farmer_field` (`ID`, `NAME`, `TYPE`, `TYPE_NAME`, `PARENT`, `STATUS`) VALUES ('91', 'Crop Insured', '1', 'farmer.farmerCropInsurance', '9', '1');
INSERT INTO `farmer_field` (`ID`, `NAME`, `TYPE`, `TYPE_NAME`, `PARENT`, `STATUS`) VALUES ('92', 'No of acres Insured', '1', 'farmer.acresInsured', '9', '1');
INSERT INTO `farmer_field` (`ID`, `NAME`, `TYPE`, `TYPE_NAME`, `PARENT`, `STATUS`) VALUES ('93', 'Primary Occupation', '1', 'farmer.houseOccupationPrimary', '10', '1');
INSERT INTO `farmer_field` (`ID`, `NAME`, `TYPE`, `TYPE_NAME`, `PARENT`, `STATUS`) VALUES ('94', 'Secondary Occupation', '1', 'farmer.houseOccupationSecondary', '10', '1');
INSERT INTO `farmer_field` (`ID`, `NAME`, `TYPE`, `TYPE_NAME`, `PARENT`, `STATUS`) VALUES ('95', 'Members in CBOs', '1', 'farmer.familyMember', '10', '1');
INSERT INTO `farmer_field` (`ID`, `NAME`, `TYPE`, `TYPE_NAME`, `PARENT`, `STATUS`) VALUES ('96', 'Member of GRS', '1', 'farmer.grsMember', '10', '1');
INSERT INTO `farmer_field` (`ID`, `NAME`, `TYPE`, `TYPE_NAME`, `PARENT`, `STATUS`) VALUES ('97', 'Share Capital 1000', '1', 'farmer.paidShareCapitial', '10', '1');
INSERT INTO `farmer_field` (`ID`, `NAME`, `TYPE`, `TYPE_NAME`, `PARENT`, `STATUS`) VALUES ('98', 'Investigator Opinion', '1', 'farmer.investigatorOpinion', '11', '1');
INSERT INTO `farmer_field` (`ID`, `NAME`, `TYPE`, `TYPE_NAME`, `PARENT`, `STATUS`) VALUES ('99', 'Investigate Date', '1', 'investigatorDate', '11', '1');
INSERT INTO `farmer_field` (`ID`, `NAME`, `TYPE`, `TYPE_NAME`, `PARENT`, `STATUS`) VALUES ('100', 'Investigator Name', '1', 'farmer.investigatorName', '11', '1');
INSERT INTO `farmer_field` (`ID`, `NAME`, `TYPE`, `TYPE_NAME`, `PARENT`, `STATUS`) VALUES ('101', 'ICS Year ', '1', 'farmer.icsYear', '1', '1');
INSERT INTO `farmer_field` (`ID`, `NAME`, `TYPE`, `TYPE_NAME`, `PARENT`, `STATUS`) VALUES ('102', 'Form Filled By', '1', 'farmer.formFilledBy', '1', '0');
INSERT INTO `farmer_field` (`ID`, `NAME`, `TYPE`, `TYPE_NAME`, `PARENT`, `STATUS`) VALUES ('103', 'Objective', '1', 'farmer.objective', '1', '0');
INSERT INTO `farmer_field` (`ID`, `NAME`, `TYPE`, `TYPE_NAME`, `PARENT`, `STATUS`) VALUES ('104', 'Assess', '1', 'farmer.assess', '1', '0');
INSERT INTO `farmer_field` (`ID`, `NAME`, `TYPE`, `TYPE_NAME`, `PARENT`, `STATUS`) VALUES ('105', 'PlaceOfAsss', '1', 'farmer.placeOfAsss', '1', '0');
INSERT INTO `farmer_field` (`ID`, `NAME`, `TYPE`, `TYPE_NAME`, `PARENT`, `STATUS`) VALUES ('106', 'PreferenceWork', '1', 'farmer.prefWrk', '1', '0');
INSERT INTO `farmer_field` (`ID`, `NAME`, `TYPE`, `TYPE_NAME`, `PARENT`, `STATUS`) VALUES ('107', 'Self Assesment', '4', 'self_Assesment', NULL, '0');
INSERT INTO `farmer_field` (`ID`, `NAME`, `TYPE`, `TYPE_NAME`, `PARENT`, `STATUS`) VALUES ('108', 'Social', '4', 'social_info', NULL, '0');
INSERT INTO `farmer_field` (`ID`, `NAME`, `TYPE`, `TYPE_NAME`, `PARENT`, `STATUS`) VALUES ('109', 'Farmer Health Info', '4', 'farmerHealthInfo', NULL, '0');
INSERT INTO `farmer_field` (`ID`, `NAME`, `TYPE`, `TYPE_NAME`, `PARENT`, `STATUS`) VALUES ('110', 'farmer.isLoanTakenScheme', '1', 'farmer.isLoanTakenScheme', '6', '0');
INSERT INTO `farmer_field` (`ID`, `NAME`, `TYPE`, `TYPE_NAME`, `PARENT`, `STATUS`) VALUES ('111', 'farmer.loanTakenScheme', '1', 'farmer.loanTakenScheme', '6', '0');
INSERT INTO `farmer_field` (`ID`, `NAME`, `TYPE`, `TYPE_NAME`, `PARENT`, `STATUS`) VALUES ('112', 'Age Label', '3', 'hideAge', '2', '0');
INSERT INTO `farmer_field` (`ID`, `NAME`, `TYPE`, `TYPE_NAME`, `PARENT`, `STATUS`) VALUES ('113', 'Text Label', '3', 'showAge', '2', '1');



-- ----------------------------
-- Records of farm_field
-- ----------------------------
INSERT INTO `farm_field` (`ID`, `NAME`, `TYPE`, `TYPE_NAME`, `PARENT`, `STATUS`) VALUES ('1', 'Farm Info', '4', 'farmInfo', NULL, '1');
INSERT INTO `farm_field` (`ID`, `NAME`, `TYPE`, `TYPE_NAME`, `PARENT`, `STATUS`) VALUES ('2', 'Contact Info', '4', 'contactInfo', NULL, '0');
INSERT INTO `farm_field` (`ID`, `NAME`, `TYPE`, `TYPE_NAME`, `PARENT`, `STATUS`) VALUES ('3', 'Soil And Irrigation ', '4', 'soilIrrigationInfo', NULL, '0');
INSERT INTO `farm_field` (`ID`, `NAME`, `TYPE`, `TYPE_NAME`, `PARENT`, `STATUS`) VALUES ('4', 'Farm Labour ', '4', 'farmLabourInfo', NULL, '0');
INSERT INTO `farm_field` (`ID`, `NAME`, `TYPE`, `TYPE_NAME`, `PARENT`, `STATUS`) VALUES ('5', 'Conversion Information ', '4', 'conversionInfo', NULL, '0');
INSERT INTO `farm_field` (`ID`, `NAME`, `TYPE`, `TYPE_NAME`, `PARENT`, `STATUS`) VALUES ('6', 'Conversion Status', '4', 'conversionStatus', NULL, '0');
INSERT INTO `farm_field` (`ID`, `NAME`, `TYPE`, `TYPE_NAME`, `PARENT`, `STATUS`) VALUES ('7', 'GFS Details', '4', 'gfsDetails', NULL, '0');
INSERT INTO `farm_field` (`ID`, `NAME`, `TYPE`, `TYPE_NAME`, `PARENT`, `STATUS`) VALUES ('8', 'Integrated Farming System', '4', 'ifsInfo', NULL, '0');
INSERT INTO `farm_field` (`ID`, `NAME`, `TYPE`, `TYPE_NAME`, `PARENT`, `STATUS`) VALUES ('9', 'Soil testing', '4', 'soilTest', NULL, '0');
INSERT INTO `farm_field` (`ID`, `NAME`, `TYPE`, `TYPE_NAME`, `PARENT`, `STATUS`) VALUES ('10', 'Farm Name', '1', 'farm.farmName', '1', '1');
INSERT INTO `farm_field` (`ID`, `NAME`, `TYPE`, `TYPE_NAME`, `PARENT`, `STATUS`) VALUES ('11', 'Survey Number', '1', 'farm.farmDetailedInfo.surveyNumber', '1', '0');
INSERT INTO `farm_field` (`ID`, `NAME`, `TYPE`, `TYPE_NAME`, `PARENT`, `STATUS`) VALUES ('12', 'Total Land', '1', 'farm.farmDetailedInfo.totalLandHolding', '1', '1');
INSERT INTO `farm_field` (`ID`, `NAME`, `TYPE`, `TYPE_NAME`, `PARENT`, `STATUS`) VALUES ('13', 'Proposed Land', '1', 'farm.farmDetailedInfo.proposedPlantingArea', '1', '0');
INSERT INTO `farm_field` (`ID`, `NAME`, `TYPE`, `TYPE_NAME`, `PARENT`, `STATUS`) VALUES ('14', 'Total Land Hectare Calc', '3', 'landHectValues', '1', '0');
INSERT INTO `farm_field` (`ID`, `NAME`, `TYPE`, `TYPE_NAME`, `PARENT`, `STATUS`) VALUES ('15', 'Total Proposed Hectare Calc', '3', 'plantHectValues', '1', '0');
INSERT INTO `farm_field` (`ID`, `NAME`, `TYPE`, `TYPE_NAME`, `PARENT`, `STATUS`) VALUES ('16', 'Farm Owned', '1', 'selectedFarmOwned', '1', '0');
INSERT INTO `farm_field` (`ID`, `NAME`, `TYPE`, `TYPE_NAME`, `PARENT`, `STATUS`) VALUES ('17', 'Land Gradient', '1', 'selectedGradient', '1', '0');
INSERT INTO `farm_field` (`ID`, `NAME`, `TYPE`, `TYPE_NAME`, `PARENT`, `STATUS`) VALUES ('18', 'Same Address as Farmer', '1', 'farm.farmDetailedInfo.sameAddressofFarmer', '1', '0');
INSERT INTO `farm_field` (`ID`, `NAME`, `TYPE`, `TYPE_NAME`, `PARENT`, `STATUS`) VALUES ('19', 'Farm Address', '1', 'farm.farmDetailedInfo.farmAddress', '1', '0');
INSERT INTO `farm_field` (`ID`, `NAME`, `TYPE`, `TYPE_NAME`, `PARENT`, `STATUS`) VALUES ('20', 'Approach Road', '1', 'selectedRoad', '1', '0');
INSERT INTO `farm_field` (`ID`, `NAME`, `TYPE`, `TYPE_NAME`, `PARENT`, `STATUS`) VALUES ('21', 'Certification Year', '1', 'farm.certYear', '1', '0');
INSERT INTO `farm_field` (`ID`, `NAME`, `TYPE`, `TYPE_NAME`, `PARENT`, `STATUS`) VALUES ('22', 'Farm Photo', '1', 'farm.farmImageFileName', '1', '1');
INSERT INTO `farm_field` (`ID`, `NAME`, `TYPE`, `TYPE_NAME`, `PARENT`, `STATUS`) VALUES ('23', 'Farm Reg Number', '1', 'farm.farmRegNumber', '1', '0');
INSERT INTO `farm_field` (`ID`, `NAME`, `TYPE`, `TYPE_NAME`, `PARENT`, `STATUS`) VALUES ('24', 'Reg Year', '1', 'farm.regYear', '1', '0');
INSERT INTO `farm_field` (`ID`, `NAME`, `TYPE`, `TYPE_NAME`, `PARENT`, `STATUS`) VALUES ('25', 'Topology', '1', 'farm.landTopology', '1', '0');
INSERT INTO `farm_field` (`ID`, `NAME`, `TYPE`, `TYPE_NAME`, `PARENT`, `STATUS`) VALUES ('26', 'District', '1', 'selectedLocality', '2', '0');
INSERT INTO `farm_field` (`ID`, `NAME`, `TYPE`, `TYPE_NAME`, `PARENT`, `STATUS`) VALUES ('27', 'City', '1', 'selectedCity', '2', '0');
INSERT INTO `farm_field` (`ID`, `NAME`, `TYPE`, `TYPE_NAME`, `PARENT`, `STATUS`) VALUES ('28', 'panchayat.name', '1', 'selectedPanchayat', '2', '0');
INSERT INTO `farm_field` (`ID`, `NAME`, `TYPE`, `TYPE_NAME`, `PARENT`, `STATUS`) VALUES ('29', 'profile.samithi', '1', 'selectedSamithi', '2', '0');
INSERT INTO `farm_field` (`ID`, `NAME`, `TYPE`, `TYPE_NAME`, `PARENT`, `STATUS`) VALUES ('30', 'fpoGroup', '1', 'selectedFpo', '2', '0');
INSERT INTO `farm_field` (`ID`, `NAME`, `TYPE`, `TYPE_NAME`, `PARENT`, `STATUS`) VALUES ('31', 'farm.soilType', '1', 'selectedSoilType', '3', '0');
INSERT INTO `farm_field` (`ID`, `NAME`, `TYPE`, `TYPE_NAME`, `PARENT`, `STATUS`) VALUES ('32', 'farm.soilTexture', '1', 'selectedTexture', '3', '0');
INSERT INTO `farm_field` (`ID`, `NAME`, `TYPE`, `TYPE_NAME`, `PARENT`, `STATUS`) VALUES ('33', 'farm.soilFertilityStatus', '1', 'selectedSoilFertility', '3', '0');
INSERT INTO `farm_field` (`ID`, `NAME`, `TYPE`, `TYPE_NAME`, `PARENT`, `STATUS`) VALUES ('34', 'farm.farmIrrigationSource', '1', 'selectedIrrigation', '3', '0');
INSERT INTO `farm_field` (`ID`, `NAME`, `TYPE`, `TYPE_NAME`, `PARENT`, `STATUS`) VALUES ('35', 'Method of Irrigation', '1', 'selectedMethodOfIrrigation', '3', '0');
INSERT INTO `farm_field` (`ID`, `NAME`, `TYPE`, `TYPE_NAME`, `PARENT`, `STATUS`) VALUES ('36', 'farm.farmDetailedInfo.boreWellRechargeStructure', '1', 'farm.farmDetailedInfo.boreWellRechargeStructure', '3', '0');
INSERT INTO `farm_field` (`ID`, `NAME`, `TYPE`, `TYPE_NAME`, `PARENT`, `STATUS`) VALUES ('37', 'Last Date of Chemical Applicatio', '1', 'farm.farmDetailedInfo.lastDateOfChemicalApplication', '4', '0');
INSERT INTO `farm_field` (`ID`, `NAME`, `TYPE`, `TYPE_NAME`, `PARENT`, `STATUS`) VALUES ('38', 'Conventional Lands ', '1', 'farm.farmDetailedInfo.conventionalLand', '4', '0');
INSERT INTO `farm_field` (`ID`, `NAME`, `TYPE`, `TYPE_NAME`, `PARENT`, `STATUS`) VALUES ('39', 'Fallow/Pasture Land ', '1', 'farm.farmDetailedInfo.fallowOrPastureLand', '4', '0');
INSERT INTO `farm_field` (`ID`, `NAME`, `TYPE`, `TYPE_NAME`, `PARENT`, `STATUS`) VALUES ('40', 'Conventional Crops ', '1', 'farm.farmDetailedInfo.conventionalCrops', '4', '0');
INSERT INTO `farm_field` (`ID`, `NAME`, `TYPE`, `TYPE_NAME`, `PARENT`, `STATUS`) VALUES ('41', 'Estimated Yield ', '1', 'farm.farmDetailedInfo.conventionalEstimatedYield', '4', '0');
INSERT INTO `farm_field` (`ID`, `NAME`, `TYPE`, `TYPE_NAME`, `PARENT`, `STATUS`) VALUES ('42', 'IFS Practices', '1', 'farm.ifs', '1', '0');
INSERT INTO `farm_field` (`ID`, `NAME`, `TYPE`, `TYPE_NAME`, `PARENT`, `STATUS`) VALUES ('43', 'Vegetables in Kitchen Garden ', '1', 'farm.vegetableName', '1', '0');
INSERT INTO `farm_field` (`ID`, `NAME`, `TYPE`, `TYPE_NAME`, `PARENT`, `STATUS`) VALUES ('44', 'Uses of Kitchen Garden ', '1', 'farm.kitchenGarden', '1', '0');
INSERT INTO `farm_field` (`ID`, `NAME`, `TYPE`, `TYPE_NAME`, `PARENT`, `STATUS`) VALUES ('45', 'Benefits from Backyard Poultry ', '1', 'farm.backYardPoultry', '1', '0');
INSERT INTO `farm_field` (`ID`, `NAME`, `TYPE`, `TYPE_NAME`, `PARENT`, `STATUS`) VALUES ('46', 'Soil Conservation Measures', '1', 'farm.soilConservation', '1', '0');
INSERT INTO `farm_field` (`ID`, `NAME`, `TYPE`, `TYPE_NAME`, `PARENT`, `STATUS`) VALUES ('47', 'Water Conservation Measures ', '1', 'farm.waterConservation', '1', '0');
INSERT INTO `farm_field` (`ID`, `NAME`, `TYPE`, `TYPE_NAME`, `PARENT`, `STATUS`) VALUES ('48', 'Farmer Service Centres ', '1', 'farm.serviceCentres', '1', '0');
INSERT INTO `farm_field` (`ID`, `NAME`, `TYPE`, `TYPE_NAME`, `PARENT`, `STATUS`) VALUES ('49', 'Farmer Field school', '1', 'farm.farmDetailedInfo.farmerFieldSchool', '1', '0');
INSERT INTO `farm_field` (`ID`, `NAME`, `TYPE`, `TYPE_NAME`, `PARENT`, `STATUS`) VALUES ('50', 'How did it benefited to you? ', '1', 'farm.farmDetailedInfo.isFFSBenifited', '1', '0');
INSERT INTO `farm_field` (`ID`, `NAME`, `TYPE`, `TYPE_NAME`, `PARENT`, `STATUS`) VALUES ('51', 'Trainings and Programs ', '1', 'farm.trainingProgram', '1', '0');
INSERT INTO `farm_field` (`ID`, `NAME`, `TYPE`, `TYPE_NAME`, `PARENT`, `STATUS`) VALUES ('52', 'Did you cultivated millets this year ? ', '1', 'farm.farmDetailedInfo.milletCultivated', '1', '0');
INSERT INTO `farm_field` (`ID`, `NAME`, `TYPE`, `TYPE_NAME`, `PARENT`, `STATUS`) VALUES ('53', 'Land ICS details', '4', 'icsAccordian', NULL, '0');
INSERT INTO `farm_field` (`ID`, `NAME`, `TYPE`, `TYPE_NAME`, `PARENT`, `STATUS`) VALUES ('54', 'Benefit Details', '4', 'benefit', NULL, '0');
INSERT INTO `farm_field` (`ID`, `NAME`, `TYPE`, `TYPE_NAME`, `PARENT`, `STATUS`) VALUES ('55', 'Soil Testing', '4', 'soilTesting', NULL, '0');
INSERT INTO `farm_field` (`ID`, `NAME`, `TYPE`, `TYPE_NAME`, `PARENT`, `STATUS`) VALUES ('57', 'Land Mark', '4', 'landMarkInfo', NULL, '0');
INSERT INTO `farm_field` (`ID`, `NAME`, `TYPE`, `TYPE_NAME`, `PARENT`, `STATUS`) VALUES ('60', 'Own Land', '1', 'farm.ownLand', '1', '1');
INSERT INTO `farm_field` (`ID`, `NAME`, `TYPE`, `TYPE_NAME`, `PARENT`, `STATUS`) VALUES ('61', 'Leased Land', '1', 'farm.leasedLand', '1', '1');
INSERT INTO `farm_field` (`ID`, `NAME`, `TYPE`, `TYPE_NAME`, `PARENT`, `STATUS`) VALUES ('62', 'Irrigated Land', '1', 'farm.irrigatedLand', '1', '1');
INSERT INTO `farm_field` (`ID`, `NAME`, `TYPE`, `TYPE_NAME`, `PARENT`, `STATUS`) VALUES ('63', 'GPS', '4', 'gpsInfo', NULL, '0');
