package com.sourcetrace.eses.entity;
// Generated 23 Jun, 2020 5:09:17 PM by Hibernate Tools 5.0.6.Final

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;

import org.hibernate.annotations.FilterDef;
import org.hibernate.annotations.Filters;
import org.hibernate.annotations.ParamDef;

/**
 * AccessLog generated by hbm2java
 */
@Entity
//@FilterDef(name = "branchFilter", parameters = @ParamDef(name = "branchIdParam", type = "string"))
//@Filters(@org.hibernate.annotations.Filter(name = "branchFilter", condition = "branch_id in ( :branchIdParam )"))
@Table(name = "ACCESS_LOG")
public class AccessLog implements java.io.Serializable {

	private Long id;
	private String login;
	private String logout;
	private String module;
	private int status;
	private String user;
	private String userIPAddress;

	public AccessLog() {
	}

	public AccessLog(String module, String user, String userIPAddress) {

		this.module = module;
		this.user = user;
		this.userIPAddress = userIPAddress;
	}

	public AccessLog(String login, String userId, String module, int status) {
		this.login = login;
		this.user = userId;
		this.module = module;
		this.status = status;
	}


	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "ID", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@Column(name = "LOGIN", length = 45)
	public String getLogin() {
		return this.login;
	}

	public void setLogin(String login) {
		this.login = login;
	}

	@Column(name = "LOGOUT", length = 45)
	public String getLogout() {
		return this.logout;
	}

	public void setLogout(String logout) {
		this.logout = logout;
	}

	@Column(name = "MODULE", length = 45)
	public String getModule() {
		return this.module;
	}

	public void setModule(String module) {
		this.module = module;
	}

	@Column(name = "STATUS", nullable = false)
	public int getStatus() {
		return this.status;
	}

	public void setStatus(int status) {
		this.status = status;
	}
	@Column(name = "USER_ID", length = 45)
	public String getUser() {
		return user;
	}

	
	public void setUser(String user) {
		this.user = user;
	}

	@Column(name = "IP_ADDRESS", length = 45)
	public String getUserIPAddress() {
		return userIPAddress;
	}

	public void setUserIPAddress(String userIPAddress) {
		this.userIPAddress = userIPAddress;
	}

}
