package com.sourcetrace.eses.entity;
// Generated 23 Jun, 2020 5:09:17 PM by Hibernate Tools 5.0.6.Final

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.annotations.FilterDef;
import org.hibernate.annotations.Filters;
import org.hibernate.annotations.ParamDef;
import org.hibernate.annotations.UpdateTimestamp;

/**
 * AgentAccessLogDetail generated by hbm2java
 */
@Entity

@Table(name = "agent_access_log_detail")
public class AgentAccessLogDetail implements java.io.Serializable {

	private Long id;
	private AgentAccessLog agentAccessLog;
	private String txnType;
	private String txnMode;
	private String messageNumber;
	private Long txnCount;
	private String servicePoint;
	private Date txnDate;
	private String latitude;
	private String longitude;
	private String updatedUser;
	private Date updatedDate;
	

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "ID", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ACCESS_ID")
	public AgentAccessLog getAgentAccessLog() {
		return agentAccessLog;
	}

	public void setAgentAccessLog(AgentAccessLog agentAccessLog) {
		this.agentAccessLog = agentAccessLog;
	}

	@Column(name = "TXN_TYPE")
	public String getTxnType() {
		return this.txnType;
	}

	public void setTxnType(String txnType2) {
		this.txnType = txnType2;
	}

	@Column(name = "TXN_MODE", length = 45)
	public String getTxnMode() {
		return this.txnMode;
	}

	public void setTxnMode(String txnMode) {
		this.txnMode = txnMode;
	}

	@Column(name = "MESSAGE_NUMBER", length = 50)
	public String getMessageNumber() {
		return this.messageNumber;
	}

	public void setMessageNumber(String messageNumber) {
		this.messageNumber = messageNumber;
	}

	@Column(name = "TXN_COUNT")
	public Long getTxnCount() {
		return this.txnCount;
	}

	public void setTxnCount(Long txnCount) {
		this.txnCount = txnCount;
	}

	@Column(name = "SERVICE_POINT", length = 50)
	public String getServicePoint() {
		return this.servicePoint;
	}

	public void setServicePoint(String servicePoint) {
		this.servicePoint = servicePoint;
	}
	@Temporal(TemporalType.DATE)
	@Column(name = "LAST_UPDATED_DATE", length = 10)
	public Date getTxnDate() {
		return txnDate;
	}

	public void setTxnDate(Date txnDate) {
		this.txnDate = txnDate;
	}
	@Column(name = "LATITUDE")
	public String getLatitude() {
		return latitude;
	}

	public void setLatitude(String latitude) {
		this.latitude = latitude;
	}
	@Column(name = "LONGITUDE")
	public String getLongitude() {
		return longitude;
	}

	public void setLongitude(String longitude) {
		this.longitude = longitude;
	}
	
	@Column(name = "UPDATED_USER", length = 50, columnDefinition = "VARCHAR(255)")
	public String getUpdatedUser() {
		return updatedUser;
	}

	public void setUpdatedUser(String updatedUser) {
		this.updatedUser = updatedUser;
	}
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "UPDATED_DATE",  length = 19)
	@UpdateTimestamp
	public Date getUpdatedDate() {
		return updatedDate;
	}

	public void setUpdatedDate(Date updatedDate) {
		this.updatedDate = updatedDate;
	}

}
