package com.sourcetrace.eses.entity;
// Generated 23 Jun, 2020 5:09:17 PM by Hibernate Tools 5.0.6.Final

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * AgentType generated by hbm2java
 */
@Entity
 @Table(name = "AGENT_TYPE")
public class AgentType implements java.io.Serializable {

	
	public static enum AgentTypes {
        NA, COOPERATIVE_MANAGER, FIELD_STAFF, WAREHOUSE_OPERATOR, GINNER, SPINNER
    }
	 public static final String BUYER = "01";
    public static final String FIELD_STAFF = "02";
    public static final String FARM_FOREST = "02";
    public static final String COOPERATIVE_MANAGER = "01";
    public static final String WAREHOUSE_OPERATOR = "03";
    public static final String GINNER = "04";
    public static final String SPINNER = "05";
	private Long id;
	private String code;
	private String name;

	public AgentType() {
	}

	public AgentType(Long id) {
		this.id = id;
	}

	public AgentType(Long id, String code, String name) {
		this.id = id;
		this.code = code;
		this.name = name;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
     @Column(name = "ID", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@Column(name = "CODE", length = 45)
	public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	@Column(name = "NAME", length = 45)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

}
