package com.sourcetrace.eses.entity;
// Generated 23 Jun, 2020 5:09:17 PM by Hibernate Tools 5.0.6.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Transient;
import com.sourcetrace.eses.util.StringUtil;

/**
 * BranchMaster generated by hbm2java
 */
@Entity
 @Table(name = "BRANCH_MASTER")
public class BranchMaster implements java.io.Serializable {

	private Long id;
	private String branchId;
	private String parentBranch;
	private String name;
	private String contactPerson;
	private String phoneNo;
	private String address;
	private String status;
	private String webSeq;
	private String remoteSeq;
	private String Limit;
	private String webIdLimit;
	
	// transient variable
	private double accountBalance;
	private String accountRupee;
	private String accountPaise;
	private String tenant;
	
		

	public static final String INACTIVE="0";
	public BranchMaster() {
	}

	public BranchMaster(String branchId) {
		this.branchId = branchId;
	}

	public BranchMaster(String branchId, String parentBranch, String name, String contactPerson, String phoneNo,
			String address, String status, String webSeq, String remoteSeq, String Limit, String webIdLimit) {
		this.branchId = branchId;
		this.parentBranch = parentBranch;
		this.name = name;
		this.contactPerson = contactPerson;
		this.phoneNo = phoneNo;
		this.address = address;
		this.status = status;
		this.webSeq = webSeq;
		this.remoteSeq = remoteSeq;
		this.Limit = Limit;
		this.webIdLimit = webIdLimit;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "ID", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@Column(name = "BRANCH_ID",  length = 50)//
	public String getBranchId() {
		return this.branchId;
	}

	public void setBranchId(String branchId) {
		this.branchId = branchId;
	}

	@Column(name = "PARENT_ID", length = 20)
	public String getParentBranch() {
		return this.parentBranch;
	}

	public void setparentBranch(String parentBranch) {
		this.parentBranch = parentBranch;
	}

	@Column(name = "NAME", length = 50)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "CONTACT_PERSON", length = 50)
	public String getContactPerson() {
		return this.contactPerson;
	}

	public void setContactPerson(String contactPerson) {
		this.contactPerson = contactPerson;
	}

	@Column(name = "PHONE_NO", length = 15)
	public String getPhoneNo() {
		return this.phoneNo;
	}

	public void setPhoneNo(String phoneNo) {
		this.phoneNo = phoneNo;
	}

	@Column(name = "ADDRESS", length = 150)
	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	@Column(name = "STATUS", length = 2)
	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	@Column(name = "WEB_SEQ", length = 15)
	public String getWebSeq() {
		return this.webSeq;
	}

	public void setWebSeq(String webSeq) {
		this.webSeq = webSeq;
	}

	@Column(name = "REMOTE_SEQ", length = 15)
	public String getRemoteSeq() {
		return this.remoteSeq;
	}

	public void setRemoteSeq(String remoteSeq) {
		this.remoteSeq = remoteSeq;
	}

	@Column(name = "SEQ_LIMIT", length = 15)
	public String getLimit() {
		return this.Limit;
	}

	public void setLimit(String Limit) {
		this.Limit =Limit;
	}

	@Column(name = "WEB_ID_LIMIT", length = 15)
	public String getWebIdLimit() {
		return this.webIdLimit;
	}

	public void setWebIdLimit(String webIdLimit) {
		this.webIdLimit = webIdLimit;
	}
	
	
	@Transient
	public double getAccountBalance() {
		
		if (this.getAccountRupee() == null || StringUtil.isEmpty(this.getAccountRupee())) {
			setAccountRupee("0");
		}
		if (this.getAccountPaise() == null || StringUtil.isEmpty(this.getAccountPaise())) {
			setAccountPaise("0");
		}
		return Double.valueOf(this.getAccountRupee() + "." + this.getAccountPaise());
	}

	public void setAccountBalance(double accountBalance) {
		this.accountBalance = accountBalance;
	}

	@Transient
	public String getAccountRupee() {
		return accountRupee;
	}

	public void setAccountRupee(String accountRupee) {
		this.accountRupee = accountRupee;
	}

	@Transient
	public String getAccountPaise() {
		return accountPaise;
	}

	public void setAccountPaise(String accountPaise) {
		this.accountPaise = accountPaise;
	}

	@Transient
	public String getTenant() {
		return tenant;
	}

	public void setTenant(String tenant) {
		this.tenant = tenant;
	}
	
	
   
	

	
}
