package com.sourcetrace.eses.entity;
// Generated 23 Jun, 2020 5:09:17 PM by Hibernate Tools 5.0.6.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * ClientProf generated by hbm2java
 */
@Entity
@Table(name = "client_prof")
public class ClientProf implements java.io.Serializable {

	private long profId;
	private Long clientTypeId;

	public ClientProf() {
	}

	public ClientProf(long profId) {
		this.profId = profId;
	}

	public ClientProf(long profId, Long clientTypeId) {
		this.profId = profId;
		this.clientTypeId = clientTypeId;
	}

	@Id

	@Column(name = "PROF_ID", unique = true, nullable = false)
	public long getProfId() {
		return this.profId;
	}

	public void setProfId(long profId) {
		this.profId = profId;
	}

	@Column(name = "CLIENT_TYPE_ID")
	public Long getClientTypeId() {
		return this.clientTypeId;
	}

	public void setClientTypeId(Long clientTypeId) {
		this.clientTypeId = clientTypeId;
	}

}
