package com.sourcetrace.eses.entity;
// Generated 23 Jun, 2020 5:09:17 PM by Hibernate Tools 5.0.6.Final

import java.util.Set;
import java.util.SortedSet;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

import lombok.Getter;
import lombok.Setter;
import org.hibernate.envers.*;

/**
 * ContInfo generated by hbm2java
 */
@Entity
@Table(name = "CONT_INFO")
@Getter
@Setter
@Audited
public class ContactInfo implements java.io.Serializable {
	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "ID", unique = true, nullable = false)
	private Long id;
	
	@Column(name = "TYPE")
	private int type;
	
	@Column(name = "ADDR")
	private String address1;
	
	@Column(name = "ADDR2")
	private String address2;
	
	@Column(name = "ZIP")
	private String zipCode;
	
	@Column(name = "PHONE")
	private String phoneNumber;
	
	@Column(name = "MOBILE")
	private String mobileNumbere;
	
	@Column(name = "EMAIL")
	private String email;

	

}
