package com.sourcetrace.eses.entity;
// Generated 23 Jun, 2020 5:09:17 PM by Hibernate Tools 5.0.6.Final

import org.hibernate.envers.*;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Coordinates generated by hbm2java
 */
@Entity
@Table(name = "COORDINATES")
@Audited
public class Coordinates implements Comparable<Coordinates> {

	private Long id;
	
	private String latitude;
	private String longitude;
	private Long orderNo;
	private CoordinatesMap coordinatesMap;
	private int type;
	private String title;
	private String description;

	public Coordinates() {
	}

	public Coordinates(int type) {
		this.type = type;
	}

	public Coordinates( String latitude, String longitude, Long orderNo, CoordinatesMap coordinatesMap, int type,
			String title, String description) {
		
		this.latitude = latitude;
		this.longitude = longitude;
		this.orderNo = orderNo;
		this.coordinatesMap = coordinatesMap;
		this.type = type;
		this.title = title;
		this.description = description;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "ID", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	

	

	@Column(name = "LATITUDE", length = 20)
	public String getLatitude() {
		return this.latitude;
	}

	public void setLatitude(String latitude) {
		this.latitude = latitude;
	}

	@Column(name = "LONGITUDE", length = 20)
	public String getLongitude() {
		return this.longitude;
	}

	public void setLongitude(String longitude) {
		this.longitude = longitude;
	}

	@Column(name = "ORDER_NO")
	public Long getOrderNo() {
		return this.orderNo;
	}

	public void setOrderNo(Long orderNo) {
		this.orderNo = orderNo;
	}

	@ManyToOne(fetch=FetchType.LAZY)
	@JoinColumn(name = "COORDINATES_MAP_ID")
	public CoordinatesMap getCoordinatesMap() {
		return this.coordinatesMap;
	}

	public void setCoordinatesMap(CoordinatesMap coordinatesMap) {
		this.coordinatesMap = coordinatesMap;
	}

	@Column(name = "TYPE", nullable = false)
	public int getType() {
		return this.type;
	}

	public void setType(int type) {
		this.type = type;
	}

	@Column(name = "TITLE")
	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	@Column(name = "DESCRIPTION", columnDefinition="LONGTEXT")
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public int compareTo(Coordinates coord) {
		
		long compareQuantity = ((Coordinates) coord).getOrderNo(); 
		
		//ascending order
		return (int) (this.orderNo - compareQuantity);
		
	}
}
