package com.sourcetrace.eses.entity;
// Generated 23 Jun, 2020 5:09:17 PM by Hibernate Tools 5.0.6.Final

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;
import java.util.List;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Transient;

import org.hibernate.annotations.FilterDef;
import org.hibernate.annotations.Filters;
import org.hibernate.annotations.ParamDef;
import org.hibernate.annotations.Type;
import org.hibernate.annotations.UpdateTimestamp;
import org.hibernate.envers.*;

/**
 * Device generated by hbm2java
 */
@Entity
@FilterDef(name = "branchFilter", parameters = @ParamDef(name = "branchIdParam", type = "string"))
@Filters(@org.hibernate.annotations.Filter(name = "branchFilter", condition = "branch_id in ( :branchIdParam )"))
@Table(name = "DEVICE")
@Audited
public class Device implements java.io.Serializable {

	public static final int POS = 1;
	public static final int ENROLLMENT_STATION = 2;
	public static final int DEVICE_CODE_LEN_MIN = 1;
	public static final int SERIAL_NUMBER_LEN_MIN = 1;
	public static final int DEVICE_CODE_LEN_MAX = 20;
	public static final int SERIAL_NUMBER_MAX = 35;
	public static final int DEVICE_NAME_MAX = 20;

	public static final String POS_DEVICE = "POS";
	public static final String MOBILE_DEVICE = "Mobile";
	public static final String LAPTOP_DEVICE = "Laptop";

	public static final int DEVICE_NOT_REGISTERED = 0;
	public static final int DEVICE_REGISTERED = 1;

	private Long id;
	private String code;
	private String serialNumber;
	private String name;
	private String deviceType;
	private Agent agent;
	private String msgNo;
	private String recptNo;
	private Boolean enabled;
	private Boolean deleted;
	private Integer isRegistered;
	private String lastUpdatedUsername;
	private Date modifiedTime;
	private String branchId;
	private String createdUsername;
	private Date createdDate;
	private String appVersion;
	private String loginTime;
	private String androidVer;
	private String mobileModel;
	private String updatedUser;
	private Date updatedDate;
	// Transient
	private String macAddress;
	private List<String> branchesList;
	private String filterStatus;
	private String deviceAddress;
	private String latitude;
	private String longitude;
	private String ipAddr;
	private ExporterRegistration exporter;

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "ID", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@Column(name = "CODE", length = 20)
	public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	@Column(name = "SERIAL_NUMBER", length = 35)
	public String getSerialNumber() {
		return this.serialNumber;
	}

	public void setSerialNumber(String serialNumber) {
		this.serialNumber = serialNumber;
	}

	@Column(name = "NAME", length = 20)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "DEVICE_TYPE", length = 10)
	public String getDeviceType() {
		return this.deviceType;
	}

	public void setDeviceType(String deviceType) {
		this.deviceType = deviceType;
	}

	@ManyToOne(fetch = FetchType.LAZY, cascade = CascadeType.ALL)
	@JoinColumn(name = "AGENT_ID", unique = true)
	public Agent getAgent() {
		return this.agent;
	}

	public void setAgent(Agent agent) {
		this.agent = agent;
	}

	@Column(name = "MSG_NUM", length = 45)
	public String getMsgNo() {
		return this.msgNo;
	}

	public void setMsgNo(String msgNo) {
		this.msgNo = msgNo;
	}

	@Column(name = "RECPT_NUM", length = 45)
	public String getRecptNo() {
		return this.recptNo;
	}

	public void setRecptNo(String recptNo) {
		this.recptNo = recptNo;
	}

	@Column(name = "ENABLED", columnDefinition = "TINYINT")
	@Type(type = "org.hibernate.type.NumericBooleanType")
	public Boolean getEnabled() {
		return this.enabled;
	}

	public void setEnabled(Boolean enabled) {
		this.enabled = enabled;
	}

	@Column(name = "IS_DELETED", columnDefinition = "TINYINT")
	@Type(type = "org.hibernate.type.NumericBooleanType")
	public Boolean getDeleted() {
		return this.deleted;
	}

	public void setDeleted(Boolean isDeleted) {
		this.deleted = isDeleted;
	}

	@Column(name = "IS_REGISTRED")
	public Integer getIsRegistered() {
		return isRegistered;
	}

	public void setIsRegistered(Integer isRegistered) {
		this.isRegistered = isRegistered;
	}

	@Column(name = "UPDATED_USERNAME", length = 45)
	public String getLastUpdatedUsername() {
		return this.lastUpdatedUsername;
	}

	public void setLastUpdatedUsername(String lastUpdatedUsername) {
		this.lastUpdatedUsername = lastUpdatedUsername;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "MODIFIED_TIME", length = 19)
	public Date getModifiedTime() {
		return this.modifiedTime;
	}

	public void setModifiedTime(Date modifiedTime) {
		this.modifiedTime = modifiedTime;
	}

	@Column(name = "BRANCH_ID", length = 50)
	public String getBranchId() {
		return this.branchId;
	}

	public void setBranchId(String branchId) {
		this.branchId = branchId;
	}

	@Column(name = "CREATED_USERNAME", length = 50)
	public String getCreatedUsername() {
		return this.createdUsername;
	}

	public void setCreatedUsername(String createdUsername) {
		this.createdUsername = createdUsername;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CREATED_DATE", length = 19)
	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	@Column(name = "APP_VERSION", length = 15)
	public String getAppVersion() {
		return this.appVersion;
	}

	public void setAppVersion(String appVersion) {
		this.appVersion = appVersion;
	}

	@Column(name = "LOGIN_TIME", length = 50)
	public String getLoginTime() {
		return this.loginTime;
	}

	public void setLoginTime(String loginTime) {
		this.loginTime = loginTime;
	}

	@Column(name = "ANDROID_VERSION", length = 15)
	public String getAndroidVer() {
		return this.androidVer;
	}

	public void setAndroidVer(String androidVer) {
		this.androidVer = androidVer;
	}

	@Column(name = "MOBILE_MODEL", length = 50)
	public String getMobileModel() {
		return this.mobileModel;
	}

	public void setMobileModel(String mobileModel) {
		this.mobileModel = mobileModel;
	}

	@Transient
	public String getMacAddress() {
		return macAddress;
	}

	public void setMacAddress(String macAddress) {
		this.macAddress = macAddress;
	}

	@Transient
	public List<String> getBranchesList() {
		return branchesList;
	}

	public void setBranchesList(List<String> branchesList) {
		this.branchesList = branchesList;
	}

	@Transient
	public String getFilterStatus() {
		return filterStatus;
	}

	public void setFilterStatus(String filterStatus) {
		this.filterStatus = filterStatus;
	}

	@Transient
	public String getDeviceAddress() {
		return deviceAddress;
	}

	public void setDeviceAddress(String deviceAddress) {
		this.deviceAddress = deviceAddress;
	}

	@Column(name = "UPDATED_USER", length = 50, columnDefinition = "VARCHAR(255)")
	public String getUpdatedUser() {
		return updatedUser;
	}

	public void setUpdatedUser(String updatedUser) {
		this.updatedUser = updatedUser;
	}
	
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "UPDATED_DATE", length = 19)
	@UpdateTimestamp
	public Date getUpdatedDate() {
		return updatedDate;
	}

	public void setUpdatedDate(Date updatedDate) {
		this.updatedDate = updatedDate;
	}
	
	@Column(name = "LAT", length = 50, columnDefinition = "VARCHAR(255)")
	public String getLatitude() {
		return latitude;
	}

	public void setLatitude(String latitude) {
		this.latitude = latitude;
	}
	@Column(name = "LON", length = 50, columnDefinition = "VARCHAR(255)")
	public String getLongitude() {
		return longitude;
	}
	
	
	public void setLongitude(String longitude) {
		this.longitude = longitude;
	}
	@Column(name = "IP_ADDR", length = 50, columnDefinition = "VARCHAR(255)")
	public String getIpAddr() {
		return ipAddr;
	}

	public void setIpAddr(String ipAddr) {
		this.ipAddr = ipAddr;
	}

	//@ManyToOne(fetch = FetchType.LAZY, cascade = CascadeType.ALL)
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "EXPORTER")
	public ExporterRegistration getExporter() {
		return exporter;
	}

	public void setExporter(ExporterRegistration exporter) {
		this.exporter = exporter;
	}

}
