package com.sourcetrace.eses.entity;
// Generated 23 Jun, 2020 5:09:17 PM by Hibernate Tools 5.0.6.Final

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Transient;

import org.hibernate.annotations.FilterDef;
import org.hibernate.annotations.Filters;
import org.hibernate.annotations.ParamDef;

/**
 * Distribution generated by hbm2java
 */
@Entity
 @FilterDef(name = "branchFilter", parameters = @ParamDef(name = "branchIdParam", type = "string"))@Filters(@org.hibernate.annotations.Filter(name="branchFilter", condition="branch_id in ( :branchIdParam )"))
@Table(name = "DISTRIBUTION")
public class Distribution implements java.io.Serializable {

	
	private static final long serialVersionUID = 1L;

	public static final String FARMER = "farmer";
	public static final String AGENT = "agent";

	public static final String DISTRIBUTION_AMOUNT = "DISTRIBUTION PAYMENT";
	public static final String PRODUCT_DISTRIBUTION_TO_FARMER_DESCRIPTION = "PRODUCT DISTRIBUTION TO FARMER";
	public static final String PRODUCT_DISTRIBUTION_TO_FIELDSTAFF_DESCRIPTION = "PRODUCT DISTRIBUTION TO FIELDSTAFF";
	public static final String PRODUCT_RETURN_FROM_FARMER_DESCRIPTION = "PRODUCT RETURN FROM FARMER";
	public static final String PRODUCT_RETURN_FROM_FIELDSTAFF_DESCRIPTION = "PRODUCT RETURN FROM FIELDSTAFF";
	public static final String DISTRIBUTION_PAYMENT_AMOUNT = "DISTRIBUTION PAYMENT AMOUNT";
	
	public static final String DISTRIBUTION_DELETE_FARMER = "DISTRIBUTION DELETE TO FARMER";
	
	public static final String DISTRIBUTION_DELETE_FIELDSTAFF = "DISTRIBUTION DELETE TO FIELDSTAFF";
	
	public static final int APPROVED=1;
	public static final String PRODUCT_DISTRIBUTION_TO_FARMER = "314";
	public static final String PRODUCT_RETURN_FROM_FARMER = "344";
	public static final String PRODUCT_DISTRIBUTION_TO_FIELDSTAFF = "514";
	public static final String PRODUCT_RETURN_FROM_FIELDSTAFF = "345";
	public static final int NOT_APPROVED=0;
	public static final int DELETE_STATUS=2;
	public static final String PRODUCT_DISTRIBUTION_FARMER_BALANCE = "395";
	
	private Long id;
	private String receiptNumber;
	private String referenceNo;
	private String serialNo;
	private Village village;
	private String villageName;
	private AgroTransaction agroTransaction;
	private String freeDistribution;
	private Double totalAmount;
	private Double tax;
	private Double finalAmount;
	private String paynmentMode;
	private SeasonMaster season;
	private Double paymentAmount;
	private String mobileNumber;
	private Double intBalance;
	private Double txnAmount;
	private Double balAmount;
	private String agentId;
	private String agentName;
	private String farmerId;
	private String farmerName;
	private String servicePointId;
	private String servicePointName;
	private Date txnTime;
	private String samithiName;
	private String txnType;
	private String branchId;
	private String seasonCode;
	private Integer status;
	private String updatedUserName;
	private Date updatedTime;
	private String warehouseCode;
	private String warehouseName;
	//private String samithiId;
	private String latitude;
	private String longitude;
	private Set<DistributionDetail> distributionDetails = new HashSet<DistributionDetail>(0);
	private Set<PmtImageDetails> pmtImageDetails = new HashSet<PmtImageDetails>(0);
	private String isFreeDistribution;
	private String productStock;
	
	//transient variables
	private String categoryName;
	private String productName;
	private String unit;
	private String distributionQuantity;
	private String seasonName;
	private String batchNo;
	private String currentQuantity;
	

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "ID", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@Column(name = "RECEIPT_NO", length = 45)
	public String getReceiptNumber() {
		return this.receiptNumber;
	}

	public void setReceiptNumber(String receiptNumber) {
		this.receiptNumber = receiptNumber;
	}

	@Column(name = "REFERENCE_NO", length = 20)
	public String getReferenceNo() {
		return this.referenceNo;
	}

	public void setReferenceNo(String referenceNo) {
		this.referenceNo = referenceNo;
	}

	@Column(name = "SERIAL_NO", length = 20)
	public String getSerialNo() {
		return this.serialNo;
	}

	public void setSerialNo(String serialNo) {
		this.serialNo = serialNo;
	}

	@ManyToOne(fetch=FetchType.LAZY)
	@JoinColumn(name = "VILLAGE_ID")
	public Village getVillage() {
		return this.village;
	}

	public void setVillage(Village village) {
		this.village = village;
	}

	@Column(name = "VILLAGE_NAME", length = 20)
	public String getVillageName() {
		return this.villageName;
	}

	public void setVillageName(String villageName) {
		this.villageName = villageName;
	}

	@ManyToOne(fetch=FetchType.LAZY)
	@JoinColumn(name = "TRXN_AGRO_ID")
	public AgroTransaction getAgroTransaction() {
		return this.agroTransaction;
	}

	public void setAgroTransaction(AgroTransaction agroTransaction) {
		this.agroTransaction = agroTransaction;
	}

	@Column(name = "IS_FREE_DISTRIBUTION", length = 2)
	public String getFreeDistribution() {
		return this.freeDistribution;
	}

	public void setFreeDistribution(String freeDistribution) {
		this.freeDistribution = freeDistribution;
	}

	@Column(name = "TOTAL_AMOUNT", precision = 20)
	public Double getTotalAmount() {
		return this.totalAmount;
	}

	public void setTotalAmount(Double totalAmount) {
		this.totalAmount = totalAmount;
	}

	@Column(name = "TAX", precision = 20)
	public Double getTax() {
		return this.tax;
	}

	public void setTax(Double tax) {
		this.tax = tax;
	}

	@Column(name = "FINAL_AMOUNT", precision = 20)
	public Double getFinalAmount() {
		return this.finalAmount;
	}

	public void setFinalAmount(Double finalAmount) {
		this.finalAmount = finalAmount;
	}

	@Column(name = "PAYNMENT_MODE", length = 20)
	public String getPaynmentMode() {
		return this.paynmentMode;
	}

	public void setPaynmentMode(String paynmentMode) {
		this.paynmentMode = paynmentMode;
	}

	@ManyToOne(fetch=FetchType.LAZY)
	@JoinColumn(name = "SEASON_ID")
	public SeasonMaster getSeason() {
		return this.season;
	}

	public void setSeason(SeasonMaster seasonId) {
		this.season = seasonId;
	}

	@Column(name = "PAYMENT_AMT", precision = 20)
	public Double getPaymentAmount() {
		return paymentAmount;
	}

	public void setPaymentAmount(Double paymentAmount) {
		this.paymentAmount = paymentAmount;
	}

	@Column(name = "MOBILE_NO", length = 20)
	public String getMobileNumber() {
		return this.mobileNumber;
	}

	public void setMobileNumber(String mobileNumber) {
		this.mobileNumber = mobileNumber;
	}

	@Column(name = "INT_BAL", precision = 20)
	public Double getIntBalance() {
		return this.intBalance;
	}

	public void setIntBalance(Double intBalance) {
		this.intBalance = intBalance;
	}

	@Column(name = "TXN_AMT", precision = 20)
	public Double getTxnAmt() {
		return this.txnAmount;
	}

	public void setTxnAmt(Double txnAmount) {
		this.txnAmount = txnAmount;
	}

	@Column(name = "BAL_AMT", precision = 20)
	public Double getBalAmount() {
		return this.balAmount;
	}

	public void setBalAmount(Double balAmount) {
		this.balAmount = balAmount;
	}

	@Column(name = "AGENT_ID", length = 20)
	public String getAgentId() {
		return this.agentId;
	}

	public void setAgentId(String agentId) {
		this.agentId = agentId;
	}

	@Column(name = "AGENT_NAME")
	public String getAgentName() {
		return this.agentName;
	}

	public void setAgentName(String agentName) {
		this.agentName = agentName;
	}

	@Column(name = "FARMER_ID", length = 20)
	public String getFarmerId() {
		return this.farmerId;
	}

	public void setFarmerId(String farmerId) {
		this.farmerId = farmerId;
	}

	@Column(name = "FARMER_NAME", length = 90)
	public String getFarmerName() {
		return this.farmerName;
	}

	public void setFarmerName(String farmerName) {
		this.farmerName = farmerName;
	}

	@Column(name = "SERVICE_POINT_ID", length = 20)
	public String getServicePointId() {
		return this.servicePointId;
	}

	public void setServicePointId(String servicePointId) {
		this.servicePointId = servicePointId;
	}

	@Column(name = "SERVICE_POINT_NAME", columnDefinition="LONGTEXT")
	public String getServicePointName() {
		return this.servicePointName;
	}

	public void setServicePointName(String servicePointName) {
		this.servicePointName = servicePointName;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "TXN_TIME", length = 19)
	public Date getTxnTime() {
		return this.txnTime;
	}

	public void setTxnTime(Date txnTime) {
		this.txnTime = txnTime;
	}

	@Column(name = "SAMITHI_NAME", length = 45)
	public String getSamithiName() {
		return this.samithiName;
	}

	public void setSamithiName(String samithiName) {
		this.samithiName = samithiName;
	}

	@Column(name = "TXN_TYPE", length = 20)
	public String getTxnType() {
		return this.txnType;
	}

	public void setTxnType(String txnType) {
		this.txnType = txnType;
	}

	@Column(name = "branch_id", length = 50)
	public String getBranchId() {
		return this.branchId;
	}

	public void setBranchId(String branchId) {
		this.branchId = branchId;
	}

	@Column(name = "season_code", length = 50)
	public String getSeasonCode() {
		return this.seasonCode;
	}

	public void setSeasonCode(String seasonCode) {
		this.seasonCode = seasonCode;
	}

	@Column(name = "STATUS")
	public Integer getStatus() {
		return this.status;
	}

	public void setStatus(Integer status) {
		this.status = status;
	}

	@Column(name = "UPDATED_USER_NAME", length = 45)
	public String getUpdatedUserName() {
		return this.updatedUserName;
	}

	public void setUpdatedUserName(String updatedUserName) {
		this.updatedUserName = updatedUserName;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "UPDATED_TIME", length = 19)
	public Date getUpdatedTime() {
		return this.updatedTime;
	}

	public void setUpdatedTime(Date updatedTime) {
		this.updatedTime = updatedTime;
	}

	@Column(name = "WAREHOUSE_CODE", length = 20)
	public String getWarehouseCode() {
		return this.warehouseCode;
	}

	public void setWarehouseCode(String warehouseCode) {
		this.warehouseCode = warehouseCode;
	}

	@Column(name = "WAREHOUSE_NAME", columnDefinition="LONGTEXT")
	public String getWarehouseName() {
		return this.warehouseName;
	}

	public void setWarehouseName(String warehouseName) {
		this.warehouseName = warehouseName;
	}

	

	@Column(name = "LATITUDE", length = 50)
	public String getLatitude() {
		return this.latitude;
	}

	public void setLatitude(String latitude) {
		this.latitude = latitude;
	}

	@Column(name = "LONGITUDE", length = 50)
	public String getLongitude() {
		return this.longitude;
	}

	public void setLongitude(String longitude) {
		this.longitude = longitude;
	}

	@OneToMany( mappedBy = "distribution")
	public Set<DistributionDetail> getDistributionDetails() {
		return this.distributionDetails;
	}

	public void setDistributionDetails(Set<DistributionDetail> distributionDetails) {
		this.distributionDetails = distributionDetails;
	}

	@OneToMany( mappedBy = "pmtId",cascade=CascadeType.ALL)
	public Set<PmtImageDetails> getPmtImageDetails() {
		return this.pmtImageDetails;
	}

	public void setPmtImageDetails(Set<PmtImageDetails> pmtImageDetails) {
		this.pmtImageDetails = pmtImageDetails;
	}

	@Transient
	public Double getTxnAmount() {
		return txnAmount;
	}

	public void setTxnAmount(Double txnAmount) {
		this.txnAmount = txnAmount;
	}

	@Transient
	public String getIsFreeDistribution() {
		return isFreeDistribution;
	}

	public void setIsFreeDistribution(String isFreeDistribution) {
		this.isFreeDistribution = isFreeDistribution;
	}
	
	@Transient
	public boolean isPaymentAvailable() {

		return this.paymentAmount != null ? (this.paymentAmount > 0d) : false;
	}
     @Transient
	public String getProductStock() {
		return productStock;
	}

	public void setProductStock(String productStock) {
		this.productStock = productStock;
	}

	@Transient
	public String getCategoryName() {
		return categoryName;
	}

	public void setCategoryName(String categoryName) {
		this.categoryName = categoryName;
	}

	@Transient
	public String getProductName() {
		return productName;
	}

	public void setProductName(String productName) {
		this.productName = productName;
	}
	@Transient
	public String getUnit() {
		return unit;
	}

	public void setUnit(String unit) {
		this.unit = unit;
	}
	
	@Transient
	public String getSeasonName() {
		return seasonName;
	}

	public void setSeasonName(String seasonName) {
		this.seasonName = seasonName;
	}
	@Transient
	public String getBatchNo() {
		return batchNo;
	}

	public void setBatchNo(String batchNo) {
		this.batchNo = batchNo;
	}

	@Transient
	public String getCurrentQuantity() {
		return currentQuantity;
	}

	public void setCurrentQuantity(String currentQuantity) {
		this.currentQuantity = currentQuantity;
	}

	@Transient
	public String getDistributionQuantity() {
		return distributionQuantity;
	}

	public void setDistributionQuantity(String distributionQuantity) {
		this.distributionQuantity = distributionQuantity;
	}
	
	
}
