package com.sourcetrace.eses.entity;
// Generated 23 Jun, 2020 5:09:17 PM by Hibernate Tools 5.0.6.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import org.hibernate.annotations.Type;

/**
 * DynamicReportConfigDetail generated by hbm2java
 */
@Entity

@Table(name = "DYNAMIC_REPORT_CONFIG_DETAIL")
public class DynamicReportConfigDetail implements Comparable<DynamicReportConfigDetail> {

	private Long id;
	private DynamicReportConfig dynamicReportConfig;
	private String labelName;
	private String field;
	private Integer acessType;
	private String paramters;
	private String method;
	private Long groupProp;
	private Long sumProp;
	private Double width;
	private Integer order;
	private Boolean isGridAvailability;
	private Boolean isExportAvailability;
	private Long status;
	private String expression;
	private String alignment;
	private Integer isFooterSum;
	private String isGroupHeader;
	private String dataType;
	private String sortField;
	
	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "ID", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@ManyToOne(fetch=FetchType.LAZY)
	@JoinColumn(name = "REPORT_CONFIG_ID")
	public DynamicReportConfig getDynamicReportConfig() {
		return this.dynamicReportConfig;
	}

	public void setDynamicReportConfig(DynamicReportConfig dynamicReportConfig) {
		this.dynamicReportConfig = dynamicReportConfig;
	}

	@Column(name = "LABEL_NAME")
	public String getLabelName() {
		return this.labelName;
	}

	public void setLabelName(String labelName) {
		this.labelName = labelName;
	}

	@Column(name = "FIELD", length = 200)
	public String getField() {
		return this.field;
	}

	public void setField(String field) {
		this.field = field;
	}

	@Column(name = "ACESS_TYPE")
	public Integer getAcessType() {
		return this.acessType;
	}

	public void setAcessType(Integer acessType) {
		this.acessType = acessType;
	}

	@Column(name = "PARAMTERS", length = 150)
	public String getParamters() {
		return this.paramters;
	}

	public void setParamters(String paramters) {
		this.paramters = paramters;
	}

	@Column(name = "METHOD")
	public String getMethod() {
		return this.method;
	}

	public void setMethod(String method) {
		this.method = method;
	}

	@Column(name = "GROUP_PROP")
	public Long getGroupProp() {
		return this.groupProp;
	}

	public void setGroupProp(Long groupProp) {
		this.groupProp = groupProp;
	}

	@Column(name = "SUM_PROP")
	public Long getSumProp() {
		return this.sumProp;
	}

	public void setSumProp(Long sumProp) {
		this.sumProp = sumProp;
	}

	@Column(name = "WIDTH", precision = 5, scale = 0)
	public Double getWidth() {
		return this.width;
	}

	public void setWidth(Double width) {
		this.width = width;
	}

	@Column(name = "ORDERR")
	public Integer getOrder() {
		return this.order;
	}

	public void setOrder(Integer orderr) {
		this.order = orderr;
	}

	@Column(name = "IS_GRID_AVAILABILITY",columnDefinition= "TINYINT")
	@Type(type = "org.hibernate.type.NumericBooleanType")
	public Boolean getIsGridAvailability() {
		return this.isGridAvailability;
	}

	public void setIsGridAvailability(Boolean isGridAvailability) {
		this.isGridAvailability = isGridAvailability;
	}

	@Column(name = "IS_EXPORT_AVAILABILITY",columnDefinition= "TINYINT")
	@Type(type = "org.hibernate.type.NumericBooleanType")
	public Boolean getIsExportAvailability() {
		return this.isExportAvailability;
	}

	public void setIsExportAvailability(Boolean isExportAvailability) {
		this.isExportAvailability = isExportAvailability;
	}

	@Column(name = "STATUSS")
	public Long getStatus() {
		return this.status;
	}

	public void setStatus(Long status) {
		this.status = status;
	}

	@Column(name = "EXPRESSION")
	public String getExpression() {
		return this.expression;
	}

	public void setExpression(String expression) {
		this.expression = expression;
	}

	@Column(name = "ALIGNMENT")
	public String getAlignment() {
		return this.alignment;
	}

	public void setAlignment(String alignment) {
		this.alignment = alignment;
	}

	@Column(name = "IS_FOOTER_SUM")
	public Integer getIsFooterSum() {
		return this.isFooterSum;
	}

	public void setIsFooterSum(Integer isFooterSum) {
		this.isFooterSum = isFooterSum;
	}

	@Column(name = "IS_GROUP_HEADER")
	public String getIsGroupHeader() {
		return this.isGroupHeader;
	}

	public void setIsGroupHeader(String isGroupHeader) {
		this.isGroupHeader = isGroupHeader;
	}

	@Column(name = "DATA_TYPE", length = 10)
	public String getDataType() {
		return this.dataType;
	}

	public void setDataType(String dataType) {
		this.dataType = dataType;
	}

	@Override
	public int compareTo(DynamicReportConfigDetail o) {
		// TODO Auto-generated method stub
		return this.order==null ? 0 : this.order.compareTo(o.getOrder());
	}

	@Column(name = "SORT_FIELD")
	public String getSortField() {
		return sortField;
	}

	public void setSortField(String sortField) {
		this.sortField = sortField;
	}
}
