package com.sourcetrace.eses.entity;
// Generated 23 Jun, 2020 5:09:17 PM by Hibernate Tools 5.0.6.Final

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Map;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Transient;

/**
 * DynamicReportConfigFilter generated by hbm2java
 */
@Entity
@Table(name = "DYNAMIC_REPORT_CONFIG_FILTER")
public class DynamicReportConfigFilter  implements Comparable<DynamicReportConfigFilter> {

	private Long id;
	private DynamicReportConfig dynamicReportConfig;
	private String field;
	private String label;
	private String method;
	private Integer status;
	private Integer order;
	private Integer Type;
	private Integer isDateFilter;
	private String defaultFilter;
	private DynamicReportConfigDetail detailId;
	@Transient
	private Map<String,String> options;
	public DynamicReportConfigFilter() {
	}

	public DynamicReportConfigFilter(DynamicReportConfig dynamicReportConfig, String field, String label, String method,
			Integer status, Integer order, Integer Type, Integer isDateFilter, String defaultFilter) {
		this.dynamicReportConfig = dynamicReportConfig;
		this.field = field;
		this.label = label;
		this.method = method;
		this.status = status;
		this.order = order;
		this.Type = Type;
		this.isDateFilter = isDateFilter;
		this.defaultFilter = defaultFilter;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "ID", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "REPORT_CONFIG")
	public DynamicReportConfig getDynamicReportConfig() {
		return this.dynamicReportConfig;
	}

	public void setDynamicReportConfig(DynamicReportConfig dynamicReportConfig) {
		this.dynamicReportConfig = dynamicReportConfig;
	}

	@Column(name = "FIELD", length = 100)
	public String getField() {
		return this.field;
	}

	public void setField(String field) {
		this.field = field;
	}

	@Column(name = "LABEL")
	public String getLabel() {
		return this.label;
	}

	public void setLabel(String label) {
		this.label = label;
	}

	@Column(name = "METHOD")
	public String getMethod() {
		return this.method;
	}

	public void setMethod(String method) {
		this.method = method;
	}

	@Column(name = "STATUS")
	public Integer getStatus() {
		return this.status;
	}

	public void setStatus(Integer status) {
		this.status = status;
	}

	@Column(name = "ORDERR")
	public Integer getOrder() {
		return this.order;
	}

	public void setOrder(Integer order) {
		this.order = order;
	}

	@Column(name = "TYPE")
	public Integer getType() {
		return this.Type;
	}

	public void setType(Integer Type) {
		this.Type = Type;
	}

	@Column(name = "IS_DATE_FILTER")
	public Integer getIsDateFilter() {
		return this.isDateFilter;
	}

	public void setIsDateFilter(Integer isDateFilter) {
		this.isDateFilter = isDateFilter;
	}

	@Column(name = "DEFAULT_FILTER")
	public String getDefaultFilter() {
		return this.defaultFilter;
	}

	public void setDefaultFilter(String defaultFilter) {
		this.defaultFilter = defaultFilter;
	}
	@Transient
	public Map<String, String> getOptions() {
		return options;
	}

	public void setOptions(Map<String, String> options) {
		this.options = options;
	}
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CONFIG_DETAIL_ID")
	public DynamicReportConfigDetail getDetailId() {
		return this.detailId;
	}

	public void setDetailId(DynamicReportConfigDetail detailId) {
		this.detailId = detailId;
	}
	@Override
	public int compareTo(DynamicReportConfigFilter o) {
		// TODO Auto-generated method stub
		return this.order==null ? 0 : this.order.compareTo(o.getOrder());
	}

}
