package com.sourcetrace.eses.entity;
// Generated 23 Jun, 2020 5:09:17 PM by Hibernate Tools 5.0.6.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * DynamicConstants generated by hbm2java
 */
@Entity
 @Table(name = "dynamic_constants")
public class DynamicConstants implements java.io.Serializable {

	private long id;
	private String code;
	private String name;
	private String fieldName;
	private String dataType;
	private String mcode;

	public DynamicConstants() {
	}

	public DynamicConstants(long id) {
		this.id = id;
	}

	public DynamicConstants(long id, String code, String name, String fieldName, String dataType, String mcode) {
		this.id = id;
		this.code = code;
		this.name = name;
		this.fieldName = fieldName;
		this.dataType = dataType;
		this.mcode = mcode;
	}

	@Id

	@Column(name = "ID", unique = true, nullable = false)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@Column(name = "CODE", length = 45)
	public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	@Column(name = "NAME", length = 100)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "FIELD_NAME", length = 100)
	public String getFieldName() {
		return this.fieldName;
	}

	public void setFieldName(String fieldName) {
		this.fieldName = fieldName;
	}

	@Column(name = "DATA_TYPE", length = 10)
	public String getDataType() {
		return this.dataType;
	}

	public void setDataType(String dataType) {
		this.dataType = dataType;
	}

	@Column(name = "MCODE", length = 100)
	public String getMcode() {
		return this.mcode;
	}

	public void setMcode(String mcode) {
		this.mcode = mcode;
	}

}
