package com.sourcetrace.eses.entity;
// Generated 23 Jun, 2020 5:09:17 PM by Hibernate Tools 5.0.6.Final

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * DynamicReportTableConfig generated by hbm2java
 */
@Entity
@Table(name = "DYNAMIC_REPORT_TABLE_CONFIG")
public class DynamicReportTableConfig implements java.io.Serializable {

	private Integer id;
	private String entityName;
	private String table;
	private String alias;
	private Integer parent;
	private String joinString;
	private String entityQuery;
	private Set<DynamicReportFieldsConfig> dynamicReportFieldsConfig =new HashSet<DynamicReportFieldsConfig>();

	public DynamicReportTableConfig() {
	}

	public DynamicReportTableConfig(String entityName, String table, String alias, Integer parent, String joinString,
			String entityQuery, Integer entity,Set<DynamicReportFieldsConfig> dynamicReportFieldsConfig ) {
		this.entityName = entityName;
		this.table = table;
		this.alias = alias;
		this.parent = parent;
		this.joinString = joinString;
		this.entityQuery = entityQuery;
		this.dynamicReportFieldsConfig=dynamicReportFieldsConfig;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "EntityName")
	public String getEntityName() {
		return this.entityName;
	}

	public void setEntityName(String entityName) {
		this.entityName = entityName;
	}

	@Column(name = "TABLE_ID")
	public String getTable() {
		return this.table;
	}

	public void setTable(String table) {
		this.table = table;
	}

	@Column(name = "Alias")
	public String getAlias() {
		return this.alias;
	}

	public void setAlias(String alias) {
		this.alias = alias;
	}

	@Column(name = "Parent")
	public Integer getParent() {
		return this.parent;
	}

	public void setParent(Integer parent) {
		this.parent = parent;
	}

	@Column(name = "JoinString")
	public String getJoinString() {
		return this.joinString;
	}

	public void setJoinString(String joinString) {
		this.joinString = joinString;
	}

	@Column(name = "EntityQuery", length = 500)
	public String getEntityQuery() {
		return this.entityQuery;
	}

	public void setEntityQuery(String entityQuery) {
		this.entityQuery = entityQuery;
	}

	@OneToMany(cascade=CascadeType.ALL, mappedBy = "dynamicReportTable")
	public Set<DynamicReportFieldsConfig> getDynamicReportFieldsConfig() {
		return dynamicReportFieldsConfig;
	}

	public void setDynamicReportFieldsConfig(Set<DynamicReportFieldsConfig> dynamicReportFieldsConfig) {
		this.dynamicReportFieldsConfig = dynamicReportFieldsConfig;
	}

	

}
