package com.sourcetrace.eses.entity;
// Generated 23 Jun, 2020 5:09:17 PM by Hibernate Tools 5.0.6.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * EseTxnHeader generated by hbm2java
 */
@Entity
@Table(name = "ese_txn_header")
public class ESETxnHeader implements java.io.Serializable {

	private Long id;
	private ESETxnType eseTxnType;
	private String serialNo;
	private String deviceId;
	private String deviceName;
	private String deviceType;
	private String agentId;
	private String agentName;
	private String servicePointId;
	private String servicePointName;
	private String msgNo;
	private String batchNo;
	private String mode;
	private String branchId;
	private String tenantId;
	private Set<ESETxn> eseTxns = new HashSet<ESETxn>(0);

	
	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "ID", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ESE_TXN_TYPE_ID")
	public ESETxnType getEseTxnType() {
		return this.eseTxnType;
	}

	public void setEseTxnType(ESETxnType eseTxnType) {
		this.eseTxnType = eseTxnType;
	}

	@Column(name = "SERIAL_NO",  length = 45)
	public String getSerialNo() {
		return this.serialNo;
	}

	public void setSerialNo(String serialNo) {
		this.serialNo = serialNo;
	}

	@Column(name = "DEVICE_ID", length = 45)
	public String getDeviceId() {
		return this.deviceId;
	}

	public void setDeviceId(String deviceId) {
		this.deviceId = deviceId;
	}

	@Column(name = "DEVICE_NAME", length = 45)
	public String getDeviceName() {
		return this.deviceName;
	}

	public void setDeviceName(String deviceName) {
		this.deviceName = deviceName;
	}

	@Column(name = "DEVICE_TYPE", length = 10)
	public String getDeviceType() {
		return this.deviceType;
	}

	public void setDeviceType(String deviceType) {
		this.deviceType = deviceType;
	}

	@Column(name = "AGENT_ID",  length = 45)
	public String getAgentId() {
		return this.agentId;
	}

	public void setAgentId(String agentId) {
		this.agentId = agentId;
	}

	@Column(name = "AGENT_NAME")
	public String getAgentName() {
		return this.agentName;
	}

	public void setAgentName(String agentName) {
		this.agentName = agentName;
	}

	@Column(name = "SERVICE_POINT_ID",  length = 45)
	public String getServicePointId() {
		return this.servicePointId;
	}

	public void setServicePointId(String servicePointId) {
		this.servicePointId = servicePointId;
	}

	@Column(name = "SERVICE_POINT_NAME", length = 45)
	public String getServicePointName() {
		return this.servicePointName;
	}

	public void setServicePointName(String servicePointName) {
		this.servicePointName = servicePointName;
	}

	@Column(name = "MSG_NO", nullable = false)
	public String getMsgNo() {
		return this.msgNo;
	}

	public void setMsgNo(String msgNo) {
		this.msgNo = msgNo;
	}

	@Column(name = "BATCH_NO",  length = 45)
	public String getBatchNo() {
		return this.batchNo;
	}

	public void setBatchNo(String batchNo) {
		this.batchNo = batchNo;
	}

	@Column(name = "MODE",  length = 10)
	public String getMode() {
		return this.mode;
	}

	public void setMode(String mode) {
		this.mode = mode;
	}

	@Column(name = "BRANCH_ID", length = 50)
	public String getBranchId() {
		return this.branchId;
	}

	public void setBranchId(String branchId) {
		this.branchId = branchId;
	}

	@Column(name = "TENANT_ID", length = 20)
	public String getTenantId() {
		return this.tenantId;
	}

	public void setTenantId(String tenantId) {
		this.tenantId = tenantId;
	}

	@OneToMany( mappedBy = "eseTxnHeader")
	public Set<ESETxn> getEseTxns() {
		return this.eseTxns;
	}

	public void setEseTxns(Set<ESETxn> eseTxns) {
		this.eseTxns = eseTxns;
	}

}
