package com.sourcetrace.eses.entity;
// Generated 23 Jun, 2020 5:09:17 PM by Hibernate Tools 5.0.6.Final

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;
import java.util.LinkedList;
import java.util.List;
import java.util.Map;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Transient;

import org.hibernate.annotations.FilterDef;
import org.hibernate.annotations.Filters;
import org.hibernate.annotations.ParamDef;

/**
 * FarmerDynamicData generated by hbm2java
 */
@Entity
@FilterDef(name = "branchFilter", parameters = @ParamDef(name = "branchIdParam", type = "string"))@Filters(@org.hibernate.annotations.Filter(name="branchFilter", condition="branch_id in ( :branchIdParam )"))
@Table(name = "farmer_dynamic_data")
public class FarmerDynamicData implements java.io.Serializable {

	private Long id;
	private Long txnUniqueId;
	private String referenceId;
	private String farmerId;
	private String txnType;
	private Date date;
	private String latitude;
	private String longitude;
	private Date createdDate;
	private String createdUser;
	private String entityId;
	private String conversionStatus;
	private String correctiveActionPlan;
	private String icsName;
	private String status;
	private String season;
	private String branchId;
	private Integer isSingleRecord;
	private String farmIcsConvId;
	private Date updatedDate;
	private String updatedUser;
	private Double totalScore;
	private Long isScore;
	private Date followUpdate;
	private String followAgent;
	private Long revisionNo;
	private String branch;
	private Integer actStatus;

	private Set<FarmerDynamicFieldsValue> farmerDynamicFieldsValues;

	@Transient
	private transient Map<String, Map<String, String>> scoreValue;
	@Transient
	private List<String> branchesList;
	@Transient
	private DynamicImageData digitalSignature;
	@Transient
	private DynamicImageData agentSignature;
	@Transient
	private long farmerDynamicFieldValueId;
	@Transient
	private Map<String, Object> profileUpdateFields;
	@Transient
	private Map<String, String> filterData;
	@Transient
	private String digSignByteString;
	@Transient
	private Set<DynamicImageData> dymamicImageData;
	@Transient
	private String inspectionStatus;
	@Transient
	private Integer isSeason;
	@Transient
	private LinkedList<String> reportValues;

	
	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "ID", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@Column(name = "TXN_UNIQUE_ID", length = 45)
	public Long getTxnUniqueId() {
		return this.txnUniqueId;
	}

	public void setTxnUniqueId(Long txnUniqueId) {
		this.txnUniqueId = txnUniqueId;
	}

	@Column(name = "REFERENCE_ID", length = 45)
	public String getReferenceId() {
		return this.referenceId;
	}

	public void setReferenceId(String referenceId) {
		this.referenceId = referenceId;
	}

	@Column(name = "FARMER_ID", length = 45)
	public String getFarmerId() {
		return this.farmerId;
	}

	public void setFarmerId(String farmerId) {
		this.farmerId = farmerId;
	}

	@Column(name = "TXN_TYPE", length = 45)
	public String getTxnType() {
		return this.txnType;
	}

	public void setTxnType(String txnType) {
		this.txnType = txnType;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DATE", length = 19)
	public Date getDate() {
		return this.date;
	}

	public void setDate(Date date) {
		this.date = date;
	}

	@Column(name = "LATITUDE", length = 45)
	public String getLatitude() {
		return this.latitude;
	}

	public void setLatitude(String latitude) {
		this.latitude = latitude;
	}

	@Column(name = "LONGITUDE", length = 45)
	public String getLongitude() {
		return this.longitude;
	}

	public void setLongitude(String longitude) {
		this.longitude = longitude;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "CREATED_DATE", length = 10)
	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	@Column(name = "CREATED_USER", length = 45)
	public String getCreatedUser() {
		return this.createdUser;
	}

	public void setCreatedUser(String createdUser) {
		this.createdUser = createdUser;
	}

	@Column(name = "ENTITY_ID", length = 45)
	public String getEntityId() {
		return this.entityId;
	}

	public void setEntityId(String entityId) {
		this.entityId = entityId;
	}

	@Column(name = "CONVERSION_STATUS", length = 45)
	public String getConversionStatus() {
		return this.conversionStatus;
	}

	public void setConversionStatus(String conversionStatus) {
		this.conversionStatus = conversionStatus;
	}

	@Column(name = "CORRECTIVE_ACTION_PLAN")
	public String getCorrectiveActionPlan() {
		return this.correctiveActionPlan;
	}

	public void setCorrectiveActionPlan(String correctiveActionPlan) {
		this.correctiveActionPlan = correctiveActionPlan;
	}

	@Column(name = "ICS_NAME", length = 45)
	public String getIcsName() {
		return this.icsName;
	}

	public void setIcsName(String icsName) {
		this.icsName = icsName;
	}

	@Column(name = "STATUS", length = 45)
	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	@Column(name = "SEASON", length = 20)
	public String getSeason() {
		return this.season;
	}

	public void setSeason(String season) {
		this.season = season;
	}

	@Column(name = "BRANCH_ID", length = 20)
	public String getBranchId() {
		return this.branchId;
	}

	public void setBranchId(String branchId) {
		this.branchId = branchId;
	}

	@Column(name = "IS_SINGLE_RECORD", length = 20)
	public Integer getIsSingleRecord() {
		return this.isSingleRecord;
	}

	public void setIsSingleRecord(Integer isSingleRecord) {
		this.isSingleRecord = isSingleRecord;
	}

	@Column(name = "FARM_ICS_CONV_ID", length = 45)
	public String getFarmIcsConvId() {
		return this.farmIcsConvId;
	}

	public void setFarmIcsConvId(String farmIcsConvId) {
		this.farmIcsConvId = farmIcsConvId;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "UPDATED_DATE", length = 10)
	public Date getUpdatedDate() {
		return this.updatedDate;
	}

	public void setUpdatedDate(Date updatedDate) {
		this.updatedDate = updatedDate;
	}

	@Column(name = "UPDATED_USER", length = 45)
	public String getUpdatedUser() {
		return this.updatedUser;
	}

	public void setUpdatedUser(String updatedUser) {
		this.updatedUser = updatedUser;
	}

	@Column(name = "TOTAL_SCORE", precision = 4)
	public Double getTotalScore() {
		return this.totalScore;
	}

	public void setTotalScore(Double totalScore) {
		this.totalScore = totalScore;
	}

	@Column(name = "is_score")
	public Long getIsScore() {
		return this.isScore;
	}

	public void setIsScore(Long isScore) {
		this.isScore = isScore;
	}


	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "FOLLOW_UPDATE", length = 19)
	public Date getFollowUpdate() {
		return this.followUpdate;
	}

	public void setFollowUpdate(Date followUpdate) {
		this.followUpdate = followUpdate;
	}

	@Column(name = "FOLLOW_AGENT", length = 45)
	public String getFollowAgent() {
		return this.followAgent;
	}

	public void setFollowAgent(String followAgent) {
		this.followAgent = followAgent;
	}

	@Column(name = "REVISION_NO")
	public Long getRevisionNo() {
		return this.revisionNo;
	}

	public void setRevisionNo(Long revisionNo) {
		this.revisionNo = revisionNo;
	}

	@OneToMany(mappedBy = "farmerDynamicData")
	public Set<FarmerDynamicFieldsValue> getFarmerDynamicFieldsValues() {
		return farmerDynamicFieldsValues;
	}

	public void setFarmerDynamicFieldsValues(Set<FarmerDynamicFieldsValue> farmerDynamicFieldsValues) {
		this.farmerDynamicFieldsValues = farmerDynamicFieldsValues;
	}
	@Transient
	public Map<String, Map<String, String>> getScoreValue() {
		return scoreValue;
	}

	public void setScoreValue(Map<String, Map<String, String>> scoreValue) {
		this.scoreValue = scoreValue;
	}

	@Transient
	public Map<String, Object> getProfileUpdateFields() {
		return profileUpdateFields;
	}

	public void setProfileUpdateFields(Map<String, Object> profileUpdateFields) {
		this.profileUpdateFields = profileUpdateFields;
	}
	@Transient
	public long getFarmerDynamicFieldValueId() {
		return farmerDynamicFieldValueId;
	}

	public void setFarmerDynamicFieldValueId(long farmerDynamicFieldValueId) {
		this.farmerDynamicFieldValueId = farmerDynamicFieldValueId;
	}

	@OneToMany(mappedBy = "farmerDynamicData")
	public Set<DynamicImageData> getDymamicImageData() {
		return dymamicImageData;
	}

	public void setDymamicImageData(Set<DynamicImageData> dymamicImageData) {
		this.dymamicImageData = dymamicImageData;
	}
	
	public String getDigSignByteString() {
		return digSignByteString;
	}

	public void setDigSignByteString(String digSignByteString) {
		this.digSignByteString = digSignByteString;
	}
	public String getBranch() {
		return branch;
	}

	public void setBranch(String branch) {
		this.branch = branch;
	}
	
	public Integer getActStatus() {
		return actStatus;
	}

	public void setActStatus(Integer actStatus) {
		this.actStatus = actStatus;
	}





}
