package com.sourcetrace.eses.entity;
// Generated 23 Jun, 2020 5:09:17 PM by Hibernate Tools 5.0.6.Final

import static javax.persistence.GenerationType.IDENTITY;

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.OneToMany;
import javax.persistence.OrderBy;
import javax.persistence.Table;
import javax.persistence.Transient;

import org.hibernate.annotations.ManyToAny;
import org.hibernate.annotations.Type;

/**
 * Menu generated by hbm2java
 */
@Entity
@Table(name = "ese_menu")
public class Menu implements java.io.Serializable {
	
	 public static enum PRIORITIES {
	        OLD, NEW
	    };
     public static final int DIMENSION_VERTICAL = 0;
	 public static final int DIMENSION_HORIZONTAL = 1;

	    
	   

	private Long id;
	private Long parentId;
	private String label;
	private String des;
	
	private String url;
	private Integer order;
	//private Integer filter;
	private Integer exportAvilability;
	private Integer dimension;
	private int priority;
	private String iconClass;
	private boolean dataFiltered;
	private Set<Menu> subMenus = new HashSet<Menu>(0);
	private Set<Action> actions=new HashSet<Action>(0);
	//private Set<ESEAction> eseMenuActions = new HashSet<ESEAction>(0);
	
	// Transient variable to set entitlement name as icon class name
    private String menuClassName;

    @Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "ID", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	
	@Column(name = "PARENT_ID", length = 45)
	public Long getParentId() {
		return parentId;
	}

	public void setParentId(Long parentId) {
		this.parentId = parentId;
	}

	@Column(name = "NAME", length = 45)
	public String getLabel() {
		return this.label;
	}

	public void setLabel(String name) {
		this.label = name;
	}

	@Column(name = "DES", length = 45)
	public String getDes() {
		return this.des;
	}

	public void setDes(String des) {
		this.des = des;
	}

	@Column(name = "URL", length = 100)
	public String getUrl() {
		return this.url;
	}

	public void setUrl(String url) {
		this.url = url;
	}

	@Column(name = "ORD")
	public Integer getOrder() {
		return this.order;
	}

	public void setOrder(Integer order) {
		this.order = order;
	}

	/*@Column(name = "FILTER")
	public Integer getFilter() {
		return this.filter;
	}

	public void setFilter(Integer filter) {
		this.filter = filter;
	}*/

	@Column(name = "EXPORT_AVILABILITY")
	public Integer getExportAvilability() {
		return this.exportAvilability;
	}

	public void setExportAvilability(Integer exportAvilability) {
		this.exportAvilability = exportAvilability;
	}

	@Column(name = "DIMENSION")
	public Integer getDimension() {
		return this.dimension;
	}

	public void setDimension(Integer dimension) {
		this.dimension = dimension;
	}

	@Column(name = "PRIORITY", nullable = false)
	public int getPriority() {
		return this.priority;
	}

	public void setPriority(int priority) {
		this.priority = priority;
	}

	@Column(name = "ICON_CLASS", length = 20)
	public String getIconClass() {
		return this.iconClass;
	}

	public void setIconClass(String iconClass) {
		this.iconClass = iconClass;
	}

	@OneToMany(fetch = FetchType.LAZY)
	@JoinColumn(name = "PARENT_ID")
	@OrderBy("order")
	public Set<Menu> getSubMenus() {
		return subMenus;
	}

	public void setSubMenus(Set<Menu> subMenus) {
		this.subMenus = subMenus;
	}
	
	@Column(name = "FILTER",columnDefinition= "TINYINT")
	@Type(type = "org.hibernate.type.NumericBooleanType")
	public boolean isDataFiltered() {
		return dataFiltered;
	}

	public void setDataFiltered(boolean dataFiltered) {
		this.dataFiltered = dataFiltered;
	}
	
	
	 public void setMenuClassName(String menuClassName) {
	        this.menuClassName = menuClassName;
	    }
		@Transient
	public String getMenuClassName() {
		return menuClassName;
	}
@Transient
	  public boolean isVerticalDimension() {

	        return (dimension == DIMENSION_VERTICAL);
	    }

public void setName(String name) {

    setLabel(name);
}

public String getName() {

    return getLabel();
}

@Override
public String toString() {

    return label;
}


@OneToMany(fetch = FetchType.LAZY)
@JoinTable(name = "ese_menu_action", joinColumns = {
		@JoinColumn(name = "MENU_ID",  updatable = false) }, inverseJoinColumns = {
				@JoinColumn(name = "ACTION_ID",  updatable = false) })
public Set<Action> getActions() {
	return actions;
}

public void setActions(Set<Action> actions) {
	this.actions = actions;
}

}
