package com.sourcetrace.eses.entity;

import static javax.persistence.GenerationType.IDENTITY;

import java.util.HashSet;
import java.util.List;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Transient;

import org.hibernate.annotations.FilterDef;
import org.hibernate.annotations.Filters;
import org.hibernate.annotations.ParamDef;

import com.fasterxml.jackson.annotation.JsonIgnore;
import org.hibernate.envers.*;

/**
 * City generated by hbm2java
 */
@Entity
 @FilterDef(name = "branchFilter", parameters = @ParamDef(name = "branchIdParam", type = "string"))@Filters(@org.hibernate.annotations.Filter(name="branchFilter", condition="branch_id in ( :branchIdParam )"))
@Table(name = "CITY")
@Audited
public class Municipality implements java.io.Serializable {

	private Long id;
	
	private String name;
	private String code;
	private String latitude;
	private String longitude;
	private String postalCode;
	private Long revisionNo;
	private String branchId;
	private Locality locality;
	private Set<GramPanchayat> gramPanchayats;
	private Set<Village> villages;
	
	/**
	 * Transient variable
	 */
	private List<String> branchesList;
	private String stateName;
	private String countryName;
	
	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "ID", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	

	@Column(name = "NAME", nullable = false, length = 100)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "CODE", nullable = false, length = 20)
	public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	@Column(name = "LATITUDE", length = 45)
	public String getLatitude() {
		return this.latitude;
	}

	public void setLatitude(String latitude) {
		this.latitude = latitude;
	}

	@Column(name = "LONGITUDE", length = 45)
	public String getLongitude() {
		return this.longitude;
	}

	public void setLongitude(String longitude) {
		this.longitude = longitude;
	}

	@Column(name = "POSTAL_CODE", length = 45)
	public String getPostalCode() {
		return this.postalCode;
	}

	public void setPostalCode(String postalCode) {
		this.postalCode = postalCode;
	}

	@Column(name = "REVISION_NO")
	public Long getRevisionNo() {
		return this.revisionNo;
	}

	public void setRevisionNo(Long revisionNo) {
		this.revisionNo = revisionNo;
	}

	@Column(name = "BRANCH_ID", length = 50)
	public String getBranchId() {
		return this.branchId;
	}

	public void setBranchId(String branchId) {
		this.branchId = branchId;
	}

	
	
	@ManyToOne(fetch = FetchType.EAGER, cascade = CascadeType.ALL)
	@JoinColumn(name="LOCATION_ID",nullable=false)
	@JsonIgnore
	public Locality getLocality() {
		return this.locality;
	}

	public void setLocality(Locality localityId) {
		this.locality =localityId;
	}
	@OneToMany( fetch = FetchType.LAZY,mappedBy = "city")
	@JsonIgnore
	public Set<GramPanchayat> getGramPanchayats() {

		return gramPanchayats;
	}

	/**
	 * Sets the gram panchayats.
	 * 
	 * @param gramPanchayats
	 *            the new gram panchayats
	 */
	public void setGramPanchayats(Set<GramPanchayat> gramPanchayats) {

		this.gramPanchayats = gramPanchayats;
	}

	
	public void setVillages(Set<Village> villages) {

		this.villages = villages;
	}

	/**
	 * Gets the villages.
	 * 
	 * @return the villages
	 */
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "city")
	@JsonIgnore
	public Set<Village> getVillages() {

		return villages;
	}

	/**
	 * Gets the code with name.
	 * 
	 * @return the code with name
	 */
	@Transient
	public String getCodeWithName() {

		return name + " - " + code;
	}
	
	@Transient
	public List<String> getBranchesList() {
		return branchesList;
	}

	public void setBranchesList(List<String> branchesList) {
		this.branchesList = branchesList;
	}
	
	@Transient
	public String getStateName() {
		return stateName;
	}

	public void setStateName(String stateName) {
		this.stateName = stateName;
	}

	@Transient
	public String getCountryName() {
		return countryName;
	}

	public void setCountryName(String countryName) {
		this.countryName = countryName;
	}




}

