package com.sourcetrace.eses.entity;
// Generated 23 Jun, 2020 5:09:17 PM by Hibernate Tools 5.0.6.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * NomInfo generated by hbm2java
 */
@Entity
@Table(name = "nom_info")
public class NomInfo implements java.io.Serializable {

	private Long id;
	private String name;
	private String relShip;
	private Date dob;
	private String address;

	public NomInfo() {
	}

	public NomInfo(String name, String address) {
		this.name = name;
		this.address = address;
	}

	public NomInfo(String name, String relShip, Date dob, String address) {
		this.name = name;
		this.relShip = relShip;
		this.dob = dob;
		this.address = address;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "ID", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@Column(name = "NAME",  length = 150)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "REL_SHIP", length = 45)
	public String getRelShip() {
		return this.relShip;
	}

	public void setRelShip(String relShip) {
		this.relShip = relShip;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DOB", length = 10)
	public Date getDob() {
		return this.dob;
	}

	public void setDob(Date dob) {
		this.dob = dob;
	}

	@Column(name = "ADDRESS",  length = 150)
	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

}
