package com.sourcetrace.eses.entity;
// Generated 23 Jun, 2020 5:09:17 PM by Hibernate Tools 5.0.6.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * PerfLog generated by hbm2java
 */
@Entity
@Table(name = "perf_log")
public class PerfLog implements java.io.Serializable {

	private Long id;
	private String module;
	private String resource;
	private long duration;
	private int status;
	private String userId;
	private Date logDate;

	public PerfLog() {
	}

	public PerfLog(String module, String resource, long duration, int status, Date logDate) {
		this.module = module;
		this.resource = resource;
		this.duration = duration;
		this.status = status;
		this.logDate = logDate;
	}

	public PerfLog(String module, String resource, long duration, int status, String userId, Date logDate) {
		this.module = module;
		this.resource = resource;
		this.duration = duration;
		this.status = status;
		this.userId = userId;
		this.logDate = logDate;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "ID", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@Column(name = "MODULE",  length = 45)
	public String getModule() {
		return this.module;
	}

	public void setModule(String module) {
		this.module = module;
	}

	@Column(name = "RESOURCE", nullable = false)
	public String getResource() {
		return this.resource;
	}

	public void setResource(String resource) {
		this.resource = resource;
	}

	@Column(name = "DURATION", nullable = false)
	public long getDuration() {
		return this.duration;
	}

	public void setDuration(long duration) {
		this.duration = duration;
	}

	@Column(name = "STATUS", nullable = false)
	public int getStatus() {
		return this.status;
	}

	public void setStatus(int status) {
		this.status = status;
	}

	@Column(name = "USER_ID", length = 45)
	public String getUserId() {
		return this.userId;
	}

	public void setUserId(String userId) {
		this.userId = userId;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "LOG_DATE",  length = 19)
	public Date getLogDate() {
		return this.logDate;
	}

	public void setLogDate(Date logDate) {
		this.logDate = logDate;
	}

}
