package com.sourcetrace.eses.entity;
// Generated 23 Jun, 2020 5:09:17 PM by Hibernate Tools 5.0.6.Final

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Transient;

import org.hibernate.annotations.OrderBy;

import lombok.Getter;
import lombok.Setter;
import org.hibernate.envers.*;

/**
 * FarmCrops generated by hbm2java
 */
@Entity
@Table(name = "planting")
@Setter
@Getter
@Audited
public class Planting extends ParentEntity {

	// @ManyToOne(cascade=CascadeType.ALL)
	@Column(name = "CROP_SEASON")
	private String cropSeason;

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "FARM_CROP")
	private FarmCrops farmCrops;

	@Column(name = "FARM_CROP_ID")
	private String farmCropId;

	/*
	 * @ManyToOne(fetch = FetchType.EAGER, cascade = CascadeType.ALL)
	 * 
	 * @JoinColumn(name = "CROP_NAME") private ProcurementProduct species;
	 */

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "VARIETY")
	private ProcurementVariety variety;

	@ManyToOne(fetch = FetchType.EAGER, cascade = CascadeType.ALL)
	@JoinColumn(name = "GRADE")
	private ProcurementGrade grade;

	@Column(name = "PLANTING_ID")
	private String plantingId;

	@Column(name = "PLANTING_DATE")
	private Date plantingDate;

	@Column(name = "LOT_NO")
	private String lotNo;

	@Column(name = "CROP_CATEGORY")
	private String cropCategory;

	@Column(name = "CULT_AREA")
	private String cultiArea;

	@Column(name = "TYPE_SEED")
	private String seedSource;

	@Column(name = "CHEMICAL_USED")
	private String chemUsed;

	@Column(name = "CHEMICAL_QTY")
	private String chemQty;

	@Column(name = "SEED_QTY_PLANTED")
	private String seedQtyPlanted;

	@Column(name = "SEED_WEEK")
	private String seedWeek;

	@Column(name = "FERTLISER")
	private String fertiliser;

	@Column(name = "TYPE_FERT")
	private String typeOfFert;

	@Column(name = "FERT_QTY")
	private String fertQty;

	@Column(name = "F_LOTNO")
	private String fLotNo;

	@Column(name = "MODE_APP")
	private String modeApp;

	@Column(name = "EXP_HARVEST_WEEK")
	private String expHarvestWeek;

	@Column(name = "EXP_HARVEST_QTY")
	private String expHarvestQty;

	@Column(name = "PLOTTING_STATUS")
	private String plottingStatus;

	@Column(name = "UNIT")
	private String unit;

	@ManyToOne(fetch = FetchType.EAGER, cascade = CascadeType.ALL)
	@JoinColumn(name = "PLOTTING")
	private CoordinatesMap plotting;

	@Column(name = "REVISION_NO")
	private long revisionNo;

	@Column(name = "STATUS")
	private int status;

	@Column(name = "FARMER_ID")
	private Long farmerId;

	@Column(name = "MSG_NO")
	private String msgNo;

	@Column(name = "FIELD_TYPE", columnDefinition = "VARCHAR(255)")
	private String fieldType;
}
