package com.sourcetrace.eses.entity;
// Generated 23 Jun, 2020 5:09:17 PM by Hibernate Tools 5.0.6.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Transient;

/**
 * PmtDetail generated by hbm2java
 */
@Entity
 @Table(name = "pmt_detail")
public class PmtDetail implements java.io.Serializable {

	private Long id;
	private Farmer farmer;
private Pmt pmt;
	
	
	private Long villageId;
	private String ics;
	private Double mtntGrossWeight;
	private Double mtnQuintalWeight;
	private Double mtnrGrossWeight;
	private Long mtntNoOfBags;
	private Long mtnrNoOfBags;
	private Long cooprativeId;
	private String pricePerUnit;
	private String subTotal;
	private String uom;
	private String branchId;
	private Long status;
	private String heap;
	
	private Double grossWeight;
	private Long noOfBags;

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "ID", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "FARMER_ID")
	public Farmer getFarmer() {
		return this.farmer;
	}

	public void setFarmer(Farmer farmer) {
		this.farmer = farmer;
	}



	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "PMT_ID")
	public Pmt getPmt() {
		return this.pmt;
	}

	public void setPmt(Pmt pmt) {
		this.pmt = pmt;
	}

	

	

	@Column(name = "VILLAGE_ID")
	public Long getVillageId() {
		return this.villageId;
	}

	public void setVillageId(Long villageId) {
		this.villageId = villageId;
	}

	@Column(name = "ICS", length = 100)
	public String getIcs() {
		return this.ics;
	}

	public void setIcs(String ics) {
		this.ics = ics;
	}

	@Column(name = "MTNT_GROSS_WEIGHT", precision = 20, scale = 3)
	public Double getMtntGrossWeight() {
		return this.mtntGrossWeight;
	}

	public void setMtntGrossWeight(Double mtntGrossWeight) {
		this.mtntGrossWeight = mtntGrossWeight;
	}

	@Column(name = "MTN_QUINTAL_WEIGHT", precision = 20, scale = 3)
	public Double getMtnQuintalWeight() {
		return this.mtnQuintalWeight;
	}

	public void setMtnQuintalWeight(Double mtnQuintalWeight) {
		this.mtnQuintalWeight = mtnQuintalWeight;
	}

	@Column(name = "MTNR_GROSS_WEIGHT", precision = 20, scale = 3)
	public Double getMtnrGrossWeight() {
		return this.mtnrGrossWeight;
	}

	public void setMtnrGrossWeight(Double mtnrGrossWeight) {
		this.mtnrGrossWeight = mtnrGrossWeight;
	}

	@Column(name = "MTNT_NO_OF_BAGS")
	public Long getMtntNoOfBags() {
		return this.mtntNoOfBags;
	}

	public void setMtntNoOfBags(Long mtntNoOfBags) {
		this.mtntNoOfBags = mtntNoOfBags;
	}

	@Column(name = "MTNR_NO_OF_BAGS")
	public Long getMtnrNoOfBags() {
		return this.mtnrNoOfBags;
	}

	public void setMtnrNoOfBags(Long mtnrNoOfBags) {
		this.mtnrNoOfBags = mtnrNoOfBags;
	}

	@Column(name = "COOPRATIVE_ID")
	public Long getCooprativeId() {
		return this.cooprativeId;
	}

	public void setCooprativeId(Long cooprativeId) {
		this.cooprativeId = cooprativeId;
	}

	@Column(name = "PRICE_PER_UNIT", length = 45)
	public String getPricePerUnit() {
		return this.pricePerUnit;
	}

	public void setPricePerUnit(String pricePerUnit) {
		this.pricePerUnit = pricePerUnit;
	}

	@Column(name = "SUB_TOTAL", length = 45)
	public String getSubTotal() {
		return this.subTotal;
	}

	public void setSubTotal(String subTotal) {
		this.subTotal = subTotal;
	}

	@Column(name = "UOM", length = 45)
	public String getUom() {
		return this.uom;
	}

	public void setUom(String uom) {
		this.uom = uom;
	}

	@Column(name = "BRANCH_ID", length = 50)
	public String getBranchId() {
		return this.branchId;
	}

	public void setBranchId(String branchId) {
		this.branchId = branchId;
	}

	@Column(name = "STATUS")
	public Long getStatus() {
		return this.status;
	}

	public void setStatus(Long status) {
		this.status = status;
	}

	@Column(name = "HEAP", length = 25)
	public String getHeap() {
		return this.heap;
	}

	public void setHeap(String heap) {
		this.heap = heap;
	}

	@Transient
	public Double getGrossWeight() {
		return grossWeight;
	}

	public void setGrossWeight(Double grossWeight) {
		this.grossWeight = grossWeight;
	}

	@Transient
	public Long getNoOfBags() {
		return noOfBags;
	}

	public void setNoOfBags(Long noOfBags) {
		this.noOfBags = noOfBags;
	}

}
