package com.sourcetrace.eses.entity;
// Generated 23 Jun, 2020 5:09:17 PM by Hibernate Tools 5.0.6.Final

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Version;

import org.hibernate.annotations.CreationTimestamp;
import org.hibernate.annotations.FilterDef;
import org.hibernate.annotations.Filters;
import org.hibernate.annotations.ParamDef;
import org.hibernate.annotations.UpdateTimestamp;

import com.fasterxml.jackson.annotation.JsonIgnore;

import lombok.Getter;
import lombok.Setter;
import org.hibernate.envers.*;

/**
 * ProcurementVariety generated by hbm2java
 */
@Entity
@FilterDef(name = "branchFilter", parameters = @ParamDef(name = "branchIdParam", type = "string"))
@Filters(@org.hibernate.annotations.Filter(name = "branchFilter", condition = "branch_id in ( :branchIdParam )"))
@Table(name = "procurement_variety")
@Getter
@Setter
@Audited
public class ProcurementVariety implements java.io.Serializable {
	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "ID", unique = true, nullable = false)

	private Long id;
	@ManyToOne(fetch = FetchType.EAGER, cascade = CascadeType.ALL)
	@JoinColumn(name = "PROCUREMENT_PRODUCT_ID")
	@JsonIgnore

	private ProcurementProduct procurementProduct;
	@Column(name = "NAME", length = 50)
	private String name;
	@Column(name = "CODE", length = 20)

	private String code;
	@Column(name = "REVISION_NO")
	private Long revisionNo;
	@Column(name = "BRANCH_ID", length = 45)
	private String branchId;

	@OneToMany(mappedBy = "procurementVariety")
	private Set<ProcurementGrade> procurementGrades;

	/*@Column(name = "Crop_HS_code", length = 50)
	private String cropHScode;*/
	
	@Column(name = "CREATED_USER", length = 50, columnDefinition = "VARCHAR(255)")
	private String createdUser;
	
	
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CREATED_DATE",  length = 19)
	@CreationTimestamp
	private Date createdDate;
	
	@Column(name = "UPDATED_USER", length = 50, columnDefinition = "VARCHAR(255)")
	private String updatedUser;
	
	
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "UPDATED_DATE",  length = 19)
	@UpdateTimestamp
	private Date updatedDate;

	@Version
	private Integer version;
	
	
	@Column(name = "LAT", length = 50, columnDefinition = "VARCHAR(255)")
	private String latitude;
	
	@Column(name = "LON", length = 50, columnDefinition = "VARCHAR(255)")
	private String longitude;
	
	@Column(name = "IP_ADDR", length = 50, columnDefinition = "VARCHAR(255)")
	private String ipAddr;
	
	

}
