package com.sourcetrace.eses.entity;
// Generated 23 Jun, 2020 5:09:17 PM by Hibernate Tools 5.0.6.Final

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.annotations.FilterDef;
import org.hibernate.annotations.Filters;
import org.hibernate.annotations.ParamDef;

import com.fasterxml.jackson.annotation.JsonIgnore;

/**
 * Procurement generated by hbm2java
 */
@Entity
 @FilterDef(name = "branchFilter", parameters = @ParamDef(name = "branchIdParam", type = "string"))@Filters(@org.hibernate.annotations.Filter(name="branchFilter", condition="branch_id in ( :branchIdParam )"))
@Table(name = "procurement")
public class Procurement implements java.io.Serializable {


	private static final long serialVersionUID = -691522973746677689L;

	public static enum productType {
		GOODS, CARRIER
	}
	public static final String PAYMENT_TXN_TYPE = "416";

	public static final String PROCUREMENT_AMOUNT = "PROCUREMENT AMOUNT";
	public static final String PROCUREMENT_PAYMENT = "PROCUREMENT PAYMENT";
	public static final String PROCUREMENT_PAYMENT_AMOUNT = "PROCUREMENT PAYMENT AMOUNT";
	public static final String CASH_WITHDRAW = "CASH WITHDRAW";
	public static final String TXN_TYPE = "316";
	public static final int DEFAULT_FARMER_ATTENDENCE = 0;
	public static final String PROCURMEMENT = "PROCUREMENT";
	public static final String DELETE_STATUS = "1";
	public static final String PROCURMEMENT_DELETE = "PROCURMEMENT DELETE";
	public static final String REPAYMENT_TXN_TYPE = "702";
	public static final String REPAYMENT_AMOUNT = "PROCUREMENT PAYMENT WITH LOAN DEDUCTION";
	private Long id;
	private SeasonMaster seasonMaster;
	private Integer typee;
	private String invoiceNo;
	private Long villageId;
	private Long trxnAgroId;
	private Long tripSheetId;
	private String poNumber;
	private String paymentMode;
	private Double paymentAmt;
	private Double totalAmount;
	private String mobileNo;
	private String masterType;
	private String masterTypeId;
	private String seasonCode;
	private Farmer farmer;
	private String createdUser;
	private Date createdDate;
	private Date updatedDate;
	private String roadMapCode;
	private String vehicleNo;
	private String farmerAttendance;
	private String substituteName;
	private String ffc;
	private String farmId;
	private String updatedUser;
	private String latitude;
	private String longitude;
	private String branchId;
	private Double totalLabourCost;
	private Double transportCost;
	private Double invoiceCost;
	private String warehouseId;
	private String cropType;
	private Customer buyer;
	private Double actualAmt;
	private Double loanPercentage;
	private Double loanAmt;
	private Double finalPayAmount;
	private String vehicleType;
	private Integer status;
	private Set<ProcurementDetail> procurementDetails = new HashSet<ProcurementDetail>();
	private double loanInterest;
	private double finalPayAmt;
	private double loanRepaymentAmt;


	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "ID", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "SEASON_ID")
	@JsonIgnore
	public SeasonMaster getSeasonMaster() {
		return this.seasonMaster;
	}

	public void setSeasonMaster(SeasonMaster seasonMaster) {
		this.seasonMaster = seasonMaster;
	}

	@Column(name = "TYPEE", nullable = false)
	public Integer getTypee() {
		return this.typee;
	}

	public void setTypee(Integer typee) {
		this.typee = typee;
	}

	@Column(name = "INVOICE_NO", length = 45)
	public String getInvoiceNo() {
		return this.invoiceNo;
	}

	public void setInvoiceNo(String invoiceNo) {
		this.invoiceNo = invoiceNo;
	}

	@Column(name = "VILLAGE_ID")
	public Long getVillageId() {
		return this.villageId;
	}

	public void setVillageId(Long villageId) {
		this.villageId = villageId;
	}

	@Column(name = "TRXN_AGRO_ID")
	public Long getTrxnAgroId() {
		return this.trxnAgroId;
	}

	public void setTrxnAgroId(Long trxnAgroId) {
		this.trxnAgroId = trxnAgroId;
	}

	@Column(name = "TRIP_SHEET_ID")
	public Long getTripSheetId() {
		return this.tripSheetId;
	}

	public void setTripSheetId(Long tripSheetId) {
		this.tripSheetId = tripSheetId;
	}

	@Column(name = "PO_NUMBER", length = 20)
	public String getPoNumber() {
		return this.poNumber;
	}

	public void setPoNumber(String poNumber) {
		this.poNumber = poNumber;
	}

	@Column(name = "PAYMENT_MODE", length = 20)
	public String getPaymentMode() {
		return this.paymentMode;
	}

	public void setPaymentMode(String paymentMode) {
		this.paymentMode = paymentMode;
	}

	@Column(name = "PAYMENT_AMT", precision = 20)
	public Double getPaymentAmt() {
		return this.paymentAmt;
	}

	public void setPaymentAmt(Double paymentAmt) {
		this.paymentAmt = paymentAmt;
	}

	@Column(name = "TOTAL_AMOUNT", precision = 20)
	public Double getTotalAmount() {
		return this.totalAmount;
	}

	public void setTotalAmount(Double totalAmount) {
		this.totalAmount = totalAmount;
	}

	@Column(name = "MOBILE_NO", length = 20)
	public String getMobileNo() {
		return this.mobileNo;
	}

	public void setMobileNo(String mobileNo) {
		this.mobileNo = mobileNo;
	}

	@Column(name = "MASTER_TYPE", length = 8)
	public String getMasterType() {
		return this.masterType;
	}

	public void setMasterType(String masterType) {
		this.masterType = masterType;
	}

	@Column(name = "MASTER_TYPE_ID", length = 8)
	public String getMasterTypeId() {
		return this.masterTypeId;
	}

	public void setMasterTypeId(String masterTypeId) {
		this.masterTypeId = masterTypeId;
	}

	@Column(name = "SEASON_CODE", length = 25)
	public String getSeasonCode() {
		return this.seasonCode;
	}

	public void setSeasonCode(String seasonCode) {
		this.seasonCode = seasonCode;
	}


	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "FARMER_ID")
	public Farmer getFarmer() {
		return farmer;
	}

	public void setFarmer(Farmer farmer) {
		this.farmer = farmer;
	}

	@Column(name = "CREATED_USER", length = 25)
	public String getCreatedUser() {
		return this.createdUser;
	}

	public void setCreatedUser(String createdUser) {
		this.createdUser = createdUser;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CREATED_DATE", length = 19)
	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "UPDATED_DATE", length = 19)
	public Date getUpdatedDate() {
		return this.updatedDate;
	}

	public void setUpdatedDate(Date updatedDate) {
		this.updatedDate = updatedDate;
	}

	@Column(name = "ROAD_MAP_CODE", length = 30)
	public String getRoadMapCode() {
		return this.roadMapCode;
	}

	public void setRoadMapCode(String roadMapCode) {
		this.roadMapCode = roadMapCode;
	}

	@Column(name = "VEHICLE_NO", length = 30)
	public String getVehicleNo() {
		return this.vehicleNo;
	}

	public void setVehicleNo(String vehicleNo) {
		this.vehicleNo = vehicleNo;
	}

	@Column(name = "FARMER_ATTENDANCE", length = 10)
	public String getFarmerAttendance() {
		return this.farmerAttendance;
	}

	public void setFarmerAttendance(String farmerAttendance) {
		this.farmerAttendance = farmerAttendance;
	}

	@Column(name = "SUBSTITUTE_NAME", length = 45)
	public String getSubstituteName() {
		return this.substituteName;
	}

	public void setSubstituteName(String substituteName) {
		this.substituteName = substituteName;
	}

	@Column(name = "FFC", length = 45)
	public String getFfc() {
		return this.ffc;
	}

	public void setFfc(String ffc) {
		this.ffc = ffc;
	}

	@Column(name = "FARM_ID", length = 20)
	public String getFarmId() {
		return this.farmId;
	}

	public void setFarmId(String farmId) {
		this.farmId = farmId;
	}

	@Column(name = "UPDATED_USER", length = 20)
	public String getUpdatedUser() {
		return this.updatedUser;
	}

	public void setUpdatedUser(String updatedUser) {
		this.updatedUser = updatedUser;
	}

	@Column(name = "LATITUDE", length = 20)
	public String getLatitude() {
		return this.latitude;
	}

	public void setLatitude(String latitude) {
		this.latitude = latitude;
	}

	@Column(name = "LONGITUDE", length = 20)
	public String getLongitude() {
		return this.longitude;
	}

	public void setLongitude(String longitude) {
		this.longitude = longitude;
	}

	@Column(name = "BRANCH_ID", length = 45)
	public String getBranchId() {
		return this.branchId;
	}

	public void setBranchId(String branchId) {
		this.branchId = branchId;
	}

	@Column(name = "TOTAL_LABOUR_COST", precision = 25)
	public Double getTotalLabourCost() {
		return this.totalLabourCost;
	}

	public void setTotalLabourCost(Double totalLabourCost) {
		this.totalLabourCost = totalLabourCost;
	}

	@Column(name = "TRANSPORT_COST", precision = 20)
	public Double getTransportCost() {
		return this.transportCost;
	}

	public void setTransportCost(Double transportCost) {
		this.transportCost = transportCost;
	}

	@Column(name = "INVOICE_COST", precision = 20)
	public Double getInvoiceCost() {
		return this.invoiceCost;
	}

	public void setInvoiceCost(Double invoiceCost) {
		this.invoiceCost = invoiceCost;
	}

	

	@Column(name = "CROP_TYPE", length = 4)
	public String getCropType() {
		return this.cropType;
	}

	public void setCropType(String cropType) {
		this.cropType = cropType;
	}
		
	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(nullable=true, name = "BUYER")
	@JsonIgnore
	public Customer getBuyer() {
		return this.buyer;
	}

	public void setBuyer(Customer buyer) {
		this.buyer = buyer;
	}

	@Column(name = "ACTUAL_AMT", precision = 25, scale = 3)
	public Double getActualAmt() {
		return this.actualAmt;
	}

	public void setActualAmt(Double actualAmt) {
		this.actualAmt = actualAmt;
	}

	@Column(name = "LOAN_PERCENTAGE", precision = 10, scale = 3)
	public Double getLoanPercentage() {
		return this.loanPercentage;
	}

	public void setLoanPercentage(Double loanPercentage) {
		this.loanPercentage = loanPercentage;
	}

	@Column(name = "LOAN_AMT", precision = 25, scale = 3)
	public Double getLoanAmt() {
		return this.loanAmt;
	}

	public void setLoanAmt(Double loanAmt) {
		this.loanAmt = loanAmt;
	}

	@Column(name = "FINAL_PAY_AMOUNT", precision = 25, scale = 3)
	public Double getFinalPayAmount() {
		return this.finalPayAmount;
	}

	public void setFinalPayAmount(Double finalPayAmount) {
		this.finalPayAmount = finalPayAmount;
	}

	@Column(name = "VEHICLE_TYPE", length = 70)
	public String getVehicleType() {
		return this.vehicleType;
	}

	public void setVehicleType(String vehicleType) {
		this.vehicleType = vehicleType;
	}

	@Column(name = "STATUS")
	public Integer getStatus() {
		return this.status;
	}

	public void setStatus(Integer status) {
		this.status = status;
	}

	@OneToMany( mappedBy = "procurement")
	public Set<ProcurementDetail> getProcurementDetails() {
		return this.procurementDetails;
	}

	public void setProcurementDetails(Set<ProcurementDetail> procurementDetails) {
		this.procurementDetails = procurementDetails;
	}
	@Column(name = "LOAN_INTEREST_PERCENT")
	public double getLoanInterest() {
		return loanInterest;
	}

	public void setLoanInterest(double loanInterest) {
		this.loanInterest = loanInterest;
	}
	@Column(name = "FINAL_PAY_AMT")
	public double getFinalPayAmt() {
		return finalPayAmt;
	}

	public void setFinalPayAmt(double finalPayAmt) {
		this.finalPayAmt = finalPayAmt;
	}

	@Column(name = "LOAN_REPAYMENT_AMT")
	public double getLoanRepaymentAmt() {
		return loanRepaymentAmt;
	}

	public void setLoanRepaymentAmt(double loanRepaymentAmt) {
		this.loanRepaymentAmt = loanRepaymentAmt;
	}

}
