package com.sourcetrace.eses.entity;
// Generated 23 Jun, 2020 5:09:17 PM by Hibernate Tools 5.0.6.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * ProcurementDetail generated by hbm2java
 */
@Entity
@Table(name = "procurement_detail")
public class ProcurementDetail implements java.io.Serializable {

	private Long id;
	private Procurement procurement;

	
	private String quality;
	private String batchNo;
	private Long numberOfBags;
	private Double grossWeight;
	private Double tareWeight;
	private Double netWeight;
	private Double ratePerUnit;
	private Double subTotal;
	private Double dryLoss;
	private Double gradingLoss;
	private String unit;
	private Long numberOfFruitBags;

	public ProcurementDetail() {
	}

	public ProcurementDetail(Procurement procurement, 
			 String quality, String batchNo, Long numberOfBags,
			Double grossWeight, Double tareWeight, Double netWeight, Double ratePerUnit, Double subTotal,
			Double dryLoss, Double gradingLoss, String unit, Long numberOfFruitBags) {
		this.procurement = procurement;
		
		
		this.quality = quality;
		this.batchNo = batchNo;
		this.numberOfBags = numberOfBags;
		this.grossWeight = grossWeight;
		this.tareWeight = tareWeight;
		this.netWeight = netWeight;
		this.ratePerUnit = ratePerUnit;
		this.subTotal = subTotal;
		this.dryLoss = dryLoss;
		this.gradingLoss = gradingLoss;
		this.unit = unit;
		this.numberOfFruitBags = numberOfFruitBags;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "ID", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "PROCUREMENT_ID")
	public Procurement getProcurement() {
		return this.procurement;
	}

	public void setProcurement(Procurement procurement) {
		this.procurement = procurement;
	}

	

	

	@Column(name = "QUALITY", length = 35)
	public String getQuality() {
		return this.quality;
	}

	public void setQuality(String quality) {
		this.quality = quality;
	}

	@Column(name = "BATCH_NO", length = 20)
	public String getBatchNo() {
		return this.batchNo;
	}

	public void setBatchNo(String batchNo) {
		this.batchNo = batchNo;
	}

	@Column(name = "NUMBER_OF_BAGS")
	public Long getNumberOfBags() {
		return this.numberOfBags;
	}

	public void setNumberOfBags(Long numberOfBags) {
		this.numberOfBags = numberOfBags;
	}

	@Column(name = "GROSS_WEIGHT", precision = 20, scale = 3)
	public Double getGrossWeight() {
		return this.grossWeight;
	}

	public void setGrossWeight(Double grossWeight) {
		this.grossWeight = grossWeight;
	}

	@Column(name = "TARE_WEIGHT", precision = 20, scale = 3)
	public Double getTareWeight() {
		return this.tareWeight;
	}

	public void setTareWeight(Double tareWeight) {
		this.tareWeight = tareWeight;
	}

	@Column(name = "NET_WEIGHT", precision = 20, scale = 3)
	public Double getNetWeight() {
		return this.netWeight;
	}

	public void setNetWeight(Double netWeight) {
		this.netWeight = netWeight;
	}

	@Column(name = "RATE_PER_UNIT", precision = 20)
	public Double getRatePerUnit() {
		return this.ratePerUnit;
	}

	public void setRatePerUnit(Double ratePerUnit) {
		this.ratePerUnit = ratePerUnit;
	}

	@Column(name = "SUB_TOTAL", precision = 20, scale = 3)
	public Double getSubTotal() {
		return this.subTotal;
	}

	public void setSubTotal(Double subTotal) {
		this.subTotal = subTotal;
	}

	@Column(name = "DRY_LOSS", precision = 20, scale = 4)
	public Double getDryLoss() {
		return this.dryLoss;
	}

	public void setDryLoss(Double dryLoss) {
		this.dryLoss = dryLoss;
	}

	@Column(name = "GRADING_LOSS", precision = 20, scale = 4)
	public Double getGradingLoss() {
		return this.gradingLoss;
	}

	public void setGradingLoss(Double gradingLoss) {
		this.gradingLoss = gradingLoss;
	}

	@Column(name = "UNIT", length = 20)
	public String getUnit() {
		return this.unit;
	}

	public void setUnit(String unit) {
		this.unit = unit;
	}

	@Column(name = "NUMBER_OF_FRUIT_BAGS")
	public Long getNumberOfFruitBags() {
		return this.numberOfFruitBags;
	}

	public void setNumberOfFruitBags(Long numberOfFruitBags) {
		this.numberOfFruitBags = numberOfFruitBags;
	}

}
