package com.sourcetrace.eses.entity;
// Generated 23 Jun, 2020 5:09:17 PM by Hibernate Tools 5.0.6.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * SavedDynamicReport generated by hbm2java
 */
@Entity
@Table(name = "saved_dynamic_report")
public class SavedDynamicReport implements java.io.Serializable {

	private Integer id;
	private String title;
	private String des;
	private String query;
	private String headerFields;
	private String filterData;
	private String entity;
	private String fieldsSelected;
	private String groupByField;

	public SavedDynamicReport() {
	}

	public SavedDynamicReport(String title, String des, String query, String headerFields, String filterData,
			String entity, String fieldsSelected, String groupByField) {
		this.title = title;
		this.des = des;
		this.query = query;
		this.headerFields = headerFields;
		this.filterData = filterData;
		this.entity = entity;
		this.fieldsSelected = fieldsSelected;
		this.groupByField = groupByField;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "title")
	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	@Column(name = "des")
	public String getDes() {
		return this.des;
	}

	public void setDes(String des) {
		this.des = des;
	}

	@Column(name = "query", length = 2550)
	public String getQuery() {
		return this.query;
	}

	public void setQuery(String query) {
		this.query = query;
	}

	@Column(name = "header_fields", length = 2550)
	public String getHeaderFields() {
		return this.headerFields;
	}

	public void setHeaderFields(String headerFields) {
		this.headerFields = headerFields;
	}

	@Column(name = "filter_data", length = 2550)
	public String getFilterData() {
		return this.filterData;
	}

	public void setFilterData(String filterData) {
		this.filterData = filterData;
	}

	@Column(name = "ENTITY", length = 10)
	public String getEntity() {
		return this.entity;
	}

	public void setEntity(String entity) {
		this.entity = entity;
	}

	@Column(name = "FIELDS_SELECTED")
	public String getFieldsSelected() {
		return this.fieldsSelected;
	}

	public void setFieldsSelected(String fieldsSelected) {
		this.fieldsSelected = fieldsSelected;
	}

	@Column(name = "GROUP_BY_FIELD", length = 250)
	public String getGroupByField() {
		return this.groupByField;
	}

	public void setGroupByField(String groupByField) {
		this.groupByField = groupByField;
	}

}
