package com.sourcetrace.eses.entity;
// Generated 23 Jun, 2020 5:09:17 PM by Hibernate Tools 5.0.6.Final

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.validation.GroupSequence;

import com.sourcetrace.eses.util.First;
import com.sourcetrace.eses.util.Second;

/**
 * SmsGroupDetail generated by hbm2java
 */
@Entity
@Table(name = "sms_group_detail")
@GroupSequence({ SmsGroupDetail.class, First.class, Second.class })
public class SmsGroupDetail implements java.io.Serializable  {
	 public static final String PROFILE_TYPE_FARMER = "FARMER";
	    public static final String PROFILE_TYPE_FIELD_STAFF = "FIELD_STAFF";
	    public static final String PROFILE_TYPE_USER = "USER";
	    public static final String PROFILE_TYPE_OTHER = "OTHER";
	    public static final String PROFILE_TYPE_ALL = "ALL";
	private Long id;
	private long profileId;
	private String profileType;
	private Character isActive;
	private Date createDt;
	private String createUserName;
	private Date lastUpdateDt;
	private String updateUserName;
	 private SmsGroupHeader smsGroup;

	

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "ID", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@Column(name = "PROFILE_ID", nullable = false)
	public long getProfileId() {
		return this.profileId;
	}

	public void setProfileId(long profileId) {
		this.profileId = profileId;
	}


	@Column(name = "PROFILE_TYPE",  length = 20)
	public String getProfileType() {
		return this.profileType;
	}

	public void setProfileType(String profileType) {
		this.profileType = profileType;
	}

	@Column(name = "IS_ACTIVE", length = 1)
	public Character getIsActive() {
		return this.isActive;
	}

	public void setIsActive(Character isActive) {
		this.isActive = isActive;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CREATE_DT", length = 19)
	public Date getCreateDt() {
		return this.createDt;
	}

	public void setCreateDt(Date createDt) {
		this.createDt = createDt;
	}

	@Column(name = "CREATE_USER_NAME", length = 45)
	public String getCreateUserName() {
		return this.createUserName;
	}

	public void setCreateUserName(String createUserName) {
		this.createUserName = createUserName;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "LAST_UPDATE_DT", length = 19)
	public Date getLastUpdateDt() {
		return this.lastUpdateDt;
	}

	public void setLastUpdateDt(Date lastUpdateDt) {
		this.lastUpdateDt = lastUpdateDt;
	}

	@Column(name = "UPDATE_USER_NAME", length = 45)
	public String getUpdateUserName() {
		return this.updateUserName;
	}

	public void setUpdateUserName(String updateUserName) {
		this.updateUserName = updateUserName;
	}
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "GROUP_ID")
	public SmsGroupHeader getSmsGroup() {
		return smsGroup;
	}

	public void setSmsGroup(SmsGroupHeader smsGroup) {
		this.smsGroup = smsGroup;
	}

}
