package com.sourcetrace.eses.entity;
// Generated 24 Jun, 2020 6:21:14 PM by Hibernate Tools 5.0.6.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * TxnCfgSeq generated by hbm2java
 */
@Entity
@Table(name = "txn_cfg_seq")
public class TxnCfgSeq implements java.io.Serializable {

	private long id;

	public TxnCfgSeq() {
	}

	public TxnCfgSeq(long id) {
		this.id = id;
	}

	@Id

	@Column(name = "ID", unique = true, nullable = false)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

}
