package com.sourcetrace.eses.entity;
// Generated 24 Jun, 2020 6:21:14 PM by Hibernate Tools 5.0.6.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * WarehouseStockReturnDetails generated by hbm2java
 */
@Entity

@Table(name = "warehouse_stock_return_details")
public class WarehouseStockReturnDetails implements java.io.Serializable {

	private Long id;
	private WarehouseStockReturn warehouseStockReturn;
	private Long productId;
	private Double costPrice;
	private Long damagedStock;
	private Long noStockRetured;
	private Double amount;

	public WarehouseStockReturnDetails() {
	}

	public WarehouseStockReturnDetails(WarehouseStockReturn warehouseStockReturn, Long productId, Double costPrice,
			Long damagedStock, Long noStockRetured, Double amount) {
		this.warehouseStockReturn = warehouseStockReturn;
		this.productId = productId;
		this.costPrice = costPrice;
		this.damagedStock = damagedStock;
		this.noStockRetured = noStockRetured;
		this.amount = amount;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "ID", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "WAREHOUSE_STOCK_RETURN_ID")
	public WarehouseStockReturn getWarehouseStockReturn() {
		return this.warehouseStockReturn;
	}

	public void setWarehouseStockReturn(WarehouseStockReturn warehouseStockReturn) {
		this.warehouseStockReturn = warehouseStockReturn;
	}

	@Column(name = "PRODUCT_ID")
	public Long getProductId() {
		return this.productId;
	}

	public void setProductId(Long productId) {
		this.productId = productId;
	}

	@Column(name = "COST_PRICE", precision = 20)
	public Double getCostPrice() {
		return this.costPrice;
	}

	public void setCostPrice(Double costPrice) {
		this.costPrice = costPrice;
	}

	@Column(name = "DAMAGED_STOCK")
	public Long getDamagedStock() {
		return this.damagedStock;
	}

	public void setDamagedStock(Long damagedStock) {
		this.damagedStock = damagedStock;
	}

	@Column(name = "NO_STOCK_RETURED")
	public Long getNoStockRetured() {
		return this.noStockRetured;
	}

	public void setNoStockRetured(Long noStockRetured) {
		this.noStockRetured = noStockRetured;
	}

	@Column(name = "AMOUNT", precision = 20)
	public Double getAmount() {
		return this.amount;
	}

	public void setAmount(Double amount) {
		this.amount = amount;
	}

}
