
-- -- Market Linkage Menu
INSERT INTO `ese_menu` VALUES (null, 'service.marketLinkage', 'Market Linkage', 'marketLinkage_list.action', 27, 3, 0, 0, 0, 0, NULL);
SET @max_menu_id = (SELECT MAX(id) FROM ese_menu);

INSERT INTO `ese_role_menu`(`ID`, `MENU_ID`, `ROLE_ID`) VALUES (NULL, @max_menu_id, 1);

INSERT INTO `ese_menu_action` (`MENU_ID`, `ACTION_ID`) VALUES (@max_menu_id, '1');
INSERT INTO `ese_menu_action` (`MENU_ID`, `ACTION_ID`) VALUES (@max_menu_id, '2');

INSERT INTO `ese_ent` (`ID`, `NAME`) VALUES (NULL, 'service.marketLinkage.list');
INSERT INTO `ese_ent` (`ID`, `NAME`) VALUES (NULL, 'service.marketLinkage.create');

INSERT INTO `ese_role_ent` (`ROLE_ID`, `ENT_ID`) VALUES ('1', (SELECT id FROM ese_ent WHERE ese_ent.`NAME`='service.marketLinkage.list'));
INSERT INTO `ese_role_ent` (`ROLE_ID`, `ENT_ID`) VALUES ('1', (SELECT id FROM ese_ent WHERE ese_ent.`NAME`='service.marketLinkage.create'));
INSERT INTO `ese_role_ent` (`ROLE_ID`, `ENT_ID`) VALUES ('2', (SELECT id FROM ese_ent WHERE ese_ent.`NAME`='service.marketLinkage.list'));
INSERT INTO `ese_role_ent` (`ROLE_ID`, `ENT_ID`) VALUES ('2', (SELECT id FROM ese_ent WHERE ese_ent.`NAME`='service.marketLinkage.create'));



-- -- Market Linkage Report
INSERT INTO `ese_menu` VALUES (null, 'report.marketLinkage', 'Market Linkage', 'dynamicViewReport_list.action?id=14', 27, 3, 0, 0, 0, 0, NULL);
SET @max_menu_id = (SELECT MAX(id) FROM ese_menu);

INSERT INTO `ese_role_menu`(`ID`, `MENU_ID`, `ROLE_ID`) VALUES (NULL, @max_menu_id, 1);
INSERT INTO `ese_menu_action` (`MENU_ID`, `ACTION_ID`) VALUES (@max_menu_id, '1');
INSERT INTO `ese_ent` (`ID`, `NAME`) VALUES (NULL, 'report.marketLinkage.list');
INSERT INTO `ese_role_ent` (`ROLE_ID`, `ENT_ID`) VALUES ('1', (SELECT id FROM ese_ent WHERE ese_ent.`NAME`='report.marketLinkage.list'));

-- -- Market Linkage Buyer Report
INSERT INTO `dynamic_report_config_filter`(`ID`, `REPORT_CONFIG`, `FIELD`, `LABEL`, `METHOD`, `STATUS`, `ORDERR`, `TYPE`, `IS_DATE_FILTER`, `DEFAULT_FILTER`) VALUES (NULL, 12, 'STATE_CODE', 'state', 'getStatesDynamic', 1, 1, 3, NULL, NULL);
INSERT INTO `dynamic_report_config_filter`(`ID`, `REPORT_CONFIG`, `FIELD`, `LABEL`, `METHOD`, `STATUS`, `ORDERR`, `TYPE`, `IS_DATE_FILTER`, `DEFAULT_FILTER`) VALUES (NULL, 12, 'CROP_CODE', 'crop', 'getCropsDynamic', 1, 2, 3, NULL, NULL);
INSERT INTO `dynamic_report_config_filter`(`ID`, `REPORT_CONFIG`, `FIELD`, `LABEL`, `METHOD`, `STATUS`, `ORDERR`, `TYPE`, `IS_DATE_FILTER`, `DEFAULT_FILTER`) VALUES (NULL, 12, 'VARIETY', 'variety', 'select  distinct  pv.name as name,pv.name as name1 from procurement_variety pv', 1, 3, 5, NULL, NULL);
INSERT INTO `dynamic_report_config_filter`(`ID`, `REPORT_CONFIG`, `FIELD`, `LABEL`, `METHOD`, `STATUS`, `ORDERR`, `TYPE`, `IS_DATE_FILTER`, `DEFAULT_FILTER`) VALUES (NULL, 12, 'GRADE', 'grade', 'select  distinct  pg.name as name,pg.name as name1 from procurement_grade pg', 1, 4, 5, NULL, NULL);
INSERT INTO `dynamic_report_config_filter`(`ID`, `REPORT_CONFIG`, `FIELD`, `LABEL`, `METHOD`, `STATUS`, `ORDERR`, `TYPE`, `IS_DATE_FILTER`, `DEFAULT_FILTER`) VALUES (NULL, 12, 'BUYER', 'BUYER', 'SELECT DISTINCT BUYER_NAME as NAME,BUYER_NAME as NAME1 from market_buyer', 1, 5, 5, NULL, NULL);

INSERT INTO `dynamic_report_config_detail`(`ID`, `REPORT_CONFIG_ID`, `LABEL_NAME`, `FIELD`, `ACESS_TYPE`, `PARAMTERS`, `METHOD`, `GROUP_PROP`, `SUM_PROP`, `WIDTH`, `ORDERR`, `IS_GRID_AVAILABILITY`, `IS_EXPORT_AVAILABILITY`, `STATUSS`, `EXPRESSION`, `ALIGNMENT`, `IS_FOOTER_SUM`, `IS_GROUP_HEADER`, `DATA_TYPE`) VALUES (NULL, 12, 'id', 'ID', 1, NULL, NULL, 0, 0, 50, 1, 1, 1, 1, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `dynamic_report_config_detail`(`ID`, `REPORT_CONFIG_ID`, `LABEL_NAME`, `FIELD`, `ACESS_TYPE`, `PARAMTERS`, `METHOD`, `GROUP_PROP`, `SUM_PROP`, `WIDTH`, `ORDERR`, `IS_GRID_AVAILABILITY`, `IS_EXPORT_AVAILABILITY`, `STATUSS`, `EXPRESSION`, `ALIGNMENT`, `IS_FOOTER_SUM`, `IS_GROUP_HEADER`, `DATA_TYPE`) VALUES (NULL, 12, 'branch', 'BRANCH_ID', 1, NULL, NULL, 0, 0, 100, 2, 1, 1, 1, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `dynamic_report_config_detail`(`ID`, `REPORT_CONFIG_ID`, `LABEL_NAME`, `FIELD`, `ACESS_TYPE`, `PARAMTERS`, `METHOD`, `GROUP_PROP`, `SUM_PROP`, `WIDTH`, `ORDERR`, `IS_GRID_AVAILABILITY`, `IS_EXPORT_AVAILABILITY`, `STATUSS`, `EXPRESSION`, `ALIGNMENT`, `IS_FOOTER_SUM`, `IS_GROUP_HEADER`, `DATA_TYPE`) VALUES (NULL, 12, 'state', 'STATE', 1, NULL, NULL, 0, 0, 100, 3, 1, 1, 1, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `dynamic_report_config_detail`(`ID`, `REPORT_CONFIG_ID`, `LABEL_NAME`, `FIELD`, `ACESS_TYPE`, `PARAMTERS`, `METHOD`, `GROUP_PROP`, `SUM_PROP`, `WIDTH`, `ORDERR`, `IS_GRID_AVAILABILITY`, `IS_EXPORT_AVAILABILITY`, `STATUSS`, `EXPRESSION`, `ALIGNMENT`, `IS_FOOTER_SUM`, `IS_GROUP_HEADER`, `DATA_TYPE`) VALUES (NULL, 12, 'Product', 'PRODUCT', 1, NULL, NULL, 0, 0, 100, 4, 1, 1, 1, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `dynamic_report_config_detail`(`ID`, `REPORT_CONFIG_ID`, `LABEL_NAME`, `FIELD`, `ACESS_TYPE`, `PARAMTERS`, `METHOD`, `GROUP_PROP`, `SUM_PROP`, `WIDTH`, `ORDERR`, `IS_GRID_AVAILABILITY`, `IS_EXPORT_AVAILABILITY`, `STATUSS`, `EXPRESSION`, `ALIGNMENT`, `IS_FOOTER_SUM`, `IS_GROUP_HEADER`, `DATA_TYPE`) VALUES (NULL, 12, 'Variety', 'VARIETY', 1, NULL, NULL, 0, 0, 100, 5, 1, 1, 1, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `dynamic_report_config_detail`(`ID`, `REPORT_CONFIG_ID`, `LABEL_NAME`, `FIELD`, `ACESS_TYPE`, `PARAMTERS`, `METHOD`, `GROUP_PROP`, `SUM_PROP`, `WIDTH`, `ORDERR`, `IS_GRID_AVAILABILITY`, `IS_EXPORT_AVAILABILITY`, `STATUSS`, `EXPRESSION`, `ALIGNMENT`, `IS_FOOTER_SUM`, `IS_GROUP_HEADER`, `DATA_TYPE`) VALUES (NULL, 12, 'Grade', 'GRADE', 1, NULL, NULL, 0, 0, 100, 6, 1, 1, 1, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `dynamic_report_config_detail`(`ID`, `REPORT_CONFIG_ID`, `LABEL_NAME`, `FIELD`, `ACESS_TYPE`, `PARAMTERS`, `METHOD`, `GROUP_PROP`, `SUM_PROP`, `WIDTH`, `ORDERR`, `IS_GRID_AVAILABILITY`, `IS_EXPORT_AVAILABILITY`, `STATUSS`, `EXPRESSION`, `ALIGNMENT`, `IS_FOOTER_SUM`, `IS_GROUP_HEADER`, `DATA_TYPE`) VALUES (NULL, 12, 'Buyer', 'BUYER', 1, NULL, NULL, 0, 0, 100, 7, 1, 1, 1, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `dynamic_report_config_detail`(`ID`, `REPORT_CONFIG_ID`, `LABEL_NAME`, `FIELD`, `ACESS_TYPE`, `PARAMTERS`, `METHOD`, `GROUP_PROP`, `SUM_PROP`, `WIDTH`, `ORDERR`, `IS_GRID_AVAILABILITY`, `IS_EXPORT_AVAILABILITY`, `STATUSS`, `EXPRESSION`, `ALIGNMENT`, `IS_FOOTER_SUM`, `IS_GROUP_HEADER`, `DATA_TYPE`) VALUES (NULL, 12, 'Email', 'EMAIL', 1, NULL, NULL, 0, 0, 100, 8, 1, 1, 1, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `dynamic_report_config_detail`(`ID`, `REPORT_CONFIG_ID`, `LABEL_NAME`, `FIELD`, `ACESS_TYPE`, `PARAMTERS`, `METHOD`, `GROUP_PROP`, `SUM_PROP`, `WIDTH`, `ORDERR`, `IS_GRID_AVAILABILITY`, `IS_EXPORT_AVAILABILITY`, `STATUSS`, `EXPRESSION`, `ALIGNMENT`, `IS_FOOTER_SUM`, `IS_GROUP_HEADER`, `DATA_TYPE`) VALUES (NULL, 12, 'Contact Number', 'CONTACT_NO', 1, NULL, NULL, 0, 0, 100, 9, 1, 1, 1, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `dynamic_report_config_detail`(`ID`, `REPORT_CONFIG_ID`, `LABEL_NAME`, `FIELD`, `ACESS_TYPE`, `PARAMTERS`, `METHOD`, `GROUP_PROP`, `SUM_PROP`, `WIDTH`, `ORDERR`, `IS_GRID_AVAILABILITY`, `IS_EXPORT_AVAILABILITY`, `STATUSS`, `EXPRESSION`, `ALIGNMENT`, `IS_FOOTER_SUM`, `IS_GROUP_HEADER`, `DATA_TYPE`) VALUES (NULL, 12, 'Available Qty', 'AVAILABLE_QTY', 1, NULL, NULL, 0, 0, 100, 10, 1, 1, 1, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `dynamic_report_config_detail`(`ID`, `REPORT_CONFIG_ID`, `LABEL_NAME`, `FIELD`, `ACESS_TYPE`, `PARAMTERS`, `METHOD`, `GROUP_PROP`, `SUM_PROP`, `WIDTH`, `ORDERR`, `IS_GRID_AVAILABILITY`, `IS_EXPORT_AVAILABILITY`, `STATUSS`, `EXPRESSION`, `ALIGNMENT`, `IS_FOOTER_SUM`, `IS_GROUP_HEADER`, `DATA_TYPE`) VALUES (NULL, 12, 'Purchase Qty', 'PURCHASE_QTY', 1, NULL, NULL, 0, 0, 100, 11, 1, 1, 1, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `dynamic_report_config_detail`(`ID`, `REPORT_CONFIG_ID`, `LABEL_NAME`, `FIELD`, `ACESS_TYPE`, `PARAMTERS`, `METHOD`, `GROUP_PROP`, `SUM_PROP`, `WIDTH`, `ORDERR`, `IS_GRID_AVAILABILITY`, `IS_EXPORT_AVAILABILITY`, `STATUSS`, `EXPRESSION`, `ALIGNMENT`, `IS_FOOTER_SUM`, `IS_GROUP_HEADER`, `DATA_TYPE`) VALUES (NULL, 12, 'Status', 'STATUS', 8, '', '{\"0\":\"Pending\",\"1\":\"Approved\"}', 0, 0, 100, 12, 1, 1, 1, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `dynamic_report_config_detail`(`ID`, `REPORT_CONFIG_ID`, `LABEL_NAME`, `FIELD`, `ACESS_TYPE`, `PARAMTERS`, `METHOD`, `GROUP_PROP`, `SUM_PROP`, `WIDTH`, `ORDERR`, `IS_GRID_AVAILABILITY`, `IS_EXPORT_AVAILABILITY`, `STATUSS`, `EXPRESSION`, `ALIGNMENT`, `IS_FOOTER_SUM`, `IS_GROUP_HEADER`, `DATA_TYPE`) VALUES (NULL, 12, 'Transfered Qty', 'TRANSFERED_QTY', 1, NULL, NULL, 0, 0, 100, 13, 1, 1, 1, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `dynamic_report_config_detail`(`ID`, `REPORT_CONFIG_ID`, `LABEL_NAME`, `FIELD`, `ACESS_TYPE`, `PARAMTERS`, `METHOD`, `GROUP_PROP`, `SUM_PROP`, `WIDTH`, `ORDERR`, `IS_GRID_AVAILABILITY`, `IS_EXPORT_AVAILABILITY`, `STATUSS`, `EXPRESSION`, `ALIGNMENT`, `IS_FOOTER_SUM`, `IS_GROUP_HEADER`, `DATA_TYPE`) VALUES (NULL, 12, 'Rate Per Unit', 'RATE', 1, NULL, NULL, 0, 0, 100, 14, 1, 1, 1, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `dynamic_report_config_detail`(`ID`, `REPORT_CONFIG_ID`, `LABEL_NAME`, `FIELD`, `ACESS_TYPE`, `PARAMTERS`, `METHOD`, `GROUP_PROP`, `SUM_PROP`, `WIDTH`, `ORDERR`, `IS_GRID_AVAILABILITY`, `IS_EXPORT_AVAILABILITY`, `STATUSS`, `EXPRESSION`, `ALIGNMENT`, `IS_FOOTER_SUM`, `IS_GROUP_HEADER`, `DATA_TYPE`) VALUES (NULL, 12, 'Amount', 'TOTAL_AMOUNT', 1, NULL, NULL, 0, 0, 100, 15, 1, 1, 1, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `dynamic_report_config_detail`(`ID`, `REPORT_CONFIG_ID`, `LABEL_NAME`, `FIELD`, `ACESS_TYPE`, `PARAMTERS`, `METHOD`, `GROUP_PROP`, `SUM_PROP`, `WIDTH`, `ORDERR`, `IS_GRID_AVAILABILITY`, `IS_EXPORT_AVAILABILITY`, `STATUSS`, `EXPRESSION`, `ALIGNMENT`, `IS_FOOTER_SUM`, `IS_GROUP_HEADER`, `DATA_TYPE`) VALUES (NULL, 12, 'Payment Amount', 'PAYMENT_AMOUNT', 1, NULL, NULL, 0, 0, 100, 16, 1, 1, 1, NULL, NULL, NULL, NULL, NULL);

INSERT INTO `dynamic_report_config`(`ID`, `REPORT`, `FETCH_TYPE`, `GRID_TYPE`, `STATUS`, `BRANCH_ID`, `ENTITY_NAME`, `XLS_FILE`, `ALIAS`, `PARENT_ID`, `GROUP_PROPERTY`, `DETAIL_METHOD`) VALUES (NULL, 'Market Linkage Report', 3, '1', '1', NULL, 'vw_market_linkage', 'MarketLinkageReport', NULL, NULL, NULL, NULL);


ALTER TABLE `market_buyer` 
ADD COLUMN `VARIETY` bigint(20) NULL AFTER `REVISION_NO`,
ADD COLUMN `PRODUCT` bigint(20) NULL AFTER `VARIETY`;


