-- ----------------------------
-- TABLE STRUCTURE FOR FILTER
-- ----------------------------
DROP TABLE IF EXISTS `FILTER`;
CREATE TABLE `FILTER` (
  `ID` INT(11) NOT NULL,
  `CODE` VARCHAR(45) COLLATE UTF8_UNICODE_CI NOT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=INNODB DEFAULT CHARSET=UTF8 COLLATE=UTF8_UNICODE_CI;

-- --------------------------------
-- TABLE STRUCTURE FOR ESE_ACTION
-- --------------------------------
DROP TABLE IF EXISTS `ESE_ACTION`;
CREATE TABLE `ESE_ACTION` (
  `ID` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `NAME` VARCHAR(45) COLLATE UTF8_UNICODE_CI NOT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=INNODB DEFAULT CHARSET=UTF8 COLLATE=UTF8_UNICODE_CI;

-- ----------------------------
-- TABLE STRUCTURE FOR ESE_ENT
-- ----------------------------
DROP TABLE IF EXISTS `ESE_ENT`;
CREATE TABLE `ESE_ENT` (
  `ID` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `NAME` VARCHAR(255) COLLATE UTF8_UNICODE_CI NOT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=INNODB  DEFAULT CHARSET=UTF8 COLLATE=UTF8_UNICODE_CI;

-- ------------------------------
-- TABLE STRUCTURE FOR ESE_MENU
-- ------------------------------
DROP TABLE IF EXISTS `ese_menu`;
CREATE TABLE `ese_menu` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `NAME` varchar(45) COLLATE utf8_unicode_ci DEFAULT NULL,
  `DES` varchar(45) COLLATE utf8_unicode_ci DEFAULT NULL,
  `URL` varchar(100) COLLATE utf8_unicode_ci DEFAULT NULL,
  `ORD` int(2) DEFAULT NULL,
  `PARENT_ID` bigint(20) DEFAULT NULL,
  `FILTER` tinyint(4) DEFAULT NULL,
  `EXPORT_AVILABILITY` tinyint(2) DEFAULT '0',
  `DIMENSION` tinyint(4) DEFAULT '0',
  PRIMARY KEY (`ID`),
  KEY `FK_ESE_MENU_ESE_MENU1` (`PARENT_ID`) USING BTREE,
  CONSTRAINT `ese_menu_ibfk_1` FOREIGN KEY (`PARENT_ID`) REFERENCES `ese_menu` (`ID`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

-- -------------------------------------
-- TABLE STRUCTURE FOR ESE_MENU_ACTION
-- -------------------------------------
DROP TABLE IF EXISTS `ese_menu_action`;
CREATE TABLE `ese_menu_action` (
  `MENU_ID` bigint(20) NOT NULL,
  `ACTION_ID` bigint(20) NOT NULL,
  KEY `FK_ESE_MENU_HAS_ESE_ACTION_ESE_MENU1` (`MENU_ID`) USING BTREE,
  KEY `FK_ESE_MENU_HAS_ESE_ACTION_ESE_ACTION1` (`ACTION_ID`) USING BTREE,
  CONSTRAINT `ese_menu_action_ibfk_1` FOREIGN KEY (`ACTION_ID`) REFERENCES `ese_action` (`ID`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `ese_menu_action_ibfk_2` FOREIGN KEY (`MENU_ID`) REFERENCES `ese_menu` (`ID`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

-- ------------------------------
-- TABLE STRUCTURE FOR ESE_ROLE
-- ------------------------------
DROP TABLE IF EXISTS `ESE_ROLE`;
CREATE TABLE `ESE_ROLE` (
  `ID` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `NAME` VARCHAR(45) COLLATE UTF8_UNICODE_CI NOT NULL,
  `DES` VARCHAR(45) COLLATE UTF8_UNICODE_CI DEFAULT NULL,
  `FILTER_ID` INT(11) DEFAULT NULL,
  PRIMARY KEY (`ID`),
  KEY `FK_ESE_ROLE_FILTER1` (`FILTER_ID`),
  CONSTRAINT `FK_ESE_ROLE_FILTER1` FOREIGN KEY (`FILTER_ID`) REFERENCES `FILTER` (`ID`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=INNODB DEFAULT CHARSET=UTF8 COLLATE=UTF8_UNICODE_CI;

-- ----------------------------------
-- TABLE STRUCTURE FOR ESE_ROLE_ENT
-- ---------------------------------
DROP TABLE IF EXISTS `ese_role_ent`;
CREATE TABLE `ese_role_ent` (
  `ROLE_ID` bigint(20) NOT NULL,
  `ENT_ID` bigint(20) NOT NULL,
  KEY `FK_ESE_ROLE_HAS_ESE_ENT_ESE_ROLE1` (`ROLE_ID`) USING BTREE,
  KEY `FK_ESE_ROLE_HAS_ESE_ENT_ESE_ENT1` (`ENT_ID`) USING BTREE,
  CONSTRAINT `ese_role_ent_ibfk_1` FOREIGN KEY (`ENT_ID`) REFERENCES `ese_ent` (`ID`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `ese_role_ent_ibfk_2` FOREIGN KEY (`ROLE_ID`) REFERENCES `ese_role` (`ID`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

-- ------------------------------------
-- TABLE STRUCTURE FOR ESE_ROLE_MENU
-- ------------------------------------
DROP TABLE IF EXISTS `ese_role_menu`;
CREATE TABLE `ese_role_menu` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `MENU_ID` bigint(20) NOT NULL,
  `ROLE_ID` bigint(20) NOT NULL,
  PRIMARY KEY (`ID`),
  KEY `FK_ESE_ROLE_MENU_ESE_ROLE1` (`ROLE_ID`) USING BTREE,
  KEY `FK_ESE_ROLE_MENU_ESE_MENU1` (`MENU_ID`) USING BTREE,
  CONSTRAINT `ese_role_menu_ibfk_1` FOREIGN KEY (`MENU_ID`) REFERENCES `ese_menu` (`ID`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `ese_role_menu_ibfk_2` FOREIGN KEY (`ROLE_ID`) REFERENCES `ese_role` (`ID`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;
